### ISSUE TITLE
b3dm batch attributes are not available in three.js

### ISSUE THREAD

**Issue by liberostelios** [NASA-AMMOS/3DTilesRendererJS#110]
While B3DMLoaderBase parses the batch attributes of a `b3dm` tile, there is no way to access those data from the 3D scene (e.g., by using a raycaster and trying to find the attributes of a triangle).

I think that could be easily solved by assigning those information to the scene object created by the three.js `TilesRenderer`. I did something like this [here](https://github.com/liberostelios/3DTilesRendererJS/commit/b3e55e2b3acd5f0a6276042444d4e024fe29613b), so then I am able to pick those information when necessary ([here](https://github.com/liberostelios/3DTilesRendererJS/blob/06600aec2424a3f5ddb464f2b3bdafae85e1f78e/example/viewer.js#L336-L348) is an example how). Not sure if that's the most elegant way to solve this, but it worked for me.

**Comment by gkjohnson** [comment]
I think this is a good addition. I'm torn between putting it in the loaders themselves and putting it into the 3DTilesRenderer. Why don't we set `batchTable` and `featureTable` on the scene itself in `B3DMLoader`. The same should be done for `I3DMLoader` and `PNTSLoader`.

Would you like to make a PR?

Thanks for contributing back improvements!

**Comment by liberostelios** [comment]
Sure, I will make a PR! But I'll have to clean up the code first, because I've hacked a lot of things and this is still based on an older version of the code.

**Comment by gkjohnson** [comment]
Fixed in #113
