### ISSUE TITLE
Should the error be calculated for empty tiles?

### ISSUE THREAD

**Issue by liberostelios** [NASA-AMMOS/3DTilesRendererJS#111]
Currently, there is a check for whether a tile has content before the error calculation is done. I guess that works in case where tiles are used to represent different LoDs.

In our case, as discussed in #77, we decided to use empty tiles to allow for a "flatter" area to be hidden when the error was sufficient enough. That required some change in the renderer (see [here](https://github.com/liberostelios/3DTilesRendererJS/commit/a4c0065ec137529a859ae7aacafdb966c753ea5e#diff-25d902c24283ab8cfbac54dfa101ad31)).

I am not sure if there are any negative side-effects for normal case, but it works good enough for us. We built a tileset where, basically, we have one layer of empty tiles with an error and each of that has as child its respective tile with the content. That way, the renderer "picks" the empty tile, if it's far enough, or the content tile, if it's close.

Would that benefit others? What's the rationale behind not computing the error of empty tiles? Just for performance gains? I believe maybe there could be an option to switch between computing the error for empty tiles or not, so that it can serve any case. I would be willing to implement that and make a PR, if you will.

**Comment by gkjohnson** [comment]
I just searched for "error" and "empty" in the spec and it's actually not clear to me what the behavior should be. It's possible the right thing to do is what you're suggesting. I think it's worth making a question in the 3d tiles spec repo to clarify why the correct thing to do here is:

https://github.com/CesiumGS/3d-tiles

**Comment by liberostelios** [comment]
That's a good point. I'll raise the question.

**Comment by liberostelios** [comment]
It's been 20 days since I've raised the question to 3D Tiles repo and they haven't responded yet. For us this is important, so I made a patch in #119 to add an option for our use case.

I understand this might seem unnecessary for you, so we are working with 3DTilesRendererJS as a submodule and we are fine with doing the whole thing as a fork. But since I had a discussion with GIS colleagues and it also makes sense for them, I decided to make the PR. So feel free to merge it if you think it doesn't add unnecessary complexity to the system.

**Comment by gkjohnson** [comment]
I've just pinged them so I'll wait on #119 to see if they get back to us in a few days. I'm hesitant to support non standard 3d tiles features but I do see that the behavior you're looking for is useful. It would be nice to know if there were a standard way to achieve it 🤔

**Comment by gkjohnson** [comment]
Looks like the correct behavior is actually to stop at empty tiles! Thanks submitting that issue.

It might take me a bit to get to merging #119 because I want to make sure I've looked at all the possible ramifications in the code but the behavior seems to be correct. We should also try to understand why it creates the need for two updates after a tileset has been loaded.

Thanks!

**Comment by liberostelios** [comment]
That's good news! I am glad this was proven helpful, after all.

In theory, this shouldn't change much so I am not sure why the two updates are getting necessary after it. What's even more weird, is that when I enabled the two update calls and put log messages to the console for "tiles loaded", "model loaded" and "render", the outcome was showing something like:

```
tiles loaded
render
model loaded
render
render
```

So, two updates are needed, but somehow they end up running after the model is loaded? While if I put it back to one update call, the it's just:

```
tiles loaded
render
```

**Comment by gkjohnson** [comment]
Just commented on the PR but I'm still not seeing that problem even in your branch. Perhaps there's an issue elsewhere in your app?
