### ISSUE TITLE
Why children content in main tileset.json not downloaded

### ISSUE THREAD

**Issue by vertalik** [NASA-AMMOS/3DTilesRendererJS#132]
My main tileset.json:
`{
  "asset": {
    "version": "0.0",
    "tilesetVersion": "1.0.0-obj23dtiles",
    "gltfUpAxis": "Y"
  },
  "geometricError": 200,
  "root": {
    "transform": [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0],
    "content": {"uri": "root.b3dm"},
    "boundingVolume": {
      "box": [
        30.760990505933865,
        46.435937875341,
        30.76094991807889,
        46.43596945354099,
        0,
        40
      ]
    },
    "children": [
      {
        "boundingVolume": { "box": [
          30.75552400203268,
          46.43220691008585,
          30.755483414177704,
          46.43223848828585,
          0,
          40
        ] },
        "content": { "uri": "1.b3dm" },
        "children": [],
        "geometricError": 0.0,
        "refine": "REPLACE"
      },
      {
        "boundingVolume": { "box": [
          30.75552573890749,
          46.434666032107614,
          30.755485151052515,
          46.43469761030761,
          0,
          40
        ] },
        "content": { "uri": "2.b3dm" },
        "children": [],
        "geometricError": 0.0,
        "refine": "REPLACE"
      }
    ],
    "geometricError": 0,
    "refine": "REPLACE"
  }
} ` 

Then -> TilesRenderer( 'tileset.json' );
In dev tools i see only my root.b3dm file. How can I use cache ?

**Comment by gkjohnson** [comment]
Hello! Unfortunately there's not enough information here for me to help with your problem. Can you provide some code showing how you are creating and updating the tiles renderer?

Also keep in mind that the child tiles will only be downloaded when they are in view of the camera and it is close enough to them to pass the error threshold.

**Comment by vertalik** [comment]
_"tiles will only be downloaded when they are in view of the camera"_ - Thanks, I will check this. 
The code I get from "Basic TilesRenderer" - README.md. Then I downloaded example/data  folder from git and put the tileset.json to the TilesRenderer(); - work's fine - the moon async loaded ( in dev tools - source i saw all child b3dm files). Then i put my tileset and he is loaded only main file without child. I dont know, maybe exist some tool to generate the valid tileset and b3dm files. Can you tell me please, how you created this files ???

**Comment by gkjohnson** [comment]
>  Can you tell me please, how you created this files ???

The example data is generated from an internal tool that is not open source (though it may be in the future). There are a few tools on github to convert files to 3d tiles including the one it looks like the one you're using (`obj23dtiles`). [This tool](https://github.com/CesiumGS/3d-tiles-validator) looks like it can be used to validate 3d tiles datasets, though I'm less familiar with these.

> Then i put my tileset and he is loaded only main file without child.

Can you upload your tileset as a zip?

**Comment by vertalik** [comment]
Thanks, is working now. I increased a geometricError value at main content.

**Comment by gkjohnson** [comment]
> Thanks, is working now. I increased a geometricError value at main content.

You can also lower the `tilesRenderer.errorTarget` value if you would like the error threshold to be met more quickly.
