### ISSUE TITLE
Loaded tiles seem to reset when turning the camera with loadSiblings === false

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#142]
- Disable `loadSiblings`
- Set `errorThreshold` to `Infinity`
- Load large dataset
- Get camera close to surface
- Let data load
- Turn the camera

**Comment by gkjohnson** [comment]
I suspect it's because of this check which stops traversal and displays the parent when the relevant children aren't loaded yet. When turning the camera a new (unloaded) child comes into view and suddenly the parent doesn't traverse the children because it wants to wait for the child to load. What should the behavior here be?

https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/d462193f7d1a20fd6b7724039e3fa38c9382a92e/src/base/traverseFunctions.js#L226-L247

**Comment by gkjohnson** [comment]
Perhaps we should continue to traverse in this case if any children were visible?

**Comment by dbuck** [comment]
Had you tested this theory out at all? I recently shut off loadSiblings to try and reduce some of the request load, and this blinking behavior started showing up very frequently.

**Comment by gkjohnson** [comment]
> Had you tested this theory out at all?

I haven't revisited this since opening the issue since we're not adjusting the loadSiblings option at the moment. But looking at [Cesiums use of their loadSiblings option](https://github.com/CesiumGS/cesium/blob/dacc86c6a32f1ece62d66ac20b6ea5ff6f040ad0/Source/Scene/Cesium3DTilesetTraversal.js#L479) it looks like it only applies to tiles with the ADD refinement. You can see [here](https://github.com/CesiumGS/cesium/blob/dacc86c6a32f1ece62d66ac20b6ea5ff6f040ad0/Source/Scene/Cesium3DTilesetTraversal.js#L459-L460) that if the refinement is set to REPLACE (and tiles are not being skipped) then children and siblings are loaded regardless of the `loadSiblings` flag. Given that it seems like the flag would be of little benefit unless you have a lot of ADD refinement tiles in your tileset.

> I recently shut off loadSiblings to try and reduce some of the request load

What specifically are you trying to cut down on? Is it load times? Or hiccups when loading tiles? I wonder if there are improvements that could be made to the tile skipping logic that could be made to help.

**Comment by gkjohnson** [comment]
Load siblings has been removed in #667 since the behavior seemed broken and did not match the behavior from Cesium for the same setting, either. #480 outlines possible options for replicating the "skip traversal" behavior from Cesium.
