### ISSUE TITLE
Prioritize loads of closer tiles

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#143]
We want tiles that are nearby and noticeable to be loaded more quickly. This could be achieved by taking into account the apparent error or distance to the camera when sorting the tiles to load. What's in view of the frustum should be prioritized, as well.

**Options**

```js
function priorityFunc( tile ) {

    return tile.__error;

}
```

```js
function priorityFunc( tile ) {

    return tile.__distance;

}
```

**Comment by dbuck** [comment]
I did a little looking at this, as I was seeing more delay while loading the higher detail tiles than I was expecting to see.

In order to do some prioritizing by __distance or __error, I had to adjust TilesRenderer.calculateError to still run for tiles which have geometricError of 0. Doing that required setting a min(Epsilon, tile.geometricError), because, div0 ;)

Once full detail tiles also included the error calc, then a test sorting function which considered both tree depth and screen space error started to work a bit better, though I'm sure it will adjust further as we get more test tilesets to work with:

```
// A priority callback that includes some screen space error consideration in addition to default tree depth
function priorityFunc( tile ) {

  const defaultPriority = 1 / ( tile.__depthFromRenderedParent + 1 );
  let errorPriority = 1 / (tile.__error + 1);
  
  // if error priority is 0, then we're *VERY* close to that tile, and should bump it up a lod level?
  // TBD if this is horribly bad in practice? It may work as long as it doesn't jump multiple levels? TBD
  if (errorPriority === 0) {
    errorPriority = -0.5;
  }

  return defaultPriority - errorPriority;
}

tiles.downloadQueue.priorityCallback = priorityFunc;
tiles.parseQueue.priorityCallback = priorityFunc;
```

**Comment by gkjohnson** [comment]
Hey @dbuck! Thanks for sharing your findings. I'm feeling more and more like somehow using the screen space error to determine drive order would be a pretty good improvement.

> In order to do some prioritizing by __distance or __error, I had to adjust TilesRenderer.calculateError to still run for tiles which have geometricError of 0.

I believe if `geometricError` is `0` then `tile.__error` should always be zero so I don't think any adjustments should be needed to use error in the function. `tile.cached.distance` will only be set when fully running `computeError`, though.

I like adjusting the "base priority" from depth by one computed from the screen error but one potential issue I see is that "error" values may be vastly different scales depending on different tilesets and how they were generated which would affect how well this approach works. I wonder if there would somehow be a way to normalize the difference in scales the error values and depth values when doing this computation?

Something else that comes to mind is that a loaded tile will only be displayed once all the sibling tiles have been loaded. I wonder if it would be worth somehow including whether any of the siblings have been loaded in the priority heuristic? But I guess one step at a time 😁 

Do you have a demo showing the difference in load behavior? Have you tried just basing load priority on the current screen space error value? I'm interested to check it out when I have time.

**Comment by dbuck** [comment]
> Have you tried just basing load priority on the current screen space error value? I'm interested to check it out when I have time.

Sure, it works to a point, but it doesn't adjust the download queue as the camera continues to move, so tiles pushed into the queue from the previous camera view may not still load in the order desired based on the updated camera view over time?

> I believe if geometricError is 0 then tile.__error should always be zero so I don't think any adjustments should be needed to use error in the function. tile.cached.distance will only be set when fully running computeError, though.

Yep, the distance check is the key, as it allows priority shifts in the queued tiles with geometricError = 0.

> Do you have a demo showing the difference in load behavior?

Hmm, nothing I can show yet, but maybe I can swap out the actual mesh for some mocks.

**Comment by gkjohnson** [comment]
> Sure, it works to a point, but it doesn't adjust the download queue as the camera continues to move, so tiles pushed into the queue from the previous camera view may not still load in the order desired based on the updated camera view over time?

Oh I see because error is not updated for tiles that aren't traversed but are still in the queues. In this case you should be able to sort by [tile._lastFrameVisited](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/base/traverseFunctions.js#L21) which will be larger only for tiles that have been updated most recently.

> Yep, the distance check is the key, as it allows priority shifts in the queued tiles with geometricError = 0.

I see there's still value to having the distance, though 🤔 I suppose just removing the early return from the `calculateError` function is enough here?

> Hmm, nothing I can show yet, but maybe I can swap out the actual mesh for some mocks.

We recently released some [tiled Mars data](https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/mars.html) that should be complex enough to demonstrate the new behavior with if you want to use that.

Both the priority callbacks for PriorityQueue and LRUCache, though, are structured to just take one tile and return a single number. With these kinds of more sophisticated priority strategies we may need to restructure both classes to take a more traditional "prioritySort" function that takes two tiles, instead:

```js
( a, b ) => {

  if ( a._lastUsedFrame !== b._lastUsedFrame ) {

    return a._lastUsedFrame - b._lastUsedFrame;

  } else if ( a._error !== b._error ) {

    return a._error - b._error;

  } else {

    return b.cached.distance - a.cached.distance;

  }

}
```

**Comment by dbuck** [comment]
> I suppose just removing the early return from the calculateError function is enough here?
That and min(epsilon/geometricError) to avoid the divide by zero in the screen space error calc

The `__lastUsedFrame` is a nice tip, I didn't notice that was available as a way to reprioritize tiles that fell out of the frustum, the distance/error only version still loads tiles behind the camera before it loads tiles in the view if they are at the same error level!

Though honestly, I think that priority func you have in the last message should behave pretty well, and if that were the default I don't think I'd need to override it?

If these calculated properties are to be allowed for use in the priority functions, they need to be documented, and with any caveats about if/when their values are filled in?

**Comment by gkjohnson** [comment]
> That and min(epsilon/geometricError) to avoid the divide by zero in the screen space error calc

Are you referring to [this line here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/7eafbb5db92017f37170c23cc196694984816487/src/three/TilesRenderer.js#L810) where we divide by the distance to the tile which could be zero? If so I think dividing by 0 is okay here because it will just wind up being `Infinity` and will behave fine in comparisons.

> If these calculated properties are to be allowed for use in the priority functions, they need to be documented, and with any caveats about if/when their values are filled in?

I think I'm okay with using them as they are for now and once we settle on a good priority function we can solidify and document the added and expected variables on the tile objects.

> Though honestly, I think that priority func you have in the last message should behave pretty well, and if that were the default I don't think I'd need to override it?

Great! Are you interested in making a PR with those changes?

**Comment by dbuck** [comment]
> Great! Are you interested in making a PR with those changes?

Will do, I have much of it in a fork already. I have a couple small d.ts fixes also.

> if that were the default I don't think I'd need to override it?
After more consideration, I don't think that's true! I will need to override the default priority function afterall ;) I have a texture lod streaming/system on top of the 3d tileset which is based off of some occlusion info, and I'd very much like to include that in the priority function also, so that the different download queues can play a little nicer together on the users resources.

That said, that func works well enough for me now before I've integrated the occlusion info !

The biggest question for that I have would be, if we (as a package dev) need these properties of Tile Object in order to make a good priority function, then the properties should be documented / exposed / typed in some way so that we (as an end user) can effectively replace the priority function, and have some visibility into if they change as the package evolves.

**Comment by gkjohnson** [comment]
> Will do, I have much of it in a fork already. I have a couple small d.ts fixes also.

Awesome!

> I have a texture lod streaming/system on top of the 3d tileset which is based off of some occlusion info

I assume the occlusion info you're referring to is extra meta data you guys are generating for the individual tiles, right? Not something that's built into 3d tiles?

> The biggest question for that I have would be, if we (as a package dev) need these properties of Tile Object in order to make a good priority function, then the properties should be documented / exposed / typed in some way so that we (as an end user) can effectively replace the priority function, and have some visibility into if they change as the package evolves.

I agree. If it looks like the distance to camera value is important for making a more effective priority sort function then it should probably be added onto the tile object itself like `tile.__closestDistance` or `tile.__distanceToCamera`  rather than defining it on the `tile.cached` object, which is more the catch-all for data needed by the three.js implementation of the tiles renderer. We would also have to note that the distance value is expected to be set on the tile object when running the `calculateError` function.

Thanks for your help! This will be a good improvement for the project.

**Comment by RomTreg** [comment]
Hi Guys, did we finally finish this issue?
