### ISSUE TITLE
select the component function of the model

### ISSUE THREAD

**Issue by yoyomule** [NASA-AMMOS/3DTilesRendererJS#152]
Hello, can you consider implementing each component that can be clicked, so that you can associate attributes and other associated information in the model itself. Similar to cesium's BIM selection component function and 3D Tiles Feature Picking.Thanks.
![image](https://user-images.githubusercontent.com/10000818/104994898-55eeb680-5a60-11eb-9d9e-13be6d72590a.png)
![image](https://user-images.githubusercontent.com/10000818/104994689-e4af0380-5a5f-11eb-80fa-906619bb7463.png)

**Comment by gkjohnson** [comment]
Hi @yoyomule!

This looks like reading and displaying batch table data to me which you can already do. Raycasting is already support, as well.

There's a snippet of code available [in the README](https://github.com/NASA-AMMOS/3DTilesRendererJS#read-batch-id-and-batch-table-data) that shows how to read data from the batch table associated with a mesh. And [this demo](https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/b3dmExample.html) shows it in practice. Hover over the buildings to highlight them and see the batch table entries per batch item.

Is that what you're looking for?

**Comment by gkjohnson** [comment]
Ping @yoyomule -- did the documentation and b3dm example in the above comment address your issue?

**Comment by yoyomule** [comment]
> Ping @yoyomule -- did the documentation and b3dm example in the above comment address your issue?

Thank you, it is ok after preliminary testing, we need further research.

**Comment by lishanlei** [comment]
I have tried the example that you menthioned. However I founded that this example is just for loading one file of b3dm format. Now I used CesiumLab to tile a obj model, and I got a tileset.json file and a bunch of b3dm. Then I used TilesRenderer to load it, and used your example to get batchTable and hoveredBatchid. But I still couldn't get the right object when I click it.

Here is the batchTable format I get:
![image](https://user-images.githubusercontent.com/23512984/108584822-40cab780-737f-11eb-8f97-8a3e5fb91f3d.png)

**Comment by gkjohnson** [comment]
> However I founded that this example is just for loading one file of b3dm format.

Yes -- I linked to that that example to demonstrate how to get the batch table for an object and how to read the contents. You can use approach in that example in conjunction with the tiles renderer raycast to get batch table information for a tile.

> Then I used TilesRenderer to load it, and used your example to get batchTable and hoveredBatchid. But I still couldn't get the right object when I click it.

Can you elaborate on what you mean by this? How are you getting the object and what are you expecting to happen? The documentation for the couple functions on the BatchTable is [in the README](https://github.com/NASA-AMMOS/3DTilesRendererJS#batchtable).

**Comment by lishanlei** [comment]
Sorry about my description. I use TilesRenderer class to load my 3D tiles model, just like this:
var tilesRenderer = new TilesRenderer('static/tiles/tileset.json');

This tileset has a lot b3dm model. After I get a batchTable and batch id associated with a mesh through click my model, I don't know how to highlight it.

**Comment by lishanlei** [comment]
Could you provide a example about How to highlight the clicked object for a tileset.json 3D tiles model?
The model file structure just like this:
 
![image](https://user-images.githubusercontent.com/23512984/108585880-d5d0af00-7385-11eb-8780-b256d064c578.png)

**Comment by gkjohnson** [comment]
> I don't know how to highlight it.

Got it -- highlighting models based on batch id requires some custom shader code which is injected [with this function](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/b3dmExample.js#L30-L73) in the example. And you can swap the tile geometry materials in the [onLoadModel](https://github.com/NASA-AMMOS/3DTilesRendererJS#onloadmodel) callback when using the tiles renderer.

I don't expect to add code that will automatically adjust the materials so they can be highlighted because many use cases do not need it and there are a lot of different ways to highlight something. so I think it should be up to the user code I'm happy to discuss it more, though, and perhaps it can be made easier.

Do you mind making a new issue to discuss highlighting geometry based on batch id, though? As far as I understand this issue was originally about reading data from the batch table.

**Comment by lishanlei** [comment]
Couldn't agree more!!

**Comment by lishanlei** [comment]
Couldn't agree more!!

**Comment by lishanlei** [comment]
Couldn't agree more!!

**Comment by lishanlei** [comment]
Couldn't agree more!!

**Comment by gkjohnson** [comment]
I'm gonna close this for now because I think the solution I mentioned above should be sufficient. @yoyomule we can reopen if that solution doesn't work and discuss new features and / or update the docs to be more clear if necessary.

Thanks!
