### ISSUE TITLE
Some models of bim still cannot be displayed and an error occurs

### ISSUE THREAD

**Issue by yoyomule** [NASA-AMMOS/3DTilesRendererJS#153]
Some models of bim still cannot be displayed and an error occurs. I provide the address of cesium ion for your analysis. It is normal in cesium. 
token：eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwM2RiZjA2Zi04ZmVkLTQ3ZDEtODcyMi1iZmRiNThmOGIyZjAiLCJpZCI6MTk4MiwiaWF0IjoxNTMwOTE1MjcwfQ.NrYvOPolAxoq7ueAJUNDjVY9BzM1kBTjn1FX3J0nNWc

asset id：257841
![image](https://user-images.githubusercontent.com/10000818/105015176-39f90e00-5a7c-11eb-9fd8-7a901be05b6c.png)
The other is a model that can be displayed normally, the token is the same, and the asset id is 257692.
![image](https://user-images.githubusercontent.com/10000818/105015440-88a6a800-5a7c-11eb-946c-dfb4a3e2ed56.png)

**Comment by gkjohnson** [comment]
Hello! Thanks for providing data to test with.

For the first tile set (asset id `57841`) it looks like `CMPT` tile format type are used which I have not had test data for so there's likely a bug in the loading. I'll take a look fixing that over the next couple weeks.

Regarding the second tile set (asset id `257692`) I'm not seeing anything that sticks out as incorrect in the loading. The tile set only contains a single child b3dm file in it. What is it expected to look like?

Thanks again!

**Comment by yoyomule** [comment]
Thank you, the second model is indeed normal, but my method of generating 3dtile is the same. I am sending it here for comparison. Looking forward to your work.
