### ISSUE TITLE
Bug: With large / deep tilesets there's an occasional flickering of a tile when quickly zooming in and out

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#155]
Even when errorThreshold === Infinity

Possibly related to LRU cache limits?

**Comment by gkjohnson** [comment]
Visible in denser displays with this demo:

https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/mars.html

Possibly this could be related to two tiles sharing an LRU Cache instance?

**Comment by segments-tobias** [comment]
Hi @gkjohnson, I believe I have the same problem in my application.
Here's a video of the tileset flickering when orbiting/zooming. It only seems to occur on larger tilesets indeed.

You can see the flicker for yourself by opening [this URL](https://segments.ai/admin-tobias/pandaset-clone/samples/809fd955-3410-45d1-8b6d-b1f86c122459/ground-truth) and toggling the merged point cloud in the floating toolbar on the right side of the screen.

https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/89590365/94b9ed30-dbe3-4cf3-b5a5-acb4395b1a88

**Comment by gkjohnson** [comment]
This looks very different - the previous issue was just a single tile that popped in late by a frame, not the full tileset disappearing. You'll have to verify why this is happening but I'm not convinced this a 3d tiles renderer issue at the moment.

**Comment by segments-tobias** [comment]
Ah okay. I'll see if I can investigate further and will create a new issue if needed.
The full tileset is not disappearing FYI: the lowest LOD remains loaded (although it's hard to see from the video).
