### ISSUE TITLE
Bug: When I use Angular 11 ,   Module not found: Error: Can't resolve 'path' in xxxxxxxxxx

### ISSUE THREAD

**Issue by HappyKent** [NASA-AMMOS/3DTilesRendererJS#156]
When I use Angular 11    
Module not found: Error: Can't resolve 'path' in xxxxxxxxxx
urlJoin.js
TilesRendererBase.js

**Comment by gkjohnson** [comment]
Hi @HappyKent!

I'm unfamiliar with Angular. What build environment are you using? Typically the `path` package is configured to be filled in by [path-browserify](https://www.npmjs.com/package/path-browserify) in the build process.

**Comment by gkjohnson** [comment]
I assume setting up the build process to use `path-browserify` fixed the issue. If this continues to be an issue let me know and we can reopen this and figure out how to address it!
