### ISSUE TITLE
help wanted for a problem using the package in a NuxtJS application

### ISSUE THREAD

**Issue by ericpascual** [NASA-AMMOS/3DTilesRendererJS#157]
Hi,

I'm trying to embed the package in a NuxtJS application already displaying 3D scenes with ThreeJS, but get the following error when  the vue containing the `import ... from '3d-tiles-renderer'` clause is loaded : 

> Must use import to load ES Module: /path/to/project/node_modules/3d-tiles-renderer/src/index.js require() of ES modules is not supported. require() of /path/to/project/node_modules/3d-tiles-renderer/src/index.js from /path/to/project/node_modules/vue-server-renderer/build.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /path/to/project/node_modules/3d-tiles-renderer/package.json.

I understand that it has something to do with imports and require statements, but didn't succeed in fixing the problem even after trying the various suggestions (including patching dependencies code !!) found by Googling.

I confess not being expert in JS packaging wizardry and that posts involving babel and friends didn't help me very much, although I've the feeling that the solution is maybe there.

Thanks a lot in advance for any indication which could help me solve this issue.

Best regards.

**Comment by gkjohnson** [comment]
Hello! This sounds like more of a NuxtJS question and unfortunately I'm unfamiliar with that tool. As far as I know this package is following the proper conventions for distributing module packages (type: 'module' in the package.json) so it's up to the build tool to handle it correctly.

**Comment by ericpascual** [comment]
Thanks Garret for replying so quickly.

Based on what the error message says, I'm not sure that the problem is NuxtJS specific. It refers to the usage of import, require and ES modules. I've already developed a couple of project based on NuxtJS and additional third party packages (including ThreeJS for instance), and have never encountered this message before. Same for a colleague of mine who is more experienced with this frameworks than I'm and to whom I've asked the question.

BTW, after having analyzed the project node_modules directory content, among the 894 installed packages, only 3 of them include the "type: module" setting (3d-tiles-renderer, colorette and nanoid). Maybe the other projects I've worked on don't use module type packages.

**Comment by gkjohnson** [comment]
The error as formatted in the first post is a bit hard to read but the error here makes it sound like "require()" is being used to import 3d-tiles-renderer package:

```
require() of ES modules is not supported
...
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ...
```

Have you tried using "import()" as the error recommends?

> I've already developed a couple of project based on NuxtJS and additional third party packages (including ThreeJS for instance), and have never encountered this message before.
> ...
> only 3 of them include the "type: module" setting

"type: module" is relatively new (within the last couple years) and it's likely that most packages published to npm provide a "main" field UMD format file as well as a "module" field file, which is what three.js does. I've opted to use the type field to keep the complexity of maintaining a build process and multiple outputs out of the equation. 

> I'm not sure that the problem is NuxtJS specific

I'm using this package with Parcel, Webpack, and Rollup in my work and I haven't had any issues. It seems Nuxt must have different expectations than those bundlers but I don't know enough about it to know what those would be.

**Comment by ericpascual** [comment]
Thanks Garret for your support.

Agree with the error message formatting: it was the form It was displayed with :/

The "import" suggestion is maybe a general advice, since there is no "require"  in my code, nor in the dependencies mentioned (I've check this by grepping in the sources).

I've however tried the proposed "fixes" but with no result. Removing the "type: module" in your package.json led to the module not found anymore. Anyways, I didn't consider it as an option, since based on modifying third-party code.

Chances are that the problems lies in the configuration of builds and friends at the project level and that once the appropriate "magic spell" is identified, everything will works like a charm. But unfortunately I'm not skilled enough currently in this domain to find it by myself :/

**Comment by gkjohnson** [comment]
> The "import" suggestion is maybe a general advice, since there is no "require" in my code, nor in the dependencies mentioned (I've check this by grepping in the sources).

I think this is where I'd go to Nuxt if the Nuxt error recommendations aren't working. [Here's a similar stackoverflow question](https://stackoverflow.com/questions/61401475/why-is-type-module-in-package-json-file) with a reasonably popular answer suggesting to use import, as well.

> Chances are that the problems lies in the configuration of builds and friends at the project level and that once the appropriate "magic spell" is identified, everything will works like a charm.

Build process hell is definitely a problem I sympathize with. If you're already using babel then it could be possible that babel is transforming packages imports to use require before Nuxt gets to them? Just a guess.

Let me know if you get an answer through Nuxt -- I'm curious about what's going on now, too.

**Comment by ericpascual** [comment]
> I think this is where I'd go to Nuxt if the Nuxt error recommendations aren't working. Here's a similar stackoverflow question with a reasonably popular answer suggesting to use import, as well.

I'm not sure to understand what you're meaning by "I'd go to Nuxt". Asking in NuxtJS forums ?

> If you're already using babel then it could be possible that babel is transforming packages imports to use require before Nuxt gets to them? Just a guess.

This is my guess too. AFAIK Nuxt seems to use babel somewhere, since it has been installed as a transitive dependency. The problem is that I'm almost totally ignorant about its intricacies :/

> Let me know if you get an answer through Nuxt -- I'm curious about what's going on now, too.

I'll do, hoping I'll be able to find a solution quickly since this problem is putting me behind schedule for the project I've planed to use the B3DM features of your package, knowing that I've not yet started the dev of the not trivial business logic.

**Comment by gkjohnson** [comment]
> I'm not sure to understand what you're meaning by "I'd go to Nuxt". Asking in NuxtJS forums ?

Sorry, yeah I mean asking Nuxt experts. Through a forum if they have one or making an issue.

**Comment by ericpascual** [comment]
Got there but didn't find very much help in existing messages. Some are mentioning things that have been broken by recent Node versions. Not very good for the peace of mind :/

I'll try to post my question and hope it'll be more helpful.

For my curiosity's sake, since nearly all installed packages don't use the type: module clause, is there a a way to package your lib without this clause while keeping the same way to import it from client code ?

**Comment by ericpascual** [comment]
Last update : I've reworked the app by dropping NuxtJS and having the VueJS bundle served by the Python server initially devoted to the back-end. I feel better now, since I'm far more comfortable with Python than with JS, and the server framework involved here (FastAPI) is fully asynchronous and very performant, so it should not impact the application performances.

This does not solve the initial problem, but gives me hope to catch up a little the delay caused by this unforeseen event.

**Comment by gkjohnson** [comment]
> For my curiosity's sake, since nearly all installed packages don't use the type: module clause, is there a a way to package your lib without this clause while keeping the same way to import it from client code ?

As far as I know before "type: module" the common practice was to produce a CommonJS / UMD version of the package for the package.json "main" field as well as optionally an es6 module in the "module" field, which is likely how most other packages are structured. [Rollup.js](https://rollupjs.org/guide/en/) is the simplest way I know of to produce a bundled CommonJS file but would still require some custom configuration to exclude `three` and `path` packages from the build.

If I have some time later this week and the issue with the Nuxt build hasn't been resolved I can put together a temporary branch with a CommonJS build file until this is figured out.

**Comment by ericpascual** [comment]
> If I have some time later this week and the issue with the Nuxt build hasn't been resolved I can put together a temporary branch with a CommonJS build file until this is figured out.

Many thanks for taking care of this, I do appreciate your involvement.

I'll try to find the NuxtJS way to solve the problem because I don't like leaving things in the dark ;) But I confess that it will not be my priority for the days to come, since I have to catch up and removing NuxtJS from the equation with the help of FastAPI and Parcel have unlocked the situation,

**Comment by gkjohnson** [comment]
> I have to catch up and removing NuxtJS from the equation with the help of FastAPI and Parcel have unlocked the situation,

In that case it sounds like you have everything sorted. Do you still need a commonjs build for working around your issue?

**Comment by ericpascual** [comment]
> Do you still need a commonjs build for working around your issue?

This seems not critical any more on my side, but it could maybe be interesting to see if it solves the problem with the default settings of NuxtJS projects. It could also help to sort out the things to be added to NuxtJS project settings to have the current package type be properly handled. 

Anyway, you don't need to hurry. I'll stay tuned to experiment with this version when it'll be ready.

**Comment by gkjohnson** [comment]
> This seems not critical any more on my side, but it could maybe be interesting to see if it solves the problem with the default settings of NuxtJS projects.

If it's no longer needed then I'd prefer not to put time into creating the config so I can spend my free hours on other issues that need addressing. Until something points to otherwise this seems like a Nuxt configuration issue so the long term solution should be addressed on that end.

If there's some more information from Nuxt let me know and we can move forward from there.

Thanks!

**Comment by ericpascual** [comment]
That's fine for me. I'll keep you informed.
