### ISSUE TITLE
Cesium Ion Tiled not showing high res layers

### ISSUE THREAD

**Issue by cyrilpreiss** [NASA-AMMOS/3DTilesRendererJS#160]
Hi,

Trying to use this great library but i'm having issues: i'm using a 8 levels tiled model (50 M faces) but only the first two levels seems to be shown when i zoom in:

http://www.gigascope.net/3d/example/bundle/index.html

here is the tiled model uri:
http://www.gigascope.net/3d/example/data/tileset.json

thanks for your help

**Comment by gkjohnson** [comment]
Hello!

The geometric error value on the root of the model you've provided is very low (0.0439...) which means the apparent screen space error of the model is very low even when the camera gets close. Compare this to the value of 30.26... on the root of our [demo model](https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/index.html) and this is one reason the model is not loading higher resolution tiles.

Another reason is that the bounding box of the tiles does not seem to be correct relative to the tile geometry which means the error computations will not seem correct when zoom into the tile geometry:

![image](https://user-images.githubusercontent.com/734200/107913787-e3b1aa80-6f15-11eb-901c-f8dbe4a086c1.png)

Have you verified this tile set is correct? How was it generated?

**Comment by cyrilpreiss** [comment]
Thanks, i had noted that if i set a very low value for errorTarget it's working.
It has been generated in Metashape, i will check why it go wrong.
Thanks for your help

**Comment by gkjohnson** [comment]
> Thanks, i had noted that if i set a very low value for errorTarget it's working. It has been generated in Metashape, i will check why it go wrong.

It's worth noting that the geometric error value might be correct but even so the incorrect bounding box means that the screen space error value can't be computed correctly.

Feel free to open a new issue if it looks like bounding boxes are correct!

**Comment by cyrilpreiss** [comment]
Hi thanks for your help.

I have found out how to fix the coordinates, but didn't understand how to set the bounding box : is it something I have to do in metashape or in this code ? 

Can you help me ?

**Comment by gkjohnson** [comment]
> I have found out how to fix the coordinates

What do you mean by fix the coordinates?

> is it something I have to do in metashape or in this code ?

Unfortunately I am unfamiliar with Metashape so I don't have a great answer for this. It could very well be a bug in this library, though. I'm happy to work through this but my time is limited so I'll have to ask from some help in getting to the bottom of the issue. Do you mind verifying that the bounding box looks correct in Cesium? It looks like there's an option for the [Cesium3DTileset object](https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileset.html) for displaying the bounds. If it does the it's likely a bug in the TilesRenderer code.

**Comment by cyrilpreiss** [comment]
How did you do above to make the screenshot with the bounding box ?

**Comment by gkjohnson** [comment]
> How did you do above to make the screenshot with the bounding box ?

The screenshot above is from [the your demo page you linked to](http://www.gigascope.net/3d/example/bundle/index.html) and you can display the tile bounding boxes by toggling the `displayBoxBounds` option here:

![image](https://user-images.githubusercontent.com/734200/108876148-c4b8b580-75b2-11eb-825e-0c4425e8b28b.png)

For the [Cesium3DTileset](https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileset.html) it looks like there is a `debugShowBoundingVolume` option that can be enabled but I'm generally less familiar with Cesium.

**Comment by gkjohnson** [comment]
Hi @cyrilpreiss I found a possible issue that might be related to your problem but unfortunately I cannot load the tileset from your link due to CORS. Do you mind attaching the full tile set as a zip file so I can test it locally?

**Comment by gkjohnson** [comment]
@cyrilpreiss I believe I've fixed this with #166. I only downloaded the first tile level of detail and tileset to test with since I couldn't easily download the whole thing but it seems to be addressed in that case. Do you mind testing with the latest version on master to make sure it fixes the full tileset? If it looks like there's still an issue we can reopen this.

![image](https://user-images.githubusercontent.com/734200/109906667-c723ab00-7c55-11eb-8229-dd2b41323450.png)

Thanks!
