### ISSUE TITLE
Change Position of Tile Set

### ISSUE THREAD

**Issue by arsalan1248** [NASA-AMMOS/3DTilesRendererJS#162]
Hi,

1- I am trying to move the camera to the tileset object . The issue is that the the tileset object is not accessible if it is not in the view of the camera.

2- Another thing is that when I am changing the position of the tileset when it is in view and then move the 3dview a bit where the tile can not be seen. The tileset gets updated and the position has been reset to the original position. 

I have also changed the position of the children and its position is not changing.

```js
window.tilesRenderer1 = new TilesRenderer( tileset1)
tilesRenderer1.setCamera( camera1 );
tilesRenderer1.setResolutionFromRenderer( camera1, renderer1 );
scene1.add( tilesRenderer1.group );

tilesRenderer1.setResolutionFromRenderer( camera1, renderer1 );
renderer1.render( scene1, camera1 );
tilesets.push(tilesRenderer1);
renderLoop();

window.renderLoop = function() {

	requestAnimationFrame( renderLoop );

	tilesets.forEach(function(tile, index){
		tile.update();
	})
	camera1.updateMatrixWorld();
	renderer1.render( scene1, camera1 );

}
```

Thanks

**Comment by gkjohnson** [comment]
Hello!

> I am trying to move the camera to the tileset object . The issue is that the the tileset object is not accessible if it is not in the view of the camera.

Which objects are you trying to use? If you would like to move the camera so the tiles renderer is within view you can use the [getBounds](https://github.com/NASA-AMMOS/3DTilesRendererJS#getbounds) function to get whole tileset bounds and move the camera to look at that. But keep in mind that you won't get a valid bounds unless the tileset.json has finished loading.

> Another thing is that when I am changing the position of the tileset when it is in view and then move the 3dview a bit where the tile can not be seen. The tileset gets updated and the position has been reset to the original position.

How are you changing the position of the tileset?

I'm having trouble understanding how the code you posted relates to the two questions above it. Do you mind elaborating and adding code that demonstrates how you're running into the above issues?

**Comment by arsalan1248** [comment]
Thank you for the response.

The code above is to just show how the tileset is getting rendered in the view. 




> Which objects are you trying to use? If you would like to move the camera so the tiles renderer is within view you can use the [getBounds](https://github.com/NASA-AMMOS/3DTilesRendererJS#getbounds) function to get whole tileset bounds and move the camera to look at that. But keep in mind that you won't get a valid bounds unless the tileset.json has finished loadin

I have managed to look at the tileset using the getbounds() function using the below code so thanks on that.

var box = new THREE.Box3()
tilesets.getBounds(box)
box.getCenter(tilesets.position)
view.lookAt(box.getCenter(tilesets.position))



> How are you changing the position of the tileset?

I am changing the position of the tileset using tilesets.group.children[0].position. The issue is the children of the tileset keeps on changing when zooming in and zooming out so at a time I can only change the position of the tilesets which are visible at that moment and cannot change the position of the whole tileset.

**Comment by gkjohnson** [comment]
> I am changing the position of the tileset using tilesets.group.children[0].position. The issue is the children of the tileset keeps on changing when zooming in and zooming out so at a time I can only change the position of the tilesets which are visible at that moment and cannot change the position of the whole tileset.

Modifying the transforms of the children of `tilesRenderer.group` isn't valid. There are optimizations in place that require that the transformations not change and even if those were not there moving the tile geometry means the tile set hierarchy bounds may no longer encapsulate the geometry correctly meaning the tile renderer would not update correctly.

If you want to move the position of the whole tileset, though, you can modify `tilesRenderer.group.position`.

**Comment by arsalan1248** [comment]
okay. Thank you for your time
