### ISSUE TITLE
Bug: TilesRenderer.d.ts declare wrong

### ISSUE THREAD

**Issue by Aierklk** [NASA-AMMOS/3DTilesRendererJS#164]
miss onLoadTileSet function declare
forEachLoadedModel function declare is wrong

**Comment by gkjohnson** [comment]
Hello! Thanks for the report. Would you like to make a PR with the fix?

**Comment by Aierklk** [comment]
ok

**Comment by Aierklk** [comment]
> Hello! Thanks for the report. Would you like to make a PR with the fix?

ok
