### ISSUE TITLE
How to change center of rotation ?

### ISSUE THREAD

**Issue by cyrilpreiss** [NASA-AMMOS/3DTilesRendererJS#172]
Hi,

Is there a way to change the center of the model rotation ?

I have issues with my model, the rotation isn't made around it's center. Is there a way to specify the rotation center coordinate ?

http://www.gigascope.net/3d/piece.html

yours,
Cyril

**Comment by gkjohnson** [comment]
Hello @cyrilpreiss!

To me it does look like the rotation is occurring around the coin center. Can you elaborate on what you're expecting? If you'd like to find the center of the model bounds you can use the [TilesRenderer.getBounds](https://github.com/NASA-AMMOS/3DTilesRendererJS#getbounds) function to get the full bounding box and get the center from that to position the model or adjust the orbit control center. Generally you can adjust the transform of [TilesRenderer.group](https://github.com/NASA-AMMOS/3DTilesRendererJS#group) like any other three.js object.

The project and data you're working on looks really interesting, by the way. Please do share more once you're able to release it! We always appreciate seeing how our projects have been used.

**Comment by cyrilpreiss** [comment]
Hi, thanks for you quick answer.

it seems that on computer it's fine indeed. But not on my phone. Can you check it out ?

thanks for your comment about my work, don't hesitate to follow my work on linkedin: 
https://www.linkedin.com/company/30634043

I'm new to three.js, i'll have a look how i can adjist the orbit control.

**Comment by gkjohnson** [comment]
> it seems that on computer it's fine indeed. But not on my phone. Can you check it out ?

On my phone the coin rotates about the center, as well. It's important to note that the camera can be panned with two fingers on the phone which would then cause the coin to rotate off center. You can disable panning on OrbitControls, if you'd like. You can see more settings in the [three.js docs](https://threejs.org/docs/?q=orb#examples/en/controls/OrbitControls).

> thanks for your comment about my work, don't hesitate to follow my work on linkedin:
> https://www.linkedin.com/company/30634043

Thanks! I'll check it out.

**Comment by gkjohnson** [comment]
Gonna close this for now -- let me know if you have other questions about setting the position of the tile set! I'll look forward to hearing more about your finished product!
