### ISSUE TITLE
How to change initial zoom ?

### ISSUE THREAD

**Issue by cyrilpreiss** [NASA-AMMOS/3DTilesRendererJS#173]
this model is very small, it's a 18mm coin:

http://www.gigascope.net/3d/piece.html

but to make it show that big i had to make it 100x time bigger than it is, otherwise it would be very small when openning the page.

how can make it zoomed in a lot more when opening it ?

**Comment by gkjohnson** [comment]
You can adjust the initial camera position using `camera.position.set( x, y, z )` and set the position closer to the object to make it bigger. And depending on how close you want to get to the object you'll probably want to make the near camera clip value smaller, as well.

It's possible to position the camera such that a bounding box or bounding sphere is automatically fit to the screen on load, as well. But unfortunately my bandwidth is limited to general three.js questions here -- I recommend the [three.js forum](https://discourse.threejs.org/) if you have more questions about how to achieve some more automatic camera positioning.

**Comment by cyrilpreiss** [comment]
thank you for your help once again
