### ISSUE TITLE
Simplify Cesium Ion example

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#176]
Related to #341

**Comment by PetterGs** [comment]
I wrote Patrick Cozzi from Cesium on LinkedIn asking if we could get a more permanent Ion token for demonstration purposes. He never answered lol.

**Comment by gkjohnson** [comment]
Heh -- thanks for checking! I think the comment at the top of the page we have right now is good enough for testing and informing users how it should work. They consistently change their own demo API key so I expect they wouldn't want to produce a permanent public one for someone else.
