### ISSUE TITLE
How to apply texture on both side of the model ?

### ISSUE THREAD

**Issue by cyrilpreiss** [NASA-AMMOS/3DTilesRendererJS#177]
Hi,
in metashape, it's showing the texture on both side of the model, when one turn the model he can see the negative of the model.

like this:
https://i.postimg.cc/dtBxfjt2/pieceback.jpg

With 3DTilesRendererJS there is nothing on the back, is it possible to make it show the texture on the other side too ?

**Comment by gkjohnson** [comment]
If you cannot export with a double sided material you can set the materials to be double sided on load. Take a look at [Material.side](https://threejs.org/docs/?q=material#api/en/materials/Material.side) in three.js. You can set the material sidedness with the [onLoadModel](https://github.com/NASA-AMMOS/3DTilesRendererJS#onloadmodel) callback, which is demonstrated in the [custom material example](https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/customMaterial.html).

**Comment by gkjohnson** [comment]
I'm assuming my above comment addressed the issue!
