### ISSUE TITLE
Software to convert data to b3dm

### ISSUE THREAD

**Issue by duonghainbs** [NASA-AMMOS/3DTilesRendererJS#180]
Dear !

I don't know what format the data here (https://github.com/NASA-AMMOS/3DTilesRendererJS/tree/master/example/data) is converted from to b3dm. Please help me with any free software or tools to convert data. run command line as possible.

obj to b3dm
or
las to b3dm
....

Thank !

**Comment by gkjohnson** [comment]
Hello! Issue #76 discusses this a bit, as well, but generally I don't have any specific recommendations for which tools to use. Some existing software tools for data reconstruction will generate data in the 3d tiles format out of the box as far as I know and looking through the [3dtiles](https://github.com/topics/3dtiles) and [3d-tiles](https://github.com/topics/3d-tiles) tags on Github yields some options but I can't vouch for any of their capabilities or security myself as I haven't used them. For our use we have an internal tool that will generate files in the 3d tiles format but unfortunately it is not public at the moment.

**Comment by duonghainbs** [comment]
> Hello! Issue #76 discusses this a bit, as well, but generally I don't have any specific recommendations for which tools to use. Some existing software tools for data reconstruction will generate data in the 3d tiles format out of the box as far as I know and looking through the [3dtiles](https://github.com/topics/3dtiles) and [3d-tiles](https://github.com/topics/3d-tiles) tags on Github yields some options but I can't vouch for any of their capabilities or security myself as I haven't used them. For our use we have an internal tool that will generate files in the 3d tiles format but unfortunately it is not public at the moment.

When will that tool be made public? Can I try it please :D

Thank you very much !

**Comment by gkjohnson** [comment]
> When will that tool be made public?

I'm not aware of any plans to make that project public right now.

**Comment by duonghainbs** [comment]
Thank all.
