### ISSUE TITLE
Blocks outside frustum are destroyed for PNTS model

### ISSUE THREAD

**Issue by alex-lancer** [NASA-AMMOS/3DTilesRendererJS#188]
Hi! I have notised that bloks of model that are outside of frustum destroys. When you move camera to that area again thay are loading again every time. As a result, it seems that parts of the model are missing. You can see in the attached picture that only the part of model that is inside frusum is rendered.  Is there an option to keep model in memory once it was loaded?

![destroyed-box-bounds-outside-camera](https://user-images.githubusercontent.com/4189022/122851016-efbfd580-d316-11eb-9b4a-f0cb43f904d3.png)

**Comment by gkjohnson** [comment]
Hello! Yes this is intended behavior -- the TilesRenderer retains a cache of loaded tiles and will unload tile geometry once that cache has been filled to prevent too much memory from being used. You can control the behavior a bit by increasing the `errorTarget` value to prevent excessively detailed tiles from being loaded before they're close to the camera (without seeing the tileset "2" seems like a particularly low value) or adjusting the `minSize` and `maxSize` of the `TilesRenderer.lruCache` object to larger values so more tiles can be loaded before it tries to unload any. You can check out the docs and the associated fields on LRUCache [here](https://github.com/NASA-AMMOS/3DTilesRendererJS#lrucache-1).

Let me know if that helps!

**Comment by RomTreg** [comment]
Seems it works,  thank you! We will try this out
