### ISSUE TITLE
Add URL parameters support

### ISSUE THREAD

**Issue by ulenspy** [NASA-AMMOS/3DTilesRendererJS#191]
Hi there!

I have an issue with external links, containing parameters in url.
For example, my tileset refers to tile by .../001.b3dm?x=34323.454&y=54322.3301
Looks like, the viewer recognizes its extension not as "b3dm" file, but as "b3dm?x=34323.454&y=54322.3301", and doesnt support it. 

See the attached screenshot:
![image_2021_06_22T10_17_52_127Z](https://user-images.githubusercontent.com/75207723/124032450-4311e200-da01-11eb-8bdd-eadc4b4ff994.png)

Tested on tileset: https://cloud.skylineglobe.com/sg/b3dm/NeveTzedek3.420160/tileset.json

**Comment by gkjohnson** [comment]
Great thanks for the report and sample data @ulenspy! I believe the two places that rely on checking the file extension of the path are when extracting the extension to parse the tile contents [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/de17021e819a914e33de72961d45b92a7515dd2c/src/base/TilesRendererBase.js#L511) and determining if a path is an external tileset json file [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/de17021e819a914e33de72961d45b92a7515dd2c/src/base/TilesRendererBase.js#L177). I think it would be best to add a new utility function that is aware of URL parameters and can properly extract the file extension when they are present.

Feel free to submit a PR! And let me know if you have any other questions.
