### ISSUE TITLE
Support newer threejs versions

### ISSUE THREAD

**Issue by dbuck** [NASA-AMMOS/3DTilesRendererJS#196]
There's some non-trivial changes in a recent version of threejs (~125->126 I believe?) with the conversion to es modules. Issue to test it out with newer three versions.

**Comment by gkjohnson** [comment]
[r127 -> r128](https://github.com/mrdoob/three.js/wiki/Migration-Guide#127--128) might be the version you're thinking of. The examples folder (which we're only using for GLTFLoader) was all changed to use classes and changed to use a bare module specifier on npm. I don't think that should have broken anything but let me know if you find anything!

**Comment by gkjohnson** [comment]
I'm using this successfully with three.js r130 so I'll close this for now. If we see anything specific that breaks with a new release we can make new issues.

**Comment by dbuck** [comment]
I've been using 128 for some time now without any compatibility problems. The log message I saw that prompted me to post this ended up being related to something else in our webpack config - (the joy of loading a second copy of three for a couple days by accident!). Forgot to follow up.
