### ISSUE TITLE
all the same types are selected instead of specific instances

### ISSUE THREAD

**Issue by yoyomule** [NASA-AMMOS/3DTilesRendererJS#201]
Click the element, all element of the same type will be selected instead of the clicked instance. How should I solve it, thank you.
![image](https://user-images.githubusercontent.com/10000818/127261245-0d2674af-62b1-4866-ba51-1e0a7a85d1ba.png)

[042202.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/6890194/042202.zip)

**Comment by gkjohnson** [comment]
This library loads and updates the tiles associated with 3d tiles including instanced meshes but doesn't provide specific APIs for interactions. If you'd like to highlight individual instances within a single mesh you'll have to handle that within your app.

**Comment by gkjohnson** [comment]
Please close your issues if your question has been answered or you don't have any follow up questions. Just want to keep things tidy -- thanks!
