### ISSUE TITLE
Issue with camera / model getting clipped when zoomed in

### ISSUE THREAD

**Issue by cyrilpreiss** [NASA-AMMOS/3DTilesRendererJS#203]
Hi,

i'm trying to use this great library in my node/react app but i have an issue with the camera.

As you can see here:
https://gigascopejs.firebaseapp.com/TestTiles

as soon as i zoom the model gets clipped but i don't know why as i'm not very good with three.js, maybe you can help me fix this.

thanks.

**Comment by gkjohnson** [comment]
Hello! Without the debug tile visualizations and a simplified example I don't think it's possible for me to help. Can you produce a smaller stand alone example that shows how things are being set up?

**Comment by cyrilpreiss** [comment]
Hi,

i have added the debug visualization.

it seems that all my 3d tiles models are offset from the boundaries:

https://gigascopejs.firebaseapp.com/TestTiles/piece
https://gigascopejs.firebaseapp.com/TestTiles/limoges

with your 3d tiles models it's working fine:
https://gigascopejs.firebaseapp.com/TestTiles/ammos

so the issue doesn't come from your code. but maybe you can help me understand why my models have an issue.

they come from metashape directly.

**Comment by cyrilpreiss** [comment]
this is great news ! do you know wich files need to be updated ?
(i have copied some code in different files, i want to be sure i update the right part)

**Comment by gkjohnson** [comment]
The core files for the library are in `/src` but generally I don't recommend directly copying files from the project because they're prone to becoming out of date. The project should be installed via npm so it's more easily updated.

**Comment by gkjohnson** [comment]
If you're questions been answered and you have no follow up please close your issue. Just trying to keep things tidy -- thanks!

**Comment by cyrilpreiss** [comment]
thanks for your help, everything is fine now thanks to you !

**Comment by cyrilpreiss** [comment]
https://gigascopejs.firebaseapp.com/TestTiles/lorin

(still work in progress)
