### ISSUE TITLE
can't load texture

### ISSUE THREAD

**Issue by QianWu184** [NASA-AMMOS/3DTilesRendererJS#219]
I load a model(download from other issues) but there is no any texture.  The console error is
![86D1F26D-0B52-4077-ACC5-6084E9BCF8DC](https://user-images.githubusercontent.com/26835387/140887599-4f62e27a-38d1-41bf-9332-bff564d46128.png)

and the model is like
![D8A4C3C7-FF8B-4e17-A42B-546E5A1CCFD4](https://user-images.githubusercontent.com/26835387/140887604-1f1fe479-a012-4c2a-bd2b-85fd573bf633.png)
But it work fine in cesium. 
Here is the model
[bim3dtile2.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/7503091/bim3dtile2.zip)
Is there anything i can do to solve it?

**Comment by gkjohnson** [comment]
Hello! It looks like the files you provided are using and image/crn format which seems to be from [crunch](https://github.com/BinomialLLC/crunch) but it's not supported by three.js' GLTFLoader. For that I recommend making an issue asking for support or at least a better error in the [official three.js project](https://github.com/mrdoob/three.js) or using another supported compressed image format like KTX2 or DDS.

You can see the mimetype of the images if you look in the ascii content of the file. It may be helpful to separate the GLTF contents from the B3DM file so it can be more easily inspected and validated by the three.js maintainers.

**Comment by QianWu184** [comment]
> Hello! It looks like the files you provided are using and image/crn format which seems to be from [crunch](https://github.com/BinomialLLC/crunch) but it's not supported by three.js' GLTFLoader. For that I recommend making an issue asking for support or at least a better error in the [official three.js project](https://github.com/mrdoob/three.js) or using another supported compressed image format like KTX2 or DDS.
> 
> You can see the mimetype of the images if you look in the ascii content of the file. It may be helpful to separate the GLTF contents from the B3DM file so it can be more easily inspected and validated by the three.js maintainers.

Thanks reply.I'll try this
