### ISSUE TITLE
 Why can't some 3DTiles be loaded

### ISSUE THREAD

**Issue by 2226174644** [NASA-AMMOS/3DTilesRendererJS#231]
I tried to load a classic example 3DTiles --**TilesetWithDiscreteLOD** ,but there was nothing in the scene and didn't log any error.
The code just like
![image](https://user-images.githubusercontent.com/51537408/144183803-327b6ec4-0000-40a1-865f-8954b6d750e2.png)
With logging the TilesRenderer , its children in the group has nothing.
![image](https://user-images.githubusercontent.com/51537408/144184827-48582a14-6e6e-4640-a47a-2fc317926992.png)
Here is the 3DTiles :
[TilesetWithDiscreteLOD.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/7631386/TilesetWithDiscreteLOD.zip)
(This 3DTiles can be loaded in Cesium , and I tried to load its b3dms alone using your B3DMLoader,it can be shown in the scene.) 
I also tried to load your example 3DTiles ( [https://github.com/NASA-AMMOS/3DTilesRendererJS/tree/master/example/data](url) ) . It can be loaded successfully.Why?

**Comment by gkjohnson** [comment]
Please take a look at your server setup. Like #229 I suspect your server configuration is not returning 404s and your url is incorrect. Loading the "TilesetWithDiscreteLOD" tile set from the cesium sample files works fine for me:

https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/index.html#https://raw.githubusercontent.com/CesiumGS/3d-tiles-samples/main/1.0/TilesetWithDiscreteLOD/tileset.json

**Comment by 2226174644** [comment]
Well,I copy your example code and test it using the same url ,it can be loaded!
![image](https://user-images.githubusercontent.com/51537408/144209228-7dca1a76-d7c6-468f-ab42-f1e71ecea0bf.png)
I still don't know why.
But all in all, thank you.

**Comment by gkjohnson** [comment]
> Well,I copy your example code and test it using the same url ,it can be loaded!
> I still don't know why.

Like I said this sounds like it's related to your server setup. It sounds to me like the URL you were passing in did not exist and for some reason the server was not returning a 404. Unfortunately without more information that's the best I can provide.
