### ISSUE TITLE
How can I use matrix instead of quaternion?

### ISSUE THREAD

**Issue by ZhangGuangXin** [NASA-AMMOS/3DTilesRendererJS#237]
Excuse me, I am sorry to bother you. I confused for using quaternion in ionExample. I don't know quaternion, I want to use matrix to rotate the objects in my project. How should I get rotation axis and rotation angle, if I use matrix.

function rotationBetweenDirections( dir1, dir2 ) {
	const rotation = new Quaternion();
	const a = new Vector3().crossVectors( dir1, dir2 );
	rotation.x = a.x;
	rotation.y = a.y;
	rotation.z = a.z;
	rotation.w = 1 + dir1.clone().dot( dir2 );
	rotation.normalize();

	return rotation;
}
How can I use matrix instead of  quaternion?

**Comment by ZhangGuangXin** [comment]
Actually, I want to convert mesh from Ellipsoid coord to a plane coord, but I don't know the theory in ionExample, can you explain it?

**Comment by gkjohnson** [comment]
> How can I use matrix instead of quaternion?

You can convert a quaternion to a matrix using this function from the docs:

https://threejs.org/docs/?q=matr#api/en/math/Matrix4.makeRotationFromQuaternion

> I don't know the theory in ionExample, can you explain it?

The local "up" vector for the tileset is assumed to be the same as the normalized position vector which is a roughly based on the assumption that the tileset lies on the surface of a sphere (though in reality it's an ellipsoid so it's not perfect). We rotate the tile set so the "up" direction is consistent with world.

These lines derive the rotation:

https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/6c5829111af481e3b7d2bcb0cdb0836cb4e108db/example/ionExample.js#L198-L200
