### ISSUE TITLE
fatal error in your example(Basic TilesRenderer)

### ISSUE THREAD

**Issue by dandiago** [NASA-AMMOS/3DTilesRendererJS#241]
Basic TilesRenderer
Setting up a basic application with a 3D Tile Set.

import { TilesRenderer } from '3d-tiles-renderer';

// ... initialize three scene ...

const tilesRenderer = new TilesRenderer( './path/to/tileset.json' );
tilesRenderer.setCamera( camera );
tilesRenderer.setResolutionFromRenderer( camera, renderer );
scene.add( tilesRenderer.group );

renderLoop();

function renderLoop() {

	requestAnimationFrame( renderLoop );

	// The camera matrix is expected to be up to date
	// before calling tilesRenderer.update
	camera.updateMatrixWorld();
	tilesRenderer.update();
	renderer.render( camera, scene );

}

renderer.render( camera, scene );  this is wrong.you reverse the order of 'camera' and 'scene'.

**Comment by gkjohnson** [comment]
Thanks! I just updated the docs.
