### ISSUE TITLE
KHR_materials_unlit

### ISSUE THREAD

**Issue by dmercel3DUN** [NASA-AMMOS/3DTilesRendererJS#242]
Several programs that create 3DTiles are using Draco Compression and particular materials such as KHR_materials_unlit.  Is there any plan to implement reading this material type or do you have any adivce for how to implement it?  Thanks.

**Comment by dbuck** [comment]
See [examples/gltf.js](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/gltf.js#L95)

You can create and use a GLTFLoader configured however you need it to be by setting it as the loader for specific filetypes in the loading manager, ex, to support draco + basis set it up like this:

```js
  const threeRenderer = ... // THREE.WebGLRenderer
  const manager = tilesRenderer.manager;
  
  // support draco
  const dracoLoader = new DRACOLoader();
  dracoLoader.setDecoderPath(`......`);

  // and ktx2/basis
  const ktx2Loader = new KTX2Loader();
  ktx2Loader.setTranscoderPath(`......`);
  ktx2Loader.detectSupport(threeRenderer);
  ktx2Loader.manager = loadingManager;
  
  // set gltf loader to use same manager as the tiles renderer
  const gltfLoader = new GLTFLoader(loadingManager);

  // apply loaders
  loader.setDRACOLoader(dracoLoader);
  loader.setKTX2Loader(ktx2Loader);

  // use the custom gltf loader for the filetypes, rather than creating a new default gltfloader per call
  manager.addHandler(/\gltf$/, gltfLoader);
  manager.addHandler(/\glb$/, gltfLoader);
```

**Comment by gkjohnson** [comment]
I'll close the issue until it can be demonstrated that something needs to be fixed in this repo, then
