### ISSUE TITLE
loaded 3dtiles of CesiumLab failed

### ISSUE THREAD

**Issue by GunOmniscience** [NASA-AMMOS/3DTilesRendererJS#249]
I used CesiumLab transform 3dtiles and used 3DtilesRendererJS loaded that, But just request tileset.json, Other .b3dm files not send request.

**Comment by GunOmniscience** [comment]
https://www.cesiumlab.com/

**Comment by gkjohnson** [comment]
You'll have to provide a bit more information and a demo of the issue. I'm unfamiliar with cesium lab.
