### ISSUE TITLE
texture load error: unknown extension "KHR_techniques_webgl"

### ISSUE THREAD

**Issue by augusttty** [NASA-AMMOS/3DTilesRendererJS#250]
![img](https://anomanm-1255452493.cos.ap-shenzhen-fsi.myqcloud.com/assets/img/20220403200638.png)

Using three.js v139

The geometry is rendered properly,but the texture didn't:

![img](https://anomanm-1255452493.cos.ap-shenzhen-fsi.myqcloud.com/assets/img/20220403201135.png)

I found the discussion in three.js issues, but  they are not intend to support this feature now ,because it is now a draft which is not been released. Is there any way to handle this issue? thanks.

**Comment by gkjohnson** [comment]
You'd have the implement the extension yourself if three.js is not intending to support it. From the glTF spec document it sounds like the extension is no longer recommended, anyway:

**Comment by gkjohnson** [comment]
You'd have the implement the extension yourself if three.js is not intending to support it. From the glTF spec document it sounds like the extension is no longer recommended, anyway:

https://github.com/KhronosGroup/glTF/tree/main/extensions#archived-extensions-for-gltf-20

It's probably best if you don't use it in your geometry.

**Comment by augusttty** [comment]
@gkjohnson Thanks.I re-exported the 3dtiles by **CesiumLab** (osgb->b3dm),and it works perfectly! I was using **3dtiles.exe** before.
