### ISSUE TITLE
Tile can't show

### ISSUE THREAD

**Issue by jinjun1994** [NASA-AMMOS/3DTilesRendererJS#251]
https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/3a3e1b97276767538c226e6d3ba2a30be371d142/src/three/TilesRenderer.js#L907

error = tile.geometricError / ( scaledDistance * sseDenominator )

if  scaledDistance  = 0 , error = Infinity

**Comment by jinjun1994** [comment]
https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/1971c982725befaff10d6c5a8c6efb3ba5644c43/src/three/TilesRenderer.js#L396

projection[ 15 ] === 1 
but in mapbox-gl  projection[ 15 ] !== 1
https://github.com/mapbox/mapbox-gl-js/blob/954c2a014925f61058f993e328c80c366ea69473/debug/threejs.html#L76

**Comment by gkjohnson** [comment]
Tbh I think this is an issue with mapbox-gl-js -- they should not be applying a translation or scale matrix to the frustum. It's no longer really just a projection matrix in that case. If you'd like to apply scale and translation it should be applied to the cameras `matrixWorld`. There are also redundant / unnecessary lines in that function so I have to feel like it should be reevaluated. Do you know why they're handling their camera updates that way?
