### ISSUE TITLE
PNTSLoader and Draco compression

### ISSUE THREAD

**Issue by phoenixbf** [NASA-AMMOS/3DTilesRendererJS#252]
Hi all,
after a few tests it seems like pointclouds tilesets do not work if pnts are draco-compressed. This can be replicated through Cesium ion (generating pointclouds with or without draco compression)

Is there an option/flag to set for for PNTSLoader to decode Draco pnts like what is already happening on b3dm?
Or eventually a way to attach a decoder?

**Comment by gkjohnson** [comment]
Hey! Looks like draco support for point clouds is a relatively new extension. Here's the page on the information:

https://github.com/CesiumGS/3d-tiles/tree/main/specification/TileFormats/PointCloud#extensions

If you'd like to make a PR to support the extension I'm happy to make a new release!

**Comment by phoenixbf** [comment]
:thumbsup: I'll have a look into that!

**Comment by segments-tobias** [comment]
Seems like this can be closed? [https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/329](https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/329)
