### ISSUE TITLE
Remove RTC_CENTER warning

### ISSUE THREAD

**Issue by segments-tobias** [NASA-AMMOS/3DTilesRendererJS#261]
`RTC_CENTER` support for pnts files was seemingly fixed (see issue #182), however warnings still appear, since `RTC_CENTER` is still listed here: [https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/3e3bbeb9a60c1d4e03207756edce33f872307df7/src/three/PNTSLoader.js#L26](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/3e3bbeb9a60c1d4e03207756edce33f872307df7/src/three/PNTSLoader.js#L26)

Is this intentional?

**Comment by gkjohnson** [comment]
Nope! Want to make a PR to remove the warning?
