### ISSUE TITLE
How to run View example

### ISSUE THREAD

**Issue by WaterSeeding** [NASA-AMMOS/3DTilesRendererJS#266]
How to run View example

I want to run the project locally to view the relevant examples, but I NPM run start and report the following questions. How can I do this?
![1](https://user-images.githubusercontent.com/31184164/176165443-006a6f18-83ae-4f1c-bc9b-7ef751ad5325.jpg)
![2](https://user-images.githubusercontent.com/31184164/176165463-f4af4bae-1a93-4627-9763-b34e868a7f16.jpg)
![3](https://user-images.githubusercontent.com/31184164/176165471-eeef7dfd-d570-40e3-ae57-1ba9c8cb74fd.jpg)

**Comment by gkjohnson** [comment]
When running the examples they are built into the `example/dev-bundle` directory so you can visit the following url:

```
http://localhost:9080/example/bundle/b3dmExample.html
```

**Comment by familyaa** [comment]
Note that threejs needs to install version `0.128`, because the test found that installing version `0.141` will lack `dat.gui.module.js`, which will prevent the example from starting.

**Comment by WaterSeeding** [comment]
> When running the examples they are built into the `example/dev-bundle` directory so you can visit the following url:
> 
> ```
> http://localhost:9080/example/bundle/b3dmExample.html
> ```

Thank you very much. Now I can see the examples

![4](https://user-images.githubusercontent.com/31184164/176341490-bfa03a32-99d2-4e4f-9fcb-51e103bd956f.jpg)

**Comment by WaterSeeding** [comment]
> Note that threejs needs to install version `0.128`, because the test found that installing version `0.141` will lack `dat.gui.module.js`, which will prevent the example from starting.

Thank you. I also noticed this problem. I have set the version of three to 0.134.0 to avoid this error.

**Comment by gkjohnson** [comment]
Feel free to submit a PR that pulls in `dat.gui` as a node module or updates the examples to use `lil-gui` from three.js!

**Comment by WaterSeeding** [comment]
> Feel free to submit a PR that pulls in `dat.gui` as a node module or updates the examples to use `lil-gui` from three.js!

Hello, when I run index HTML example, the URL is found to be invalid. What is the problem? I didn't modify anything in the data.

![image](https://user-images.githubusercontent.com/31184164/176373675-bb9a2851-f20c-4fbc-8b1e-4ec1f4d98f80.png)

**Comment by JupiterStep** [comment]
I can change the URL so that it works
![image](https://user-images.githubusercontent.com/55522153/177235416-3650a1e6-cbb2-4bea-9394-2d25e026cfc4.png)
