### ISSUE TITLE
How to support shadows,texture and light in B3dmExample.js

### ISSUE THREAD

**Issue by JupiterStep** [NASA-AMMOS/3DTilesRendererJS#274]
The color changing function of the model has been realized by ShaderMaterial. How to support shadows,texture and light in B3dmExample.js

**Comment by gkjohnson** [comment]
Related to #265 - it's possible to extend existing materials using the [onBeforeCompile](https://threejs.org/docs/?q=mater#api/en/materials/Material.onBeforeCompile) function. For more help on more general three.js questions like this I recommend asking at the forum:

https://discourse.threejs.org/

**Comment by gkjohnson** [comment]
q
