### ISSUE TITLE
Render disorder after version 0.3.10

### ISSUE THREAD

**Issue by Junior2Ran** [NASA-AMMOS/3DTilesRendererJS#275]
I noticed that on [CHANGELOG](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/CHANGELOG.md#0310---2022-07-02) `Fix the application of the tile "up" axis adjustments.`

Before this fix, the render output is correct. However, afther this version, the render output turns out to be a mass and disorder. How would this happen?

**Comment by gkjohnson** [comment]
@Junior2Ran it's possible there was an issue in the updated implementation. Can you provide images of before / after and example data to reproduce the issue?

The updates were made in #260, and the original issue was #184

**Comment by Junior2Ran** [comment]
Actually, I'm not sure that the problem is caused by this `axis fix`. 

However, with version 0.3.9 it seems like
![image](https://user-images.githubusercontent.com/19679189/179647531-1ba69ea4-7729-46e2-8b1f-8d3603d8be18.png)

wiith version 0.3.10 it turns out to be a mass, full of unexpected coordinates disorder, z-fighting, LOD disorder
![image](https://user-images.githubusercontent.com/19679189/179647903-7dac5e1c-ef58-4624-9189-55b225e0bb7b.png)

You are the professional guy, I assume that you can find a clue to solve the problem. And I'm glad to provid some wild guess

**Comment by gkjohnson** [comment]
> You are the professional guy, I assume that you can find a clue to solve the problem. And I'm glad to provid some wild guess

Unfortunately I don't have the bandwidth to find and solve everyones issues for them. I'll need your help to track down the PR / commit that broke your dataset and then we can talk about how to address it and where the regression came from - if those are buildings are all instanced from an `i3dm` file then it is possible that it was broken in #260 but I can't be sure.

**Comment by Junior2Ran** [comment]
The buildings are from `b3dm` files, and the upAxis is `z`. 
I've reviewed #260 ,  it seems likely to be caused by this PR. 
I will take some time to debug the code and find out the reason later.

**Comment by gkjohnson** [comment]
@Junior2Ran - are you able to provide a sample data set? It would be nice to get to the bottom of this

**Comment by gkjohnson** [comment]
@Junior2Ran I'm going to assume that this was actually fixed in #273 and released in v0.3.12. In the future it's helpful to provide test data so the issues can be tested and confirmed.

Thanks!
