### ISSUE TITLE
 How to select multiple models

### ISSUE THREAD

**Issue by JupiterStep** [NASA-AMMOS/3DTilesRendererJS#276]
The geometry of a mesh contains multiple small models

How can I select several small models

Like this example

https://threejs.org/examples/?q=sele#misc_boxselection

**Comment by gkjohnson** [comment]
If you'd like to use some kind of lasso or box selection you'll have to make your own implementation with the b3dm and i3dm batchtable ids in mind.

**Comment by JupiterStep** [comment]
In the b3dmExample.js example, I want to know how I can make the model change color if there are tens of thousands of 'highlightedBatchId'. If the passed array is in uniform, the array length of unforms is limited

**Comment by JupiterStep** [comment]
@gkjohnson 
Please give guidance and suggestions

**Comment by gkjohnson** [comment]
If you want to support highlighting multiple objects at once with the batch table / batch id concept I'd use something like a data texture with pixels for every batch id. Then a value can be assigned for the color of the mesh associated with the pixel for the given batch id for the sake of highlighting. This would require more custom shader logic.
