### ISSUE TITLE
 how to optimize performance when 3dtiles data is very mass

### ISSUE THREAD

**Issue by ZhangGuangXin** [NASA-AMMOS/3DTilesRendererJS#277]
Hello，I meet a headache problem, I load 3dtiles data that is excess 50G.  When I drag the map by mouse, the map will gradually slow down until it crashes. for performance, I set the following code:

              this.tilesRenderer.downloadQueue.maxJobs = 32;
              this.tilesRenderer.parseQueue.maxJobs = 32;
              this.tilesRenderer.lruCache.unloadPercent = 0.1;
              this.tilesRenderer.lruCache.unloadPriorityCallback = function (item) {
                  self.tilesRenderer.lruCache.remove(item);
              }

but the above code can't  solve the performance problem, the map will still crash. I wonder what should I do to optimize.

**Comment by gkjohnson** [comment]
Does the tileset work in Cesium? Without a sample of the data or information about why it's crashing it's not very possible to provide much insight.

**Comment by gkjohnson** [comment]
Closing for now. If you can provide more insight I'm happy to reopen and discuss!
