### ISSUE TITLE
Question: No self shadowing rendered

### ISSUE THREAD

**Issue by WaterSeeding** [NASA-AMMOS/3DTilesRendererJS#278]
I loaded cesium 3D tiles through 3dfilesrendererjs, and set the material to receive and generate shadows. I saw that 3D tiles produced shadows, but it had no way to receive shadows, and did not display shadows on its surface.
![5](https://user-images.githubusercontent.com/31184164/181228863-026d3e9d-ea21-4275-920c-d9a5e5c33fde.png)
![6](https://user-images.githubusercontent.com/31184164/181228984-5d81595d-00cc-4bd7-bc96-9ca9ca3a01e1.png)
![7](https://user-images.githubusercontent.com/31184164/181229009-0fb0ac9f-521a-48e6-9453-49d299589b96.png)

**Comment by gkjohnson** [comment]
You'll need to provide more information if you want help. I can't provide any insight without a code snippet or some example.

**Comment by JupiterStep** [comment]
I think you may be using a directional light, and the range of shadows produced by the directional light can be set. I think you can check if the model is in scope.
//Set up shadow properties for the light
light.shadow.mapSize.width = 512; // default
light.shadow.mapSize.height = 512; // default
light.shadow.camera.near = 0.5; // default
light.shadow.camera.far = 500; // default

**Comment by WaterSeeding** [comment]
> You'll need to provide more information if you want help. I can't provide any insight without a code snippet or some example.

Thank you. I saw the problem in this issue later. This is the model problem I used

https://github.com/mrdoob/three.js/issues/21483

**Comment by gkjohnson** [comment]
It looks like shadows are casting but the quality is low or cast region too big. I recommend asking general shadow questions at the forum or on the three.js discord:

https://discourse.threejs.org/
