### ISSUE TITLE
Why not re network request tiles

### ISSUE THREAD

**Issue by JupiterStep** [NASA-AMMOS/3DTilesRendererJS#279]
The model is not in the camera range until it is returned to the camera range, and the tiles will not be loaded again by the network request.

**Comment by JupiterStep** [comment]
How to download again instead of using cache

**Comment by gkjohnson** [comment]
Can you explain your use case? The cache is in place to enable turning the camera so tiles that will frequently be cycled in and out of view are available when needed. Tiles that are not needed are evicted from the cache when too many tiles have been downloaded.

**Comment by JupiterStep** [comment]
I need to load a total of 20GB files, but half of them cannot be fully displayed
code:
 tiles1 = new TilesRenderer('city1/tileset.json');  // every file size: 2GB
 tiles2 = new TilesRenderer('city2/tileset.json');
 tiles3 = new TilesRenderer('city3/tileset.json');
 tiles4 = new TilesRenderer('city4/tileset.json');
 tiles5 = new TilesRenderer('city5/tileset.json');
 ...
render() { 
   camera.updateMatrixWorld();
   moveToCenter(); // update all tiles center 
   tiles1.update();
   tiles2.update();
   ...
}
@gkjohnson

**Comment by gkjohnson** [comment]
Unfortunately this isn't enough information to help. If an individual file you're loading is 2.0GB then they won't fit in memory.

If not enough tiles are downloading then you may need to adjust the lru cache min and max size fields:

https://github.com/NASA-AMMOS/3DTilesRendererJS#maxsize

**Comment by gkjohnson** [comment]
Closing this for now - if you can provide more information on what's happening or a demo of the issue then we can reopen the issue!

**Comment by JupiterStep** [comment]
I think my problem is how to load the big size model performance optimization，Game scenes often require many models，I'm going to optimize from building model
