### ISSUE TITLE
PNTSLoader Compatibility issues

### ISSUE THREAD

**Issue by haojay5** [NASA-AMMOS/3DTilesRendererJS#280]
I have a set of PNTS format data， When I loaded it, I reported an error，cesium load it is normal，the tile metadata has no POINTS_LENGTH attribute is under the header，This set of data is converted through cesium lab
![image](https://user-images.githubusercontent.com/18531492/185919565-5f7d78e8-fa53-4054-9a1f-90d65ffe2375.png)
![image](https://user-images.githubusercontent.com/18531492/185920150-10acfca9-094f-4c4a-9f31-f6b34671adc3.png)

**Comment by gkjohnson** [comment]
> the tile metadata has no POINTS_LENGTH attribute is under the header

Your screenshot shows that `POINTS_LENGTH` is present in the file. However it looks like `POSITION_QUANTIZED` is used which you can see from the code is not currently supported.

Would you like to make a PR to add support for quantized positions? You can see documentation here: https://github.com/CesiumGS/3d-tiles/blob/main/specification/TileFormats/PointCloud/README.md#quantized-positions
