### ISSUE TITLE
please add CESIUM_RTC extension support

### ISSUE THREAD

**Issue by peiyu7921** [NASA-AMMOS/3DTilesRendererJS#281]
some tiles has CESIUM_RTC extension,but it is not support now

**Comment by gkjohnson** [comment]
If you'd like to create the extension for feel free to make a PR. I'm happy to provide any guidance you might need to contribute! The GLTFLoader in three.js has a robust extension system or it can be added into the existing [GLTFExtensionLoader](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/three/GLTFExtensionLoader.js).

Here is the specification for the extension:

https://github.com/KhronosGroup/glTF/blob/main/extensions/1.0/Vendor/CESIUM_RTC/README.md

And you can see how the RTC transform is applied to B3DM files here:

https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/beb322aae5fd99e773e3ec90711629d212a5b7fa/src/three/B3DMLoader.js#L58-L65

**Comment by peiyu7921** [comment]
> If you'd like to create the extension for feel free to make a PR. I'm happy to provide any guidance you might need to contribute! The GLTFLoader in three.js has a robust extension system or it can be added into the existing [GLTFExtensionLoader](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/three/GLTFExtensionLoader.js).
> 
> Here is the specification for the extension:
> 
> https://github.com/KhronosGroup/glTF/blob/main/extensions/1.0/Vendor/CESIUM_RTC/README.md
> 
> And you can see how the RTC transform is applied to B3DM files here:
> 
> https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/beb322aae5fd99e773e3ec90711629d212a5b7fa/src/three/B3DMLoader.js#L58-L65

which step  should i do this?

**Comment by gkjohnson** [comment]
I have provided you two places to start - it's up to you. You can implement this as a GLTFLoader extension or within the GLTFExtensionLoader in this project.

**Comment by peiyu7921** [comment]
#282 please check this pr
