### ISSUE TITLE
ThreeTilesRenderer : Region bounds not supported.

### ISSUE THREAD

**Issue by kingwangwang** [NASA-AMMOS/3DTilesRendererJS#283]
**Why does loading the simplest model cause such errors? How can I solve them?**
[1.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/9580007/1.zip)
------------------------------------------------------------------------------------------
![2022-09-16_093201](https://user-images.githubusercontent.com/61161658/190539338-01ff926a-5f5e-4acb-8bc3-eff5e3ae03a0.png)
![2022-09-16_094040](https://user-images.githubusercontent.com/61161658/190539341-95aae20e-cf73-4871-ac29-0fc6282270d9.png)

**Comment by gkjohnson** [comment]
Hi @kingwangwang! Currently the loader does not support the `region` type bounding volume. Issue #66 is the outstanding ticket for this feature and outlines how this could be implemented in the loader using bounding spheres or bounding boxes in lieu of a more sophisticated region volume implementation.

This is a long requested feature and it would be great to have it added to the project and unfortunately I don't have the bandwidth to work on it. Are you interested in helping to add the feature to the project? I can provide guidance and advice along the way and it would be a much appreciated addition.

**Comment by kingwangwang** [comment]
您好！您的邮件已收到。我将在假期结束后，尽快给你回复。
祝您生活愉快。
BY WJC

**Comment by kingwangwang** [comment]
> Hi @kingwangwang! Currently the loader does not support the `region` type bounding volume. Issue #66 is the outstanding ticket for this feature and outlines how this could be implemented in the loader using bounding spheres or bounding boxes in lieu of a more sophisticated region volume implementation.
> 
> This is a long requested feature and it would be great to have it added to the project and unfortunately I don't have the bandwidth to work on it. Are you interested in helping to add the feature to the project? I can provide guidance and advice along the way and it would be a much appreciated addition.

@gkjohnson thanks ,I will try.
