### ISSUE TITLE
On index.js file have a code bug

### ISSUE THREAD

**Issue by callmegaga** [NASA-AMMOS/3DTilesRendererJS#292]
At tag 0.3.13

on file `r/src/index.js`
with code `export { Ellipsoid, WGS84_RADIUS, WGS84_HEIGHT } from './three/math/Ellipsoid.js';` 

but the file `Ellipsoid.js`, do not export `WGS84_RADIUS` and `WGS84_HEIGHT`

so it cause bug

**Comment by gkjohnson** [comment]
Thanks! fixed in v0.3.14
