### ISSUE TITLE
Region Bounding Volume example data does not load

### ISSUE THREAD

**Issue by lukem-vaarst** [NASA-AMMOS/3DTilesRendererJS#293]
Hello, thanks for the excellent 3D Tiles renderer. I'm trying out the new support for Region bounding volumes using the Basic TilesRenderer snippet from the `README` and the example data linked from PR #66, but TilesRenderer doesn't seem to load anything except `tileset.json`. Running the same code but switching the TilesRenderer to point to the Dingo Gap Mars dataset works fine:
```
import { TilesRenderer } from '3d-tiles-renderer';

// ... initialize three scene ...

// PR 66 example tileset with Region Bounding Volume only loads tileset.json
const tilesRenderer = new TilesRenderer( 'https://raw.githubusercontent.com/CesiumGS/3d-tiles-samples/main/1.0/TilesetWithRequestVolume/tileset.json' );

// Mars Dingo Gap tileset loads fine using same code
// const tilesRenderer = new TilesRenderer( 'https://raw.githubusercontent.com/NASA-AMMOS/3DTilesSampleData/master/msl-dingo-gap/0528_0260184_to_s64o256_colorize/0528_0260184_to_s64o256_colorize/0528_0260184_to_s64o256_colorize_tileset.json' );

tilesRenderer.setCamera( camera );
tilesRenderer.setResolutionFromRenderer( camera, renderer );
scene.add( tilesRenderer.group );

renderLoop();

function renderLoop() {

	requestAnimationFrame( renderLoop );

	// The camera matrix is expected to be up to date
	// before calling tilesRenderer.update
	camera.updateMatrixWorld();
	tilesRenderer.update();
	renderer.render( scene, camera );

}
```
Is something additional required to load the tileset containing the Region?

**Comment by gkjohnson** [comment]
Tilesets with regions are often positioned extremely far from the origin on the surface of the earth - ie a distance of the earths radius from the origin. You'll have to center the tileset near the camera if you're expecting to see it at the origin:

https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/6664b51c4027c621372f1dc99487cc421a785583/example/index.js#L527-L538

**Comment by lukem-vaarst** [comment]
Thanks for the tip, that is now loading great.
