### ISSUE TITLE
How to create tileset.json? --help

### ISSUE THREAD

**Issue by MeRahulAhire** [NASA-AMMOS/3DTilesRendererJS#294]
Hi, I'm new to the world of 3d tiles and currently I know how to make custom XYZ leaflet tiles. I want to know that how can I make `tileset.json`? Do I need a glb format rendered out of blender or [will this help](https://github.com/dreamergz/gltf-to-3d-tiles)? 

I'm trying to make 3d  of Nasa's map with displacement map to render it exactly like google earth which has dynamic tiles which is also what your demo shows.

**Comment by gkjohnson** [comment]
We've only used internal implementations of a 3d tiles generation pipeline so unfortunately I cannot provide any recommendations for external prcesses.

**Comment by MeRahulAhire** [comment]
Can you let me know how its been done?

**Comment by gkjohnson** [comment]
There's not - it's a complicated series of algorithms and pipelines and there's nothing public on our process I can share.

**Comment by MeRahulAhire** [comment]
Do you know any other open tool that can help me achieve it?

**Comment by gkjohnson** [comment]
I haven't used any of them but if you look under the [3dtiles](https://github.com/topics/3dtiles) and the [3d-tiles](https://github.com/topics/3d-tiles) tags on Github you may be able to find something. There is also the [Cesium Ion](https://cesium.com/platform/cesium-ion/) service.

**Comment by MeRahulAhire** [comment]
Thanks for the suggestion, I'll have a look at them.
