### ISSUE TITLE
how to load the better level of tile when reach the limit of LRU cache

### ISSUE THREAD

**Issue by wemamawe** [NASA-AMMOS/3DTilesRendererJS#296]
Background:
 i have a project, it was sliced many leaf tile about 3500 leafs at the first level. so if i set the maxSize value of LRUCache to 2000, the result look like strange，not right。
i tried to change the parameters，can‘t find a good result。

**Comment by gkjohnson** [comment]
Without any more information I cannot help. Please provide a repro case and screenshots.
