### ISSUE TITLE
TilesRenderer.d.ts contains the wrong method names

### ISSUE THREAD

**Issue by jesse-small** [NASA-AMMOS/3DTilesRendererJS#298]
**Describe the bug**

The TilesRenderer.d.ts lists the function _getBoundsTransform_ but if you look at TilesRenderer.js there is no matching function, instead, it contains _getOrientedBounds_ which returns both the box and matrix. I would like to use _getOrientedBounds_ but it is not exposed correctly through the type definition file. It looks like the type definition file has not been updated in a while.

**Expected behavior**

The type definition file for TilesRenderer should match the available APIs in the javascript file.

**Platform:**

 - Library version: [v0.3.14]

**Comment by gkjohnson** [comment]
Thanks for the catch? Can you make a PR with the fix?

**Comment by jesse-small** [comment]
Yeah, more than happy to! I'll try to push up a PR later today, appreciate the quick reply.

**Comment by jesse-small** [comment]
@gkjohnson I have created the PR, please see https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/299.
