### ISSUE TITLE
CESIUM_RTC not supported with B3DMLoader

### ISSUE THREAD

**Issue by jesse-small** [NASA-AMMOS/3DTilesRendererJS#300]
**Describe the bug**

When I try to load a tile with the CESIUM_RTC extension through the B3DMLoader, I get the following error "THREE.GLTFLoader: Unknown extension CESIUM_RTC". I see that the GLTFExtensionLoader supports CESIUM_RTC however the B3DMLoader does not use the GLTFExtensionLoader it just uses the GLTFLoader provided by the manager. Is there any way to use the GLTFExtensionLoader with the B3DMLoader?

**Expected behavior**

We should be able to use the GLTFExtensionLoader so that we can register the extensions to the GLTFLoader before it is used by the B3DMLoader.

**Comment by jesse-small** [comment]
After playing around a bit I found a solution that would work.
Being able to register the cesium extension to the GLTF loader. There is also a change to the cesium extension that is required so that tiles that do not require the cesium extension do not error. 

So the code changes required are:
1) export the cesium extension so it can be registered manually by the GLTF loader
2) modify the cesium extensions so that it does not error our for tiles that do not require it

Please let me know if there is a better approach I am missing, otherwise I am more than happy to push up a PR with these changes.

**Comment by jesse-small** [comment]
@gkjohnson 
I have created a PR to resolve this issue.
It allows us to manually register the cesium extension when needed by exporting it for use.
https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/301

**Comment by gkjohnson** [comment]
Closed with #301
