### ISSUE TITLE
If "refine" is "ADD", is it impossible to click to select a sub model

### ISSUE THREAD

**Issue by kingwangwang** [NASA-AMMOS/3DTilesRendererJS#302]
My model is a BIM model. When the model is loaded in the 'ADD' mode, the mouse ray detection cannot detect the sub model, so many functions cannot be further developed. Is it because of BVH?

Loading the 'tileset add. json' model in your case also has this problem, as shown in the figure

![111111111](https://user-images.githubusercontent.com/61161658/199875190-e0603b12-f248-4c0b-95c4-a1a7092abbb5.png)

**Comment by gkjohnson** [comment]
Hello! Does the issue still occur if `TilesRenderer.optimizeRaycast` is set to `false`?

There are two raycast traversal functions in [this file](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/three/raycastTraverse.js) that optimize raycasting using the bounding volume hierarchy to limit the number of tiles checked - so I suspect the functions are stopping once they find an active tile and not checking whether the children have an `ADD` refinement.

Would you like to look into the issue and make a PR?

**Comment by kingwangwang** [comment]
您好！您的邮件已收到。我将在假期结束后，尽快给你回复。
祝您生活愉快。
BY WJC

**Comment by kingwangwang** [comment]
> Hello! Does the issue still occur if `TilesRenderer.optimizeRaycast` is set to `false`?
> 
> There are two raycast traversal functions in [this file](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/three/raycastTraverse.js) that optimize raycasting using the bounding volume hierarchy to limit the number of tiles checked - so I suspect the functions are stopping once they find an active tile and not checking whether the children have an `ADD` refinement.
> 
> Would you like to look into the issue and make a PR?
![87702bdd-66e6-11ed-95be-244bfe021163](https://user-images.githubusercontent.com/61161658/202605002-f061c910-a59d-4edf-9dae-a64be192e118.png)

After testing and modification, it has been solved

**Comment by gkjohnson** [comment]
Great! Can you make a PR into the project that fixes the issue and we can publish a new version with the fix?

**Comment by kingwangwang** [comment]
> @kingwangwang Great! Can you make a PR into the project that fixes the issue and we can publish a new version with the fix?

ok, I'll PR sometime.

**Comment by kingwangwang** [comment]
您好！您的邮件已收到。我将在假期结束后，尽快给你回复。祝您生活愉快。BY WJC
