### ISSUE TITLE
import GLTFCesiumRTCExtension from './GLTFCesiumRTCExtension.js'

### ISSUE THREAD

**Issue by mojin** [NASA-AMMOS/3DTilesRendererJS#303]
No matching export in "node_modules/3d-tiles-renderer/src/three/GLTFCesiumRTCExtension.js" for import "default"

node 16.17.0
vite 2.9.9
vue 3.2.31

**Comment by jesse-small** [comment]
@gkjohnson I have fixed this here https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/304

**Comment by gkjohnson** [comment]
Just published the fix in v0.3.16!
