### ISSUE TITLE
GLTF Loader error while loading dataset

### ISSUE THREAD

**Issue by adoug** [NASA-AMMOS/3DTilesRendererJS#306]
I am trying to load this dataset:
https://vic.digitaltwin.terria.io/api/v0/data/b2518f08-8f65-4c78-9af7-a17191628dc8/v2/tileset.json

But getting an error in GLTF Loader
Cannot read properties of undefined (reading 'getMaterialType')

It looks like its trying to use KHR_materials_unlit extension but its not loaded. I am not sure if I need to register this extension but not sure how. 

In GLTF loader I can see its registering extensions such as `GLTFMaterialsClearcoatExtension` , `GLTFTextureBasisUExtension` and so on but `GLTFMaterialsUnlitExtension` is not registered by default.

![image](https://user-images.githubusercontent.com/2123392/201825465-efb1899c-8ac9-484d-91f8-1a5b43fde2fc.png)

Potentially, this is just a dataset issue, (have no control over dataset) I think the dataset needs to specify `KHR_materials_unlit ` in `extensionsUsed` . I've tested by manually adding `KHR_materials_unlit ` in the GLTF Loader and it loaded the dataset correctly.

Is there a way to inject extensionsUsed post data load fetch but before the FLTF Loader parse is called?

![image](https://user-images.githubusercontent.com/2123392/201864023-b8f3802a-9548-4e64-b0a8-438527ed9eaf.png)

**Comment by gkjohnson** [comment]
The GLTFLoader isn't maintained by this project - you'll want to direct any questions about that over to the forum or the three.js repo. If the gltf content doesn't declare that the unlit extension is used even though it is then that does seem like a dataset issue, though.
