### ISSUE TITLE
can not parse KTX2 texture

### ISSUE THREAD

**Issue by wemamawe** [NASA-AMMOS/3DTilesRendererJS#307]
**Describe the bug**

i want to load a photogrammetry project with draco compression  and ktx2 compression;

***Live example***
it looks white without texture;
<img width="755" alt="image" src="https://user-images.githubusercontent.com/29365634/204987886-a87f24c4-a4c5-4ac4-a7d5-a15de23fb08a.png">
Cesium can display well.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/29365634/204987764-62ac8f16-686c-4087-9ed6-4f4cfad339c6.png">

 - Device: [Desktop]
 - OS: [Windows, MacOS,]
 - Browser: [Chrome,Safari]
 - Three.js version: r136
 - Library version: 0.3.12

**Comment by gkjohnson** [comment]
The three.js GLTFLoader does not automatically support KTX2 textures so you'll need to provide a GLTFLoader instance that has the parser registered. See the [DRACO compression parser registration](https://github.com/NASA-AMMOS/3DTilesRendererJS#adding-draco-decompression-support) example snippet.
