### ISSUE TITLE
I am trying this library to load 3d tile set from japan

### ISSUE THREAD

**Issue by nightfury07x** [NASA-AMMOS/3DTilesRendererJS#311]
i am trying to load 3d tile set from japan that have bounding volume type region 
when try to load it seems .b3dm files are loading but cant see the mesh in three js scene

![image](https://user-images.githubusercontent.com/37612805/208253963-ef83c546-c6e4-430d-b922-d8a9f33a2910.png)

**Comment by nightfury07x** [comment]
@gkjohnson help please

**Comment by gkjohnson** [comment]
Please do not delete the issue template. If you do not provide more information then you're issue cannot be helped.

**Comment by hasithlakshan** [comment]
@gkjohnson I also have same kind of issue and this is my region type json file and its not loading 
![Screenshot 2022-12-19 195512](https://user-images.githubusercontent.com/23122322/208447698-afc31e33-59f4-4b4d-8542-a990369c6b0f.png)

**Comment by gkjohnson** [comment]
Again - please share more information and sample data. Region tilesets are supported in the project but I cannot guess at what else might be going wrong.

I see in the first screenshot that the CESIUM_RTC extension is used in the B3DM files. You can see this issue for more info on that extension and how to use it in b3dm: #300.

**Comment by hasith-dbf** [comment]
@gkjohnson thanks for replying me :).. I tried with the data set from this plateau data site ( https://www.geospatial.jp/ckan/dataset/plateau-47201-naha-shi-2020 ). also I used region type. then using chrome web server and created the JSON path like this (http://127.0.0.1:8887/tileset.json) from the local downloaded dataset. I followed this guideline (https://github.com/NASA-AMMOS/3DTilesRendererJS) to render but I couldn't load the dataset.

**Comment by hasithlakshan** [comment]
@gkjohnson thanks for replying me :).. I tried with the data set from this plateau data site ( https://www.geospatial.jp/ckan/dataset/plateau-47201-naha-shi-2020 ). also I used region type. then using chrome web server and created the JSON path like this (http://127.0.0.1:8887/tileset.json) from the local downloaded dataset. I followed this guideline (https://github.com/NASA-AMMOS/3DTilesRendererJS) to render but I couldn't load the dataset.

**Comment by gkjohnson** [comment]
Thank you - that looks like a cool dataset. It looks like the CESIUM_RTC extension in the B3DM. Right now you have to export add a gltf file-format handler to the manager you pass into the 3d tiles renderer that supports the CESIUM_RTC extension:

```js
import { GLTFExtensionLoader } from '3d-tiles-renderer';

const loader = new GLTFExtensionLoader();
const tilesRenderer = new TilesRenderer( './path/to/tileset.json' );
tilesRenderer.manager.addHandler( /(\.gltf|\.glb)$/, loader );

// or
import { GLTFCesiumRTCExtension } from '3d-tiles-renderer';

const loader = new GLTFLoader( manager );
loader.register( () => new GLTFCesiumRTCExtension() );

const tilesRenderer = new TilesRenderer( './path/to/tileset.json' );
tilesRenderer.manager.addHandler( /(\.gltf|\.glb)$/, loader );
```

**Comment by hasithlakshan** [comment]
@gkjohnson its working...Thank you mate for your amazing support to load the tile set.it was really helpful for me. Cheers
