### ISSUE TITLE
Model below ground

### ISSUE THREAD

**Issue by laraduarte** [NASA-AMMOS/3DTilesRendererJS#312]
Every model loaded with this plugin is a little bit below the ground.
It's easy to reproduce this issue by adding a grid helper to the scene.

grid = new GridHelper(600, 600, 0xff0000, 0xff0000);
grid.material.transparent = true;
grid.material.opacity = 0.1;
grid.material.depthWrite = false;
scene.add(grid);

I expected to see the model clamp to the ground.

Cesium example
![image](https://user-images.githubusercontent.com/1926934/210399825-5b1ea43c-29c2-4f80-97ce-069dc5029b53.png)

Bounding Volume example
![image](https://user-images.githubusercontent.com/1926934/210399910-84e68edd-a45b-4761-8a7a-f2ab94342d50.png)

Index example
![image](https://user-images.githubusercontent.com/1926934/210399974-62a8d71e-1d4c-4efc-a3fd-5c60701d7f2b.png)

Library version (0.3.16)

**Comment by gkjohnson** [comment]
The models in the demos are centered at 0, 0, 0. If you want them to be positioned above 0, 0, 0 you'll have to adjust the position.

**Comment by laraduarte** [comment]
@gkjohnson humm I see, but how do I clamp the model to the ground? Like in the images below? Is there any method for this on the plugin?

![image](https://user-images.githubusercontent.com/1926934/210510871-80d556b5-1cea-4e35-88fe-52720d8dcf45.png)
![image](https://user-images.githubusercontent.com/1926934/210510951-9cf56662-32fc-437c-84a1-e1a4d0678413.png)
![image](https://user-images.githubusercontent.com/1926934/210513252-e5895e5a-a9ee-4dbe-9e7a-d49fa6f29d67.png)

**Comment by laraduarte** [comment]
I understand what you mean @gkjohnson but I have no idea how to do that :D 
This is very new to me so I am a little bit lost!

Can you provide an example? 
thank you so much!

![image](https://user-images.githubusercontent.com/1926934/210533333-71bf6da3-7161-4fcc-86f9-0bda77e12ed0.png)

**Comment by gkjohnson** [comment]
Unfortunately I don't have the bandwidth to provide personal help. If you need help with three.js generally I recommend the three.js discord or [forum](https://discourse.threejs.org/).
