### ISSUE TITLE
Need example with  react-three-fiber

### ISSUE THREAD

**Issue by cyrilpreiss** [NASA-AMMOS/3DTilesRendererJS#314]
Hi,

i'm trying to use this great library with react.

I manage to display the model: https://gigascopejs.firebaseapp.com/3d/piece

But the orbit control doesn't work.

So i'm trying to use react-three-fiber but i have difficulties to make it work with the loader. Could you try and provide an example ?

**Comment by gkjohnson** [comment]
If you have questions about react or react-three-fiber please ask at the three.js forum or a dedicated r3f community.
