### ISSUE TITLE
import GLTFCesiumRTCExtension from './GLTFCesiumRTCExtension.js';

### ISSUE THREAD

**Issue by comYanXiang** [NASA-AMMOS/3DTilesRendererJS#315]
tags:v0.3.15

**Comment by gkjohnson** [comment]
Please make an effort to describe a problem if you're going to report an issue.

**Comment by comYanXiang** [comment]
can you speek chinese?

**Comment by gkjohnson** [comment]
Unfortunately I cannot but there are a variety of services that can be used to translate to english. Also if you are using v0.3.15 please make sure to upgrade to the latest version if you are having any problems (v0.3.16)
