### ISSUE TITLE
Is there a plan to use Worker?

### ISSUE THREAD

**Issue by Junior2Ran** [NASA-AMMOS/3DTilesRendererJS#318]
I noticed that `fetch` and `parse` tiles are processed all in `TilesRenderer`, which is main thread. Is there a plan to change the procedure to Workers like Cesium? The performance should be better.

**Comment by gkjohnson** [comment]
There are no plans to add a worker but if you're running to performance issues and think that web worker support would fix the issue I'm happy to take a PR. But first I'd ask that you provide some performance and timing information to show where the current bottleneck is and make sure that performing the task in a worker fixes the problem and is worth the added complexity. Of course it depends on the geometry but in my experience most of the hiccups from model loading come from data upload to the GPU which cannot be performed in a worker.

**Comment by dbuck** [comment]
Similar findings here, we considered it, and **might** like to move the fetch out as potential improvement, but it's not a definite easy win without verification, a lot of my issues with slow parse ended up being issues that are better handled by adjusting the tileset layout and contents?

- That said, we're also running with draco+ktx, so much of the heavy lifting is already workerized internally by three and the gltf loader implementations, so your mileage may vary depending on the content and extensions used?

**Comment by Junior2Ran** [comment]
> that are better handled by adjusting the tileset layout and contents

That is definately right! However in most cases, tileset data's quality is not under control with frontend. I just want to find a way to deal with those data that are composed ugly by low level data providers.

If you professional guys say this way cannot fix the performance bottleneck, then I will forget it. Because somtimes, bear with it is also an effective solution :)

**Comment by Junior2Ran** [comment]
Thanks for your professional explainations, it really helps. Though my problem still exists, I learned a lot.

**Comment by dbuck** [comment]
@Junior2Ran Step 1 of that is expanding on what the words 'my problem' means in that last message ! You should provide some more information about the problem / particular tilesets / tests / profiles? 

We're just starting to consider similar work, though it's just unlikely that it comes up 'soon' on the priority to actually work on, as it's not a huge problem for us, but it might be nice?

Makes an actual case for doing this work that is beneficial to you ;) Part of something like this is always determining what the NEED is and what a change would gain us and other possible users?

**Comment by gkjohnson** [comment]
Closing until a more clear benefit and use case can be provided.
