### ISSUE TITLE
Child tiles render far from camera

### ISSUE THREAD

**Issue by ziiler** [NASA-AMMOS/3DTilesRendererJS#319]
At higher levels of detail, child tiles are rendered in regions of the model farther from the camera rather than in closer areas, as though  the screenSpaceError and errorTarget were ignored. In addition, parents are not unloaded.

The model is available at : https://3drockmaps.com/bundle/r3d_stjeannet.html

I have attached a few screenshots to clarify the problem.

Lower detailed LODs work perfectly: child tiles replace parent tiles when the screenSpaceError exeeds the errorTarget:
![LOD_0and1](https://user-images.githubusercontent.com/61741140/226134532-a3e90521-2deb-4a01-961a-f659a0d38f62.png)

Things start to go wrong: for the next level of detail (pink bbox) some tiles load in front and some in the back:
![LOD_1and2](https://user-images.githubusercontent.com/61741140/226134912-1d15255a-6b70-433e-a39d-c4f1f1b7212e.png)

Here it get really bad! The next LOD (blue marine bbox) loads in the background only:
![LOD_2and3](https://user-images.githubusercontent.com/61741140/226134966-70fccf3f-475e-4d4f-aa66-c1d5e2eb5ee0.png)

Settings:
geometric_errors = [50, 35, 15, 8, 0.5, 0.05]
'errorTarget': 200
'errorThreshold':2000
'maxDepth': 15
Nested tilesets in the first 2 LODs.

What is triggering the different behavior of the renderer as the camera gets closer to the model?
I have complete control over the tile and tileset properties,  what do I have to tweak?

PS Great work

**Comment by gkjohnson** [comment]
Hello! Looking briefly at your tileset it looks like you're using nested tileset json for every piece of geometry which is unnecessary and definitely not recommended since it will cause everything to load pretty slowly - it adds a ton of overhead to loading a new piece of geometry since in order to load a low LOD geometry multiple json files must be loaded, parsed, and traversed to get to the b3dm file url.

**Comment by ziiler** [comment]
OK, I just uploaded a single tileset file.
I was experimenting with ways to reduce initial loading time with large tilesets, in the online model I have not included all the LODs.

**Comment by gkjohnson** [comment]
Yes there are tradeoffs to consider but the json file does not seem so large for a tileset. It's also advise-able to not have so many children of any given node since each LoD layer must wait until all children have loaded before any child tiles can display.
