### ISSUE TITLE
Cesium tiles transform

### ISSUE THREAD

**Issue by chunlampang** [NASA-AMMOS/3DTilesRendererJS#320]
I am trying to load a cesium tiles. However, the tiles is rotated and the position is very far away.
Are there any methods to reset the transform?

![image](https://user-images.githubusercontent.com/30290516/227131099-4f1b1315-9806-480d-85af-9894f503cac8.png)

**Comment by gkjohnson** [comment]
You can get the oriented bounding box with the `getOrientedBounds` function and use that to center and orient the tileset using regular three.js functionality. You can see that done in the examples here:

https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/87cec070fe4b95179a927c93b77e2e5dcf23ea7e/example/ionExample.js#L178-L210

**Comment by chunlampang** [comment]
You can place the model at the center now.
However, I am stuck on another issue. When the camera is 90deg look at the tiles and then rotate it clockrise, half of the angle will hide the tiles.

**Comment by gkjohnson** [comment]
Sorry - your issue isn't clear. Without a demonstration I won't be able to help.
