### ISSUE TITLE
raycast error tile when ray origin is inside the tile bounding

### ISSUE THREAD

**Issue by powerocean** [NASA-AMMOS/3DTilesRendererJS#321]
**Describe the bug**

1. set rayCaster.firstHitOnly = true
2. move the camera very close to the Tile
3. then pick the tile, sometimes it will pick tiles that are farther away

***src/three/raycastTraverse.js***

```js
if ( _ray.intersectBox( boundingBox, _vec ) ) {

    //...... 
    data.distance = _vec.distanceToSquared( _ray.origin ) * invScale * invScale;
    data.tile = tile;

}

```

when boundingBox.containsPoint(_ray.origin), _vec will on another farther side of the box,
and distanceToSquared value may become very large. 
that Caused the current tile to be in the wrong position in the array after sorting

And The following code works for me: 

```js
if (boundingBox.containsPoint(_ray.origin)) {
	data.distance = 0;
}
else {
	data.distance = _vec.distanceToSquared( _ray.origin ) * invScale * invScale;
}
```

**Comment by gkjohnson** [comment]
Thanks! Looks like this will happen in the case that the ray starts inside a bound and a sibling bound overlaps the bound the ray origin is in.

Would you like to make a PR?
