### ISSUE TITLE
How can I obtain the components of the model?

### ISSUE THREAD

**Issue by kingwangwang** [NASA-AMMOS/3DTilesRendererJS#325]
could you  tell me why mesh is the entire tile when I perform radiographic testing?

![微信图片_20230427161650](https://user-images.githubusercontent.com/61161658/234802370-bfd55ef1-c273-4f34-b291-865efe75bcc1.png)

 If I perform radiographic testing on the same model in gltf format, components will be detected. 
![微信图片_20230427162022](https://user-images.githubusercontent.com/61161658/234803245-8cfb98f3-11d1-4e76-b472-5aa06642a3bc.png)

**Comment by gkjohnson** [comment]
Assuming you mean when selecting via raycast - it looks like the models have been instanced and are represented by a single "InstancedMesh" or batched model. Though with the information you've provided it's unclear how you've processed the model or generated the tileset. You'll have to highlight via instance id or batch id depending on how they've been merged.

**Comment by kingwangwang** [comment]
> Assuming you mean when selecting via raycast - it looks like the models have been instanced and are represented by a single "InstancedMesh" or batched model. Though with the information you've provided it's unclear how you've processed the model or generated the tileset. You'll have to highlight via instance id or batch id depending on how they've been merged.


![微信图片_20230427175120](https://user-images.githubusercontent.com/61161658/234827381-7fdffe1e-217b-4c69-a6fe-c29d55fd1c45.png)
I generated 3tiles after slicing the Revit model, and did not instantiate it. I was able to obtain the ID of the corresponding component, but I was unable to use ray selection to select the model component.


![2](https://user-images.githubusercontent.com/61161658/234827631-34cad82a-9dca-4da0-9ce7-d6765f4f94bd.png)
![3](https://user-images.githubusercontent.com/61161658/234827665-128c8bf6-c59b-4677-8c8c-6201f3166517.png)
![1](https://user-images.githubusercontent.com/61161658/234827679-514a17d2-7ead-48f2-aaf0-3e4552723931.png)
In fact, b3dm comes from gltf, and when I used three. js to perform radiographic testing on the gltf model generated after revit conversion and select the model, I did not see any issues caused by instantiation.

![4](https://user-images.githubusercontent.com/61161658/234829062-0e569e28-6908-45da-908d-c371a061003a.png)

**Comment by gkjohnson** [comment]
B3DM provides special support for merging and batching geometry and providing unique ids for each submesh in the merged model to help with performance and reducing draw calls so just comparing this to GLTF is not enough. I do not know what revit does on export but it's possible it is automatically batching some geometry together based on a common material. If this is a b3dm model with a batched mesh then the geometry for that particular model will likely have extra attributes such as "_batchid" provided to identify the individual components.

**Comment by gkjohnson** [comment]
You can see how to select individual components of a batched model in [this example](https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/b3dmExample.html) (code [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/b3dmExample.js)) which uses custom shader materials.

If you feel certain that the b3dm provides individual meshes for each components then you'll have to provide the B3DM file.
