### ISSUE TITLE
Can't display smaller tiles correctly

### ISSUE THREAD

**Issue by tomhsiao1260** [NASA-AMMOS/3DTilesRendererJS#327]
Hi, thanks in advance for this repo! It helps me a lot to explore what can be done on top of three.js.

I try to use it to visualize a group of cubes set, each cube is a b3dm file, however, some of them can't display when the camera get close enough to it.

#### Here is a demo of 16x16x16 cubes. Each larger cube contains 8 smaller cubes inside.

https://user-images.githubusercontent.com/31985811/235232303-60173b4a-e957-470d-9774-3a9a28e007ac.mp4

#### Here is a demo of 1x16x16 cubes. Each larger cube contains 4 smaller cubes inside (align to the same face).

https://user-images.githubusercontent.com/31985811/235232406-711df394-0ce6-48e4-b891-46b0eec8450e.mp4

### Problem:
I found that it's hard for me to display the smallest cube in 16x16x16 case but it works well in 1x16x16 case. Not sure but I guess perhaps the issue comes from boundingVolume setting in tileset.json file. After a period of debugging, I still don't know how to display it correctly, so posted this issue to see if I missed something

### To Reproduce:
The ZIP folder below is the data I use for this demo which contain:

- tileset-16x16x16.json: the tileset file of 16x16x16 cubes demo
- tileset-1x16x16.json: the tileset file of 1x16x16 cubes demo
- b3dm folder: the corresponding b3dm data (for both 16x16x16 & 1x16x16)

👉👉👉   [data.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/11356645/data.zip)   👈👈👈

More precisely, in tileset-16x16x16.json case, I can't display b3dm files with 5-digit names (e.g. 01132.b3dm, 03333.b3dm, etc.) which works well in 1x16x16 case. Any suggestion?

**Comment by gkjohnson** [comment]
See the documentation for "LRUCache". It limits the amount of tiles that can be downloaded to prevent crashing the WebGL context and with the provided view your tileset requires downloading thousands of tiles. You can adjust the max cache size through the settings.

**Comment by tomhsiao1260** [comment]
Is it possible for me to only display the outermost cubes in 16*16*16 case? Want to render something like this on the top of `3DTilesRendererJS` and `three-mesh-bvh` but still don't know how to achieve that. Some clues, keywords or related examples would be helpful, thanks!
https://discord.com/channels/685241246557667386/1168839422935056434

**Comment by gkjohnson** [comment]
What you're describing is "occlusion culling" which is significantly more complicated and not handled by the 3d tiles spec.
