### ISSUE TITLE
tiles come in tilted

### ISSUE THREAD

**Issue by rck1** [NASA-AMMOS/3DTilesRendererJS#328]
**Describe the bug**

Some 3D tile samples come in tilted by approximately 45 degrees.  This occurs even when correcting for z-up, etc.  I don't think this is a bug but this has occurred with multiple other datasets and I hope to get some suggestions.

**To Reproduce**

Example 3D tile from NY Times loads with the "tilt":  https://int.nyt.com/data/3dscenes/ONA360/TILESET/0731_FREEMAN_ALLEY_10M_A_36x8K__10K-PN_50P_DB/tileset_tileset.json

**Expected behavior**

3D tiles should be rendered properly with y-up (after performing transforms for z-up datasets, etc.)

**Screenshots**

The screenshot is looking straight down the z-axis with y-up.  However the 3D tiles are rendered with a ~45 degree tilt.

![Screen Shot 2023-04-28 at 8 47 24 PM](https://user-images.githubusercontent.com/33330922/235274010-a840eda5-1238-4543-9900-3df7d3012ef4.png)

**Platform:**

 - Device: Desktop
 - OS: Windows, MacOS
 - Browser: [Chrome, Safari, Edge
 - Three.js version: [r149]
 - Library version: [v0.3.17]

**Comment by gkjohnson** [comment]
Many tilesets are specified in the [WGS84](https://en.wikipedia.org/wiki/World_Geodetic_System) coordinate frame which defines Z+ to be pointing in the direction of the earths surface normal. So depending on the lat/lon of the tileset it will appear tilted when out of that context. You'll have to rotate the tileset such that it's local Z+ vector is oriented to three.js Y+ if you don't want to view it with that tilt.

**Comment by rck1** [comment]
Thank you @gkjohnson !  This is very helpful.  I am new to the 3D Tiles spec.  Is there a way to determine if a tileset is specified in the WGS84 coordinate frame?  Can you provide guidance on how I can determine the Z+ vector if its based on the surface normal of the earth so I can perform the appropriate transformation to y-up?

**Comment by rck1** [comment]
I found a good solution here:  #237 [How can I use matrix instead of quaternion?](https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/237#issuecomment-1013753957)
