### ISSUE TITLE
Google Maps Tiles demo needed improvements

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#331]
Here's a list of features needed to improve

**Improved Globe Orbit Controls**
- ~Use three.js' [MapControls](https://threejs.org/docs/?q=MapCon#examples/en/controls/MapControls) which pans along the camera's "up" direction rather than in screen space.~ #346
- ~Use the "Ellipsoid" class to derive latitude, longitude, and surface normal from the camera position position so we can adjust the plane the map controls pans on based on the position.~ #46
- ~Fix the controls target to be the WGS84 ellipsoid surface so we scroll on a reasonable plane.~ #346
- ~Use raycasting to adjust the camera / controls target height based on loaded geometry / mountains.~ #346
- When zooming out transition to an orbital camera

**Zoom Controls**
- Adjust MapControls to zoom in to the cursor position.

**Camera View Range**
- ~Scale the camera near and far so only necessary tiles are loaded - and tiles on the opposite side of the globe are not.~ #346
  - Perhaps keeping the camera far fixed at the perpendicular plane at the earth's center is good enough?

**Metadata**
- ~Display data copyrights based on visible tiles~ #337
  - See tile glb metadata
  - https://developers.google.com/maps/documentation/tile/create-renderer
- ~Display current latitude and longitude~ #338

**Jump to location**
- Use window hash to specify which latitude and longitude to jump to

**Comment by gkjohnson** [comment]
> Note that MapControls projects the camera up onto the y=0 plane and pans along that vector.

Did you try adjusting camera.up? The docs say that MapControls pan orthogonal to the cameras up direction:

https://threejs.org/docs/?q=map#examples/en/controls/MapControls.screenSpacePanning

**Comment by aiden-jeffrey** [comment]
> Did you try adjusting camera.up? The docs say that MapControls pan orthogonal to the cameras up direction:

Yes, but the [`panLeft`](https://github.com/mrdoob/three.js/blob/master/examples/jsm/controls/OrbitControls.js#L396) function needs patching to support the same functionality, so I don't think there's any way around forking. See my changes here: https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/GlobeOrbitControls.js#L412

**Comment by gkjohnson** [comment]
> Also, I don't think camera.up ever gets updated (it's always normalised y vector).

[Object3D.up](https://threejs.org/docs/?q=objec#api/en/core/Object3D.up) is a configurable value - you have to change it.

**Comment by gkjohnson** [comment]
Closing in favor of other issues
