### ISSUE TITLE
Interactive three-d globe component in angular 

### ISSUE THREAD

**Issue by yogibear234** [NASA-AMMOS/3DTilesRendererJS#388]
Hi, I wanted to know if we can render a three dimensional spinning globe kind of UI with this library, something that can already be done with CesiumJS. My particular use case is as follows:

1. I want an interactive globe that can spin based on mouse events.
2. I want to be able to drop colored pins that can redirect to pages on clicks (similar to entities in CesiumJS)
3. I want pop-up tooltips when I hover on said entities to display some predefined data.

I want to know whether something like this is feasible or not using 3DTilesRenderer coupled with angular.

Thanks again.

**Comment by gkjohnson** [comment]
It's of course all possible - but you have to implement these things on top of the library yourself. There are no provided camera controls or 2d UI components in this project. I am not familiar with Angular but I don't see why this wouldn't be possible with the framework.
