### ISSUE TITLE
3DTile Model Load Not Propertly

### ISSUE THREAD

**Issue by WallanceLee** [NASA-AMMOS/3DTilesRendererJS#394]
Hello eveyone, I am new to use this library. 
According to README, my project is built with vue3, vite and this library. When loading my 3dTiles model, it just not loaded b3dm even. I am very confused to debug this problem. Thanks for your help for this debug question.
I just compared your example tileset json and mine, and I found one difference in root.content.uri field that mine doesn't have this one field and yours have, is it a point?

**Comment by gkjohnson** [comment]
There's no way the problem can be helped if you don't provide a sample of the problematic data.

**Comment by WallanceLee** [comment]
This is my problematic data. Thanks a lot.
[Archive.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/12216204/Archive.zip)


> There's no way the problem can be helped if you don't provide a sample of the problematic data.

**Comment by gkjohnson** [comment]
The model loads fine - it just needs to be centered which can be done using the bounding boxes. Related to #395.

<img width="583" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/734200/25e2b486-b1f8-4a9a-b6ce-68aa1ce72928">
