### ISSUE TITLE
GoogleTilesRenderer crashes on iPhone

### ISSUE THREAD

**Issue by gffilux** [NASA-AMMOS/3DTilesRendererJS#396]
I was trying to test the googleMapsAerial example and found that it breaks after working for a while (approximately after 15 seconds in my case) on an iPhone 13. It seems like a memory leak that crashes the browser (both Safari and Chrome), but currently, I do not have the means to verify if this is the actual cause of the issue.

To reproduce the issue, simply load the [GoogleTilesRenderer example](https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/googleMapsAerial.html) from the master branch with a valid Google Tiles API Key and navigate around the example for a few seconds on an iPhone 13. I also tested it locally using version 3.20 of the library and faced the same issue.

This is not happening to me on PC or Android phones (I launched the example on a POCO X4 Pro 5G and POCO X3 Pro), so it seems to be related only to iOS devices. The issue has been reproduced on several iPhone 13 devices with the latests iOS updates but I cannot confirm if this is happening on other Apple devices.

**Comment by gkjohnson** [comment]
Please provide more information. What logs are being reported? Does reducing the "errorTarget" improve the situation? Or reducing the pixel ratio? What ix the pixel ratio of your phone?
