### ISSUE TITLE
cannot get basic demos to work locally

### ISSUE THREAD

**Issue by AndrewAnnex** [NASA-AMMOS/3DTilesRendererJS#397]
**Describe the bug**

Demos don't work on current master with fresh nodejs. I get exceptions like "Uncaught SyntaxError: Cannot use import statement outside a module (at mars.js:1:1)" for each demo I tried and a blank web browser window each time.

**To Reproduce**

clone the repo 
npm install
npm start
go to http://localhost:9080/example/mars.html and open the developer tools to look at the logs in the console

**Platform:**

 - Device: Laptop mbp
 - OS: macos
 - Browser: Chrome, Safari
 - Three.js version: three@0.153.0
 - Library version: current master branch a25bb252e0bf316e673e8ca38574b7a58d7da841

**Comment by gkjohnson** [comment]
You must load the files in the built "dev-bundle" folder:

```
http://localhost:9080/example/dev-bundle/mars.html
```

The build process could be updated to just use the parcel "serve" command if you'd like to help update the dev process.

**Comment by AndrewAnnex** [comment]
@gkjohnson okay thanks, I am primarily a python dev so some of the nodejs norms are new to me. Maybe will contribute that once I get more familiar
