### ISSUE TITLE
We are having to use patch-package to change the draft export as in order to use this library, what are we doing wrong?

### ISSUE THREAD

**Issue by charlesritchea** [NASA-AMMOS/3DTilesRendererJS#398]
It's my understanding that `export * as GeoUtils` is a draft ecmascript feature, and our current build system doesn't support it. Until we can figure out how to support it, we are using patch-package to just change it to something that compiles:

```
diff --git a/node_modules/3d-tiles-renderer/src/index.js b/node_modules/3d-tiles-renderer/src/index.js
index 9bdc0c4..336e04c 100644
--- a/node_modules/3d-tiles-renderer/src/index.js
+++ b/node_modules/3d-tiles-renderer/src/index.js
@@ -23,7 +23,7 @@ export { EllipsoidRegionHelper, EllipsoidRegionLineHelper } from './three/object
 export { SphereHelper } from './three/objects/SphereHelper.js';
 export { Ellipsoid } from './three/math/Ellipsoid.js';
 export { EllipsoidRegion } from './three/math/EllipsoidRegion.js';
-export * as GeoUtils from './three/math/GeoUtils.js';
+export * from './three/math/GeoUtils.js';
 export * from './three/math/GeoConstants.js';
 export * from './three/renderers/GoogleTilesRenderer.js';
 export * from './three/renderers/CesiumIonTilesRenderer.js';
```

based on the fact that nobody else seems to have reported this, I'm assuming the staleness of our old lerna bootstrap / webpack 4 monorepo is the culprit, but I was hoping someone would know exactly what we need to do to support this feature and why it's even ok to use without causing lots of incompatibility issues with consumers of the library. Any help or advice would be welcome

**Comment by gkjohnson** [comment]
> It's my understanding that export * as GeoUtils is a draft ecmascript feature, and our current build system doesn't support it.

It's not draft at all from what I can tell - from [caniuse](https://caniuse.com/mdn-javascript_statements_export_namespace) it's been supported in all major browsers for over 2-4 years depending on vendor and it's described without caveat on [MDN](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#re-exporting_aggregating). 

> webpack 4 monorepo is the culprit,

Webpack 5 has been released for almost 3 years. And the last release of release of Webpack 4 was [almost as long ago](https://github.com/webpack/webpack/releases/tag/v4.46.0). I'd recommend using modern versions of your build dependencies.

**Comment by charlesritchea** [comment]
I'm well aware of the Webpack staleness preaching to the choir. I'm
unfortunately unable to upgrade currently. I've tried many many times. Ok,
I'll just keep the patch until I can get Webpack upgraded then I guess.
I've literally been trying to upgrade Webpack for a year with this shitty
repo

**Comment by charlesritchea** [comment]
I have been trying to upgrade to webpack 5 all year, there is always some blocker. I can't "just upgrade" when that means a million lines of code changes. Thanks for verifying that it's not draft. I'll figure it out then... thanks for writing this library.
