### ISSUE TITLE
Relative path not loaded

### ISSUE THREAD

**Issue by zhoujingfu** [NASA-AMMOS/3DTilesRendererJS#399]
Hello, I tried using this library to load tile files and found that the relative path was not loaded, but it can be displayed normally in cesium，what I supposed to do? Thank you！
 
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/43539608/e2a299de-e0d3-4545-95e0-28e2317ac0e3)

only on request in this lib

![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/43539608/83182308-a127-40a1-9922-a24962f93197)

**Comment by gkjohnson** [comment]
If you don't provide any example data, a working example, or even logs then there's no help that can be provided.

**Comment by zhoujingfu** [comment]
> If you don't provide any sample data, a live example of the issue, or even logs then there's no help that can be provided.

This is my sample data, The file exceeds the size, please download it, thanks.
[https://github.com/zhoujingfu/canvas-editor/blob/ef5a5c990fa7fd4a16b29ff4f2613dff7944da37/testjson.zip](url)

**Comment by gkjohnson** [comment]
The linked tileset loads just fine without any special setup.

<img width="739" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/734200/59556e99-a6cd-4451-a28a-5f6e34b217d3">

**Comment by gkjohnson** [comment]
> can you show your code? please ^_^

The code I used is already present in the examples and documentation. You can share a minimal example of what's not working for you as I requested previously and I can take a look.

**Comment by zhoujingfu** [comment]
> > can you show your code? please ^_^
> 
> The code I used is already present in the examples and documentation. You can share a minimal example of what's not working for you as I requested previously and I can take a look.

here is the minimal example : https://codesandbox.io/p/sandbox/trusting-chatelet-dxnwc8?file=/src/components/HelloWorld.vue:56,15

**Comment by gkjohnson** [comment]
Please check the logs of your example. This is a server resource issue:

> Access to fetch at 'https://www.xpheng.com/3dmodel/Apps/assets/testjson(1)/testjson/tileset.json' from origin 'https://dxnwc8-5173.csb.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by zhoujingfu** [comment]
> Please check the logs of your example. This is a server resource issue:
> 
> > Access to fetch at 'https://www.xpheng.com/3dmodel/Apps/assets/testjson(1)/testjson/tileset.json' from origin 'https://dxnwc8-5173.csb.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Sorry, Because I opened the chrome plugin, the resource issue has been fixed, but the problem still exists
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/43539608/95c72e1d-52f6-46d8-beab-78b9eb2212e1)

![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/43539608/c996cfc3-f178-4230-aee4-5ced8f8f9389)

**Comment by zhoujingfu** [comment]
> > Please check the logs of your example. This is a server resource issue:
> > > Access to fetch at 'https://www.xpheng.com/3dmodel/Apps/assets/testjson(1)/testjson/tileset.json' from origin 'https://dxnwc8-5173.csb.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 
> Sorry, Because I opened the chrome plugin, the resource issue has been fixed, but the problem still exists ![image](https://user-images.githubusercontent.com/43539608/267614791-95c72e1d-52f6-46d8-beab-78b9eb2212e1.png)
> 
> ![image](https://user-images.githubusercontent.com/43539608/267614865-c996cfc3-f178-4230-aee4-5ced8f8f9389.png)

The reason should be that the uri of json points to the second layer of json, not the b3dm file.

**Comment by gkjohnson** [comment]
If you look at the bounding box of the tileset it is way off center and therefore offscreen. You can retrieve the bounding box of the tileset with the "getBounds" function and use that to center the mode.
