### ISSUE TITLE
Validation : Validate against other 3D Tiles data sets

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#4]
https://github.com/CesiumGS/3d-tiles-samples

It looks like the 3d tile sets at the link require a legacy version of GLTFLoader to work.

**Comment by gkjohnson** [comment]
Another reference set:

https://github.com/NASA-AMMOS/Unity3DTiles/issues/1#issuecomment-517086870

**Comment by gkjohnson** [comment]
Hey @munrocket! I know you've expressed interest in this in the past -- do you happen to have any 3d tiles datasets available that I can use to test? I'm using internal data right now but it would be great to validate more against something that's been generated elsewhere. Unfortunately public 3d tiles data sets seem to be hard to come by!

**Comment by munrocket** [comment]
@gkjohnson Sorry, I just had one CAD viewer that always tried to open large files that slowed down fps in browsers. I stopped with merged mesh with texture atlas and .glb + .draco, but anyway rendering was slow sometime and I was unable to simplify geometry with blender, because result was not good enough for this viewer.

I am expecting that this Tiles3D approach from CesiumJS (and other progressive mesh methods) will be a great real-time optimization in renderer, because they based on tree and can reduce amount of vertices.

Here pdf that describe format: https://github.com/CesiumGS/3d-tiles/blob/master/3d-tiles-overview.pdf

**Comment by gkjohnson** [comment]
Yeah I'm very familiar with the format, now I was just looking for some test data from other people to make sure I was rendering everything correctly. Something like 3D Tiles could definitely help with that use case but it would come with quite a few limitations can't select or move individual parts, etc. I'm not sure what kind of publicly available converters there are, though.

I'll keep looking for some other datasets -- thanks for your help!

**Comment by munrocket** [comment]
Wow, this is cool!

**Comment by munrocket** [comment]
Can I help you with your project? Where better to start with small improvements?

**Comment by gkjohnson** [comment]
@munrocket 

> Can I help you with your project? Where better to start with small improvements?

Glad to hear it! The features I need for the projects I'm working on are implemented but there are still some 3d Tiles features unimplemented.

The other mesh file formats are the lowest hanging fruit, I think. 3DTiles supports B3DM, I3DM, PNTS, and CMPT formats for representing tile data. B3DM is the only file format currently loading but it would be nice to add basic loading capability for all of them. I've added a test page for B3DM [here](https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/b3dmExample.html) as an example. I think a similar page for the PNTS points file or I3DM instanced geometry format would be a good next step to validate they work. These are also features I likely won't be able to get to myself because I've got so much on my plate at the moment. Issue #67 is a pretty big catch-all issue for loading these but we can make smaller issues, too.

#60 for quickly loading image data might be bite-sized. I'm using `createImageBitmap` to load textures but behavior is apparently a bit inconsistent across browsers. I don't know if you're familiar with it but it's on my list to make sure that is working correctly.

Let me know if you're interested in either of those and maybe we can break some of the issues down a bit and I can fill in a bit more detail!
