### ISSUE TITLE
pnts render error  THREE.DRACOLoader: Decoding failed: Unsupported geometry type.

### ISSUE THREAD

**Issue by chenguang1994** [NASA-AMMOS/3DTilesRendererJS#400]
Error: THREE.DRACOLoader: Decoding failed: Unsupported geometry type.
code examples
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/31501915/0b102b2d-b3e5-4628-9935-bdc10f72a8e2)

erro info
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/31501915/b0133cf0-d403-4831-b3c3-fd20ccbd6a38)

the pnts is cesium ion assets
view 
https://sandcastle.cesium.com/?src=Hello%20World.html&label=Showcases&code=eyJjb2RlIjoiLy8gR3JhbnQgQ2VzaXVtSlMgYWNjZXNzIHRvIHlvdXIgaW9uIGFzc2V0c1xuQ2VzaXVtLklvbi5kZWZhdWx0QWNjZXNzVG9rZW4gPSBcImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpxZEdraU9pSm1OVEF4WlRZM05TMWxZemc1TFRRNFlUZ3RPRGxpTXkwMk1HWTVPVEZrTldSbFkyTWlMQ0pwWkNJNk1qSXdNalVzSW5OamIzQmxjeUk2V3lKaGMzSWlMQ0puWXlKZExDSnBZWFFpT2pFMU9ERXdPRFE1TlRsOS5zcy1Pam9HMjhMUDc3MDJHQ0EtZTBJWXR2dzNnakNFMmZmckRRc0ZQVHNzXCI7XG5jb25zdCB2aWV3ZXIgPSBuZXcgQ2VzaXVtLlZpZXdlcihcImNlc2l1bUNvbnRhaW5lclwiKTtcblxudHJ5IHtcbiAgY29uc3QgdGlsZXNldCA9IGF3YWl0IENlc2l1bS5DZXNpdW0zRFRpbGVzZXQuZnJvbUlvbkFzc2V0SWQoMjg5NDUpO1xuICB2aWV3ZXIuc2NlbmUucHJpbWl0aXZlcy5hZGQodGlsZXNldCk7XG4gIGF3YWl0IHZpZXdlci56b29tVG8odGlsZXNldCk7XG5cbiAgLy8gQXBwbHkgdGhlIGRlZmF1bHQgc3R5bGUgaWYgaXQgZXhpc3RzXG4gIGNvbnN0IGV4dHJhcyA9IHRpbGVzZXQuYXNzZXQuZXh0cmFzO1xuICBpZiAoXG4gICAgQ2VzaXVtLmRlZmluZWQoZXh0cmFzKSAmJlxuICAgIENlc2l1bS5kZWZpbmVkKGV4dHJhcy5pb24pICYmXG4gICAgQ2VzaXVtLmRlZmluZWQoZXh0cmFzLmlvbi5kZWZhdWx0U3R5bGUpXG4gICkge1xuICAgIHRpbGVzZXQuc3R5bGUgPSBuZXcgQ2VzaXVtLkNlc2l1bTNEVGlsZVN0eWxlKGV4dHJhcy5pb24uZGVmYXVsdFN0eWxlKTtcbiAgfVxufSBjYXRjaCAoZXJyb3IpIHtcbiAgY29uc29sZS5sb2coZXJyb3IpO1xufVxuIiwiaHRtbCI6IjxzdHlsZT5cbiAgQGltcG9ydCB1cmwoLi4vdGVtcGxhdGVzL2J1Y2tldC5jc3MpO1xuPC9zdHlsZT5cbjxkaXYgaWQ9XCJjZXNpdW1Db250YWluZXJcIiBjbGFzcz1cImZ1bGxTaXplXCI+PC9kaXY+XG48ZGl2IGlkPVwibG9hZGluZ092ZXJsYXlcIj5cbiAgPGgxPkxvYWRpbmcuLi48L2gxPlxuPC9kaXY+XG48ZGl2IGlkPVwidG9vbGJhclwiPjwvZGl2PlxuIn0=

**Comment by gkjohnson** [comment]
The error you've reported is from the native DRACO library and subsequently thrown from three.js' DracoLoader (see [here](https://github.com/mrdoob/three.js/blob/1250397f1867f35f1e4023ac1ed5383d3fb15e50/examples/jsm/loaders/DRACOLoader.js#L498-L502)). I recommend extracting the draco contents from a tile that is throwing an error and providing that with a working reproduction in the three.js repo.

If it seems the issue is from this repository we can reopen this issue.
