### ISSUE TITLE
How to get the centre location (latitude and longitude) of the 3D tiles when the user moves the 3D view?

### ISSUE THREAD

**Issue by inodw1** [NASA-AMMOS/3DTilesRendererJS#404]
Hi,

I am working with your 3D tiles renderer and implemented a 3D view to display location 3D data when the user moves on the 2D map (used Mapbox). I implemented it by passing lat, lng to the setLatLonToYUp.
` const { lat, lng } = mapCenterOnMove;
        tiles.setLatLonToYUp(lat * MathUtils.DEG2RAD, lng * MathUtils.DEG2RAD);
        tiles.update();`
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/23226783/cfa46750-c372-4dac-9ab8-b1ca4526e068)

_It is working fine._

Now, I need to Synchronize the 3d tiles with the 2d map. For that, _when the user moves the 3D view needs to move the 2D map too. For that, I need to get the centre location (latitude and longitude) of the 3D tiles according to my scene._ I was looking at the tiles data inside of the onTileVisibilityChange and onLoadModel. But I couldn't able to find the location details.

I need some help from you guys to achieve this. **How can I get the centre location (latitude and longitude) of the 3D tiles based on tiles data in my scene when the user moves the 3D view?**

**Comment by gkjohnson** [comment]
I assume you're using the `GoogleTilesRenderer` class? In this case the tiles renderer exposes the [globe wgs84 ellipsoid](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/three/renderers/GoogleTilesRenderer.js#L13-L17) which provides a [getPositionToCartographic](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/three/math/Ellipsoid.js#L83C1-L84C1) function that can be used to convert a local position in the tiles group to a cartographic position.

The Ellipse class is not super documented but if you'd like to make a PR that adds some basic documentation for some of the functions that would be appreciated.
