### ISSUE TITLE
About Error Reporting： THREE.GLTFLoader: Legacy binary file detected

### ISSUE THREAD

**Issue by 3261564019** [NASA-AMMOS/3DTilesRendererJS#405]
This is a very useful tool, thank you very much ！

I have encountered a very confusing problem and hope to receive effective 

I am trying to load this model for rendering by B3DMLoader

[https://data.mars3d.cn/3dtiles/qx-shequ/tileset.json](url)

but it threw an error like the one in the title

I can load other b3dm files, and I guess it should be a problem with the file version. How can I load and render the files in the above address correctly, or how can I convert them to a format supported by 3DFilesRenderJS? Thank you again!

**Comment by gkjohnson** [comment]
The provided B3DMs have a legacy glTF 1.0 file embedded in them - which is disallowed by the 3d tiles 1.0 specification. You can see that the provided tileset uses the 3d tiles 0.0 prerelease specification which this project does not support.
