### ISSUE TITLE
Assertion is logged for 1.1 asset version

### ISSUE THREAD

**Issue by liangyuan1** [NASA-AMMOS/3DTilesRendererJS#407]
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/25976027/c414ef5b-7a02-4f2d-a5b5-23c9fd637489)

**Comment by gkjohnson** [comment]
Which asset version does your tile set use? Please provide an example file.

**Comment by liangyuan1** [comment]
[test.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/12926226/test.zip)
3dtiles next(3dtiles 1.1) 采用用cesiumlib工具转化的模型示例

**Comment by gkjohnson** [comment]
Great, thank you - would you like to make a PR that tests for a 1.x major version rather than explicitly checking for the string `"1.0"`?

**Comment by liangyuan1** [comment]
希望支持3dtiles 1.1协议的数据加载

**Comment by liangyuan1** [comment]
想问一下这本3.22版本预计什么时候发布，等待支持3dtiles(1.1)

**Comment by gkjohnson** [comment]
As I've mentioned in my previous comment - please make a Pull Request if you'd like to help fix the issue.
