### ISSUE TITLE
When should we call the “disposeTile” method

### ISSUE THREAD

**Issue by IDONKN** [NASA-AMMOS/3DTilesRendererJS#411]

**Comment by IDONKN** [comment]
When should we call the disposeTile method


At present, the engine does not seem to have used the disposeTile method. The structural data and material data contained in the loaded tile are all in the memory, resulting in memory leaks when loading large models.

What is the appropriate time to call disposeTile to release memory and ensure that the browser does not crash?

**Comment by gkjohnson** [comment]
There is not need to call disposeTile. It is done internally.

**Comment by gkjohnson** [comment]
> The structural data and material data contained in the loaded tile are all in the memory, resulting in memory leaks when loading large models.

If you believe there are memory leaks then please make an example reproduction of it. The data is unloaded once it is no longer needed based on the LRUCache settings.
