### ISSUE TITLE
Add 3D model on the ground of Google Tiles

### ISSUE THREAD

**Issue by Vovka95** [NASA-AMMOS/3DTilesRendererJS#413]
Hey all

I want to add a 3D model on top of Google 3D tiles by providing latitude and longitude. Is there some way to convert between [lat, lon] to three.js [x, y, z] position? 

I tried to use "getCartographicToPosition" and "getPositionToCartographic" but I assume there are more transformations to get the correct position on the scene.

Could someone help me with that?

**Comment by gkjohnson** [comment]
The "getCartographicToPosition" is what you need to use to get a point on the surface of the planet ellipsoid. But that won't get you a surface of the loaded geometry (the height of which will change with every tile update). You'll have to raycast or do some kind of spatial query to determine the height.

**Comment by Vovka95** [comment]
Thanks a lot

I found the solution to convert coordinates correctly. Just leave it here in case someone needs help with this kind of task.

From [lat, lon, height] to [x, y, z]
```
const positionVector = new Vector3();

tiles.ellipsoid.getCartographicToPosition(
      MathUtils.degToRad(lat),
      MathUtils.degToRad(lon),
      height,
      positionVector
);

const mat = tiles.group.matrixWorld.clone();
positionVector.applyMatrix4(mat);
```

From [x, y, z] to [lat, lon, height]

```
 const res = {};
 const intersectedPoint = getTilesIntersection(); // Vector3
 
 const mat = tiles.group.matrixWorld.clone().invert();
 const vec = intersectedPoint.applyMatrix4(mat);
 
 tiles.ellipsoid.getPositionToCartographic(vec, res);
```

**Comment by manoj-kumar-joshi** [comment]
Thank you. Is getTilesIntersection() some function you implemented?

**Comment by jellehak** [comment]
@manoj-kumar-joshi  I guess just a Vector3. I use the following:
It only return the delta what you have setup as `tiles.setLatLonToYUp`

```js
function getPositionToCartographic(point = new Vector3()) {
	const res = {};
	// const intersectedPoint = getTilesIntersection(); // Vector3
	const intersectedPoint = point.clone(); // Vector3
	
	const mat = tiles.group.matrixWorld.clone().invert();
	const vec = intersectedPoint.applyMatrix4(mat);
	
	tiles.ellipsoid.getPositionToCartographic(vec, res);
  
	return res
}
```

**Comment by Dmitrijlagutkin** [comment]
@Vovka95 
I am using exactly the same functions to convert position. I noticed some issue. There is some difference when I trying convert from (lat, lng) to Vector 3 with clicked point position in (Vector 3) which I recieved from intersects[0].point. 

```
export const radiansToDegrees = (radians: number) => radians * (180 / Math.PI)

export const getPositionToCartographic = (point = new Vector3(), tilesRendererRef: GoogleTilesRenderer | null) => {
    const res: {lat: number; lon: number; alt: number} = {lat: 0, lon: 0, alt: 0}
    if (tilesRendererRef) {
        const intersectedPoint = point.clone()

        const mat = tilesRendererRef.group.matrixWorld.clone().invert()
        const vec = intersectedPoint.applyMatrix4(mat)

        tilesRendererRef.ellipsoid.getPositionToCartographic(vec, res)

        res.lat = (res.lat * 180) / Math.PI
        res.lon = (res.lon * 180) / Math.PI
        res.alt = point.y
    }

    return {lat: res.lat, lng: res.lon, alt: res.alt}
}

export const getCartographicToVector3Position = (
    panelLocation: LocationType,
    tilesRendererRef: GoogleTilesRenderer
) => {
    const res = new Vector3()

    tilesRendererRef.ellipsoid.getCartographicToPosition(
        MathUtils.degToRad(panelLocation.lat),
        MathUtils.degToRad(panelLocation.lng),
        panelLocation?.alt ?? 0,
        res
    )

    const mat = tilesRendererRef.group.matrixWorld.clone()
    res.applyMatrix4(mat)

    return res
}
```

Here is result of calculation. It is the big difference of "x" position. Let's say It is totaly another building. Not the same as I have clicked.

```
 "intersects[0].point" = {
                **x: 8.174821130037934,**
                y: 217.5335349519556,
                z: 4.967353534559738
            }

 "getCartographicToVector3Position(location, tilesRendererRef) result" = {
                **x: 8.90003746189177,**
                y: 217.53352679591626,
                z: 4.967353033367544
            }
```
            
          Can I improve somehow accuracy. Because this difference is too big to reach success.
