### ISSUE TITLE
load and unload cesium ion assets when camera is away.

### ISSUE THREAD

**Issue by SujayAmberkar** [NASA-AMMOS/3DTilesRendererJS#414]
I uploaded a huge model to cesium ion in .obj format and converted it to 3d tiles. Then I used this library to fetch that model into my 3js scene. Everything is working fine till now, but the problem is that it takes too much memory and when I run this 3js app in my phone it crashes. How do I not load the entire model and only load few parts of that model which are near the camera and when I move away it unloads that part and loads the new part which is again closer to the camera. I tried to explain the problem as much as possible but if you need some more information please let me know.

**Comment by SujayAmberkar** [comment]
ok, I increased errorTarget and it works. Although just needed a confirmation if this is the only way or it can be optimized more?

**Comment by SujayAmberkar** [comment]
By crashing I mean this when trying to load the model on phone's browser,
![awwsnap](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/38327075/067a44a1-2585-46ed-8d5b-580c5d8d32f9)

It does load everything on PC but takes a lot of memory mostly above 90%, in the following image it was 75%
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/38327075/000693c4-3fd6-4a4f-8b00-e1682c830ba9)

I cannot say the number of geometries loaded but it's a lot so a lot of data gets downloaded when the pages loads,
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/38327075/6b741922-521a-4a1e-8d69-b6076bdd2c1b)

following is the model after it is fetch to 3js,
![Uploading image.png…]()

**Comment by gkjohnson** [comment]
You can count the geometry using some of the load and unload callback functions in the README and estimate memory usage using `estimateBytesUsed` from three.js' `BufferGeometryUtils`. Textures may be accounting for more memory than necessary, as well.

Either way it sounds like too much memory is being used for the files. You could reduce the files further using the typical approaches like gltf-transform or gltfpack.
