### ISSUE TITLE
Why raycastTraverse use `Object.getPrototypeOf(c).raycast`?

### ISSUE THREAD

**Issue by Junior2Ran** [NASA-AMMOS/3DTilesRendererJS#415]
As the code in [raycastTraverse.js](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/three/raycastTraverse.js#L20) `Object.getPrototypeOf( c ).raycast.call( c, raycaster, intersects );`

Why we use `Object.getPrototypeOf(c).raycast` rather than `c.raycast`?
Because I am facing a problem that I'm gonna deal with raycast method myself, and my way is to traverse tiles mesh and set my raycast method like `tiles.tarverse(c => c.raycast = customRaycastFunction)`.
However, it didn't work because `Object.getPrototypeOf(c).raycast` make the raycast method refers to `c.__proto__.raycast`. So is there a reason why this be set？ Or I pull a request to modify the code like `c.raycast`?

**Comment by gkjohnson** [comment]
Raycasting is handled with a custom traversal algorithm so the raycast function on each mesh is replaced with a custom one on load to avoid redundant raycasting work. It's the only way to disable raycasting on an object in three.js.

Can you explain in more detail what you're trying to do? Why do you need to replace the raycasting function?

**Comment by Junior2Ran** [comment]
First, I still cannot get it why the code is written like `Object.getPrototypeOf(c).raycast` rather than `c.raycast`. I assume that it can also work with your custom traverse raycasting design above.

In my project, 3DTiles data is BIM which is so heavy and large. Even the raycasting has been optimised, the performance is still not good. In fact, I'm gonna replace raycast function to BVH. I noticed that you are also the BVH author, is there an elegant way to deal with it?

**Comment by gkjohnson** [comment]
> First, I still cannot get it why the code is written like Object.getPrototypeOf(c).raycast rather than c.raycast. I assume that it can also work with your custom traverse raycasting design above.

As I said - I the raycasting performs custom traversal by overriding the root "raycast" function and it's required to replace the existing raycast function with an "empty" one so duplicate raycasting is not performed. The prototype raycast function is retrieved when leaf nodes are traversed to so we have the associated raycast function associated with the object type. Because we replace the original raycast function with the empty one it's no longer available.

> In my project, 3DTiles data is BIM which is so heavy and large. Even the raycasting has been optimised, the performance is still not good. In fact, I'm gonna replace raycast function to BVH. I noticed that you are also the BVH author, is there an elegant way to deal with it?

three-mesh-bvh suggests overriding the prototype of `Mesh` in the documentation which will work just fine here since the prototype is modified:

```js
Mesh.prototype.raycast = accleratedRaycast;
```

It's possible to add something that allows for more control over this but I'd like to avoid it if possible. At least this limitation should be listed in the documentation, I'd think.

**Comment by ligaofeng0901** [comment]
> three-mesh-bvh suggests overriding the prototype of `Mesh` in the documentation which will work just fine here since the prototype is modified:
> 
> ```js
> Mesh.prototype.raycast = accleratedRaycast;
> ```

I don't think this is an elegant way.

**Comment by gkjohnson** [comment]
> I don't think this is an elegant way. Using c.raycast is a better way.

I'm not interested in repeating what I've already stated previously. If there's something specific you don't understand about why the current approach is being used I'm happy to answer. But statements like this are not helpful.

> I only want to modify raycasting on some meshes, not all.

I won't be dealing with hypothetical situations. Please be specific about what function you're replacing the raycast one with and why.

The current "optimizedRaycast" and "firstHitOnly" options enabled by the overwritten raycast functions provide a 2-5x performance improvement over the naive raycast approach in some cases. And it would be even higher (4-10x or more) if there were a way to get rid of some other unnecessary three.js overhead.

**Comment by gkjohnson** [comment]
I'll close this until more information or details can be provided on the purpose. Ultimately changes need to be made in three.js to support this. Or a custom raycaster solution needs to be provided, which I don't think is an elegant solution.
