### ISSUE TITLE
Optimize Raycast path slower due to three.js overhead

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#416]
Related to https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/415#issuecomment-1809410719

When raycasting against the tileset two paths are taken - one that smartly traverses the tileset based on parent bounds and the internal three.js logic one that iterates over all tileset children that have an "empty" raycast function assigned. The latter set of tile iterations can take a significant amount of time.

When the mouse is not over the tileset it can take 0ms while the individual tile iterations can take significantly longer (0.5-1ms). And when hovering over a tile the tile iteratation can take over half the iteration time. Sometimes significantly more than half due to this three.js overhead. Some method providing more control over the raycast logic would help alleviate this.

<img width="779" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/734200/dc0cd33b-aa67-4f8e-9c3a-ae409b3f3dce">

**Comment by mrdoob** [comment]
How's the overhead now?

**Comment by gkjohnson** [comment]
From https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/546:

> Raycasting in an extreme case (close mesh, error target of 10) results in improvements from **~1.8-2.1ms** to **~0.2ms** for a raycast.

And the times in the "overhead" column of the table in https://github.com/mrdoob/three.js/issues/27702 would be gone - so it's a pretty good improvement.
