### ISSUE TITLE
Can it be used in React-three-fiber 

### ISSUE THREAD

**Issue by SujayAmberkar** [NASA-AMMOS/3DTilesRendererJS#418]
Hello there! I recently used your library to fetch 3D tiles from Cesium Ion and it worked perfectly with Three.js. However, I would like to use it with React-Three-Fiber. Could you please let me know if it is possible to use your library with React? If not, what changes would need to be made? Thank you!

**Comment by swarmt** [comment]
Hey mate! Try this https://github.com/swarmt/react-three-cesium

**Comment by SujayAmberkar** [comment]
Hey @swarmt, thank you for your help. I managed to modify the code you provided to fetch data from Cesium ion using the asset id and access token. However, when I tried to view the scene, I didn't see anything. I checked the "tiles.group" property and found an array of around 300 tilesets, but none of them were active.  You can check out the modified code here https://codesandbox.io/p/sandbox/cold-shadow-4hwl9s?file=%2Fsrc%2FApp.js%3A4%2C29
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/38327075/6481a12c-ee89-4187-985c-51287dd4dd78)
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/38327075/2107faab-41d8-48e3-a5a1-e58f11f2fcd1)

**Comment by swarmt** [comment]
They might be out of view somewhere. I suggest is to follow the transformations as closely as you can from [this example](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/ionExample.js)

Are they draco compressed?

**Comment by SujayAmberkar** [comment]
I managed to fix the issue. The problem was that I forgot to set the transformations in the onLoadTileSet() function. Additionally, I had not taken care of the Draco compression. Now everything is working perfectly fine. You can check the same sandbox link to confirm. Thank you very much for your help, @swarmt. 
Closing the issue.
