### ISSUE TITLE
Tiles are traversed and queued in depth-first order causing shallow tiles to not load when cache is full 

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#428]
<img width="1741" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/734200/5e60a288-c559-4773-ad57-4ed1d27b583c">

<img width="1722" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/734200/42dad4fd-2287-4a2e-a9e4-60c179b2c657">

Possibly only happening when camera is near or inside a tile? Or on reload of the tileset?

**Comment by gkjohnson** [comment]
Necessary settings:

- target error: 2
- threshold: 1000
- side: -Z
- maxDepth: 9+

**Comment by gkjohnson** [comment]
The tile isn't being queued because the cache is full. Since tiles are traversed in a depth-first order the children of other tiles fill up the cache first causing the next shallow parent tile to fail to queue.

This is a less likely scenario to encounter if the cache is set up appropriately but two option for avoiding this in a more streamlined manner are to traversed in a breadth-first manner for traversals that queue loads or accumulate tiles that need to be loaded, sort them by priority, and then queue.

**Comment by jo-chemla** [comment]
Quick question following merge of PR https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/723

Would you agree to say that tiles are now neither loaded depth-first nor breadth-first given all the different properties used for evaluation of the [priorityCallback](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/b98051a3ede719ad8b7c1833636de2ad7a2ee65b/src/base/TilesRendererBase.js#L11) and the if-cascade?

**Comment by gkjohnson** [comment]
> Would you agree to say that tiles are now neither loaded depth-first nor breadth-first given all the different properties used for evaluation of the [priorityCallback](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/b98051a3ede719ad8b7c1833636de2ad7a2ee65b/src/base/TilesRendererBase.js#L11) and the if-cascade?

Tiles were never loaded depth-first - they were always sorted by the priority queue before triggering a fetch. Rather they were added to the _queue_ depth-first but the queue would reject them if it was "full", meaning that some tiles would be rejected even if they would technically be fetched with a higher priority based on the priority function.

The priority function also includes a test for [depth in the hierarchy](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/b98051a3ede719ad8b7c1833636de2ad7a2ee65b/src/base/TilesRendererBase.js#L13) and prioritizes shallower tiles to load first - so to an extent it's breadth-first loading (and always has been).

I guess the answer depends on what the purpose of the question is.
