### ISSUE TITLE
The 3D Tiles Renderer VR Example fails to start in VR

### ISSUE THREAD

**Issue by epaulson** [NASA-AMMOS/3DTilesRendererJS#459]
**Describe the bug**

The VR example from the README fails to start when you try to enter an immersive VR session.
**To Reproduce**

1. Go to https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/vr.html
2. Click on 'Enter VR'
3. See error

```
[Immersive Web Emulator] native WebXR API successfully overridden
webxr-polyfill.js:4455 The optional feature 'bounded-floor' is not supported
webxr-polyfill.js:4455 The optional feature 'layers' is not supported
webxr-polyfill.js:3169 TypeError: Cannot read properties of undefined (reading 'cameras')
    at A (vr.js:249:29)
    at S (vr.js:313:2)
    at three.module.js:26918:36
    at Object.i [as callback] (three.module.js:13333:3)
    at XRSession$1.<computed>.onDeviceFrame (webxr-polyfill.js:3166:28)
XRSession$1.<computed>.onDeviceFrame @ webxr-polyfill.js:3169
requestAnimationFrame (async)
requestAnimationFrame @ webxr-polyfill.js:28307
XRSession$1.<computed>.startDeviceFrameLoop @ webxr-polyfill.js:3178
XRSession$1 @ webxr-polyfill.js:3252
requestSession @ webxr-polyfill.js:4461
await in requestSession (async)
CustomWebXRPolyfill.XRSystem.requestSession @ webxr-polyfill.js:33626
o.onclick @ VRButton.js:66
Show 1 more frame
Show less
```

<img width="612" alt="Screenshot 2024-01-17 at 4 47 12 PM" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/315267/ab897837-1153-43d5-8030-16a0764620de">

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome]

I have the Meta Immersive Web Emulator installed in Chrome as an add-on. This example also fails when I tried it in my Quest Pro using the Quest browser - it loads OK in 2D but when I press 'Enter VR' it just displays the 3 little loading circles, I'm not sure how to get the Javascript Console in that setup to see what's going on.

**Comment by gkjohnson** [comment]
Thanks for the report.

> I'm not sure how to get the Javascript Console in that setup to see what's going on.

Some articles come up pretty quickly when searching for how to do this. Can you provide a console log from the device to help understand what's happening?

**Comment by pizza3** [comment]
I think it should work on updating to three r154, there is a revert commit for getCamera method ([link](https://github.com/mrdoob/three.js/releases/tag/r154)) which should fix this or maybe updateCameraXR should also work ?

**Comment by gkjohnson** [comment]
Great! Thank you. It would be great to have a PR upgrading the three.js version

**Comment by gkjohnson** [comment]
@epaulson if you could try again to confirm the VR demo works that would be great
