### ISSUE TITLE
What does "tiles" refer to in "const loader = new GLTFLoader( tiles.manager );" (DRACOLoader)

### ISSUE THREAD

**Issue by rvouilloz** [NASA-AMMOS/3DTilesRendererJS#479]
Hello,
Thanks a lot for this development! I managed to make it work locally with your 3D tiles model. Now I'm trying to replace it with my own model exported from Metashape.
The structure is a bit different: in the parent folder, I have a tileset.json and a Data folder. In this folder, I have five different .b3dm files (a, b0, b1, b2, b3) and 21 cxx folders. In each of these folders, a lot of .b3dm files and a tileset.json file.

According to the errors I've been getting, I guess I need a DRACOLoader to read my model. Following your code, I get the following error: 
`Uncaught ReferenceError: tiles is not defined`
in this line : 
`const loader = new GLTFLoader( tiles.manager );`

What does "tiles" refer to?

**Comment by gkjohnson** [comment]
"tiles" refers to the tiles renderer instance but I see that in the small snippet the renderer is declared afterward and named differently. Would you like to make a PR to update the documentation?

**Comment by rvouilloz** [comment]
thanks that's perfect now it's working! Sure I'll do the PR
