### ISSUE TITLE
DebugTilesPlugin: improve "init extremes" performance

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#484]
When a new child tileset is loaded the whole hierarchy is loaded which can take 40+ ms in some cases especially with complex tilesets like google tiles, causing a jerkiness when new tiles are loaded in.

Options:
- Derive extremes only from currently visible tilesets
- Take the max of the current extreme and any newly added tileset

**Comment by sguimmara** [comment]
I didn't see this issue, but it might be obsolete now with #885

**Comment by gkjohnson** [comment]
I think it is!
