### ISSUE TITLE
Tiles disappear when zooming in too quickly

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#51]
This is because of the `skipTraversal` step. Instead we should continue to render a parent if it was already rendered and children haven't full loaded, yet. Sort of the inverse of #29.

**Comment by gkjohnson** [comment]
After looking into this a bit more this may be a slightly more complicated addition to the rendering algorithm.

We want to check if _all_ used visible children have already loaded and if not then render the currently visible parent that was visible last frame. If there wasn't one visible last frame then we just traverse to the children and load them as usual.

However the hiccup is that the next used / visible children should _just_ kick off their load if they haven't loaded and _not_ be marked as visible because the previously visible parent is to be used until all the visible children have loaded. This means that if it is detected that a parent is going to render until all children have rendered then something like a flag needs to be passed down to prevent children from being marked as visible for that frame. The check would be performed again the next frame.

**Comment by dbuck** [comment]
I'm running into this problem with my tilesets. It can be pretty jarring to have large chunks of the scan disappearing during initial load in the time between starting to load the more detailed level being ready to render.

Are there any mitigations that can be done currently?

I'll need to look into this in order to pursue using the package much more, did you have any change to the preferred way to address the issue?

**Comment by gkjohnson** [comment]
This was on my list of things to look into next because I've noticed it with a couple of our tile sets. Can you give a bit more information on how you're configuring the renderer?

> Are there any mitigations that can be done currently?

I believe this is related to the `errorThreshold` value which works by only loading tiles that are within some range of the current error target. For example if you're zoomed in close to the ground then parent tiles won't load and you can load the child tiles closer to your error target sooner. Of course if you zoom out really quickly you'll be at a point where the error target dictates that the parent tiles that were never loaded should be rendered causing the flash you see. So keeping the `errorThreshold` option set to `Infinity` should mitigate the problem in this case. That's what I believe is going on, at least, and in my quick test updating `errorThreshold` seemed to fix it.

I'm trying to think if there's an approach to get the best of both worlds. Possibly we could load the "skipped" parent tiles with a low priority so at least they could _start_ loading but you might still get the flicker if the parents hadn't loaded by the time you zoom out.

The original intent behind `errorThreshold` was to enable loading the higher resolution data sooner particularly for cases where there wouldn't be dramatic camera movement. Can you see if setting `errorThreshold` to `Infinity` removes the issue in your case (if it's not already)? If it does then it might just be worth updating the docs for now.

**Comment by dbuck** [comment]
> Keeping the errorThreshold option set to Infinity should mitigate the problem in this case.

Ahh, thank you, that was not immediately clear what errorThreshold did, setting it back to Infinity works how I'd expect !

I started from the ionExample, I think having the errorThreshold in the dat.gui params ended up with a range where it didn't make sense

**Comment by gkjohnson** [comment]
> Ahh, thank you, that was not immediately clear what errorThreshold did, setting it back to Infinity works how I'd expect !

I'll update the documentation when I get a chance to make it more clear. Considering setting it to Infinity fixes it and the other behavior I mentioned above I'm thinking it makes sense to close this issue and just document that the option is intended for cases where the camera will not be moving too dramatically. Does that sound reasonable?

**Comment by dbuck** [comment]
Sounds reasonable to me!

We may want to either try to explain the correlation between model size (in meters), geometric error values, and error target / threshold values, or tweak the demo scripts which include the gui clamping and default errorThreshold of 60?

That seems like it*may* reduce some other chances for User Error™️. It's *very* possible to be that my WAG at geometricError is not correct/useful for my 'house' scale tilesets, when compared with your 'crater' scale tilesets ;)

**Comment by gkjohnson** [comment]
I've updated the README [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/commit/5935fa9d55aea22b2a5c07eeef1473185a10fcdd) to reference the 3d tiles docs on geometric error and note some of the caveats of the setting a bit more. Let me know you have other suggestions.

> tweak the demo scripts which include the gui clamping and default errorThreshold of 60?

It's a good point. It would be nice if the demos started with the same values that TilesRenderer defaults to. Perhaps a checkbox that forces the errorThreshold to Infinity that defaults to true?

> It's very possible to be that my WAG at geometricError is not correct/useful for my 'house' scale tilesets

Are you manually generating your own 3d tiles data? I had understood the geometric error to be the maximum distance in meters from the simplified representation to the original geometry.

Thanks again for bringing up your issues!
