### ISSUE TITLE
disposeTile is sometimes unable to clean up tile resources

### ISSUE THREAD

**Issue by JackXie60** [NASA-AMMOS/3DTilesRendererJS#510]
LRUCache starts to dispose the tiles
```js
  for ( let i = 0, l = geometry.length; i < l; i ++ ) {
  
      geometry[ i ].dispose();
  
  }
  
  for ( let i = 0, l = materials.length; i < l; i ++ ) {
  
      materials[ i ].dispose();
  
  }

  for ( let i = 0, l = textures.length; i < l; i ++ ) {
  
      const texture = textures[ i ];
      
      if ( texture.image instanceof ImageBitmap ) {
      
	      texture.image.close();
      
      }
  
      texture.dispose();
  
  }
```
Cleaning up geometry, material, and texture with the above code looks good, but I found that I was loading large 3dtiles with memory that kept increasing and LRUCache's caching strategy seemed to fail.

<img width="566" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/74998838/f34c5a4a-5fa9-4199-adab-821bbf33983f">

**geometry.dispose ()** will call **onGeometryDispose** to clean the geometry contents, but this function will not be registered on the geometry if the mesh is not added (or was added) to the scene,because it traverses the object below the scene, gets the geometry of the object and then binds onGeometryDispose.
 Many tiles will not register **onGeometryDispose** after loading because the camera position has moved, and nothing will happen when the dispose function is called

 
![1](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/74998838/d65f5ac6-866d-4f95-aa61-a48416ec7eb3)

**Comment by gkjohnson** [comment]
The three.js `onDispose` function is only added once a tile has been rendered and there are WebGL resources to dispose of. It is not a problem if it has not been added.

You'll have provide a more concrete example of a memory leak or show where dangling references are left once a tile has been disposed. Javascript is a garbage collected language so it's expected that resource usage goes up until the GC runs.
