### ISSUE TITLE
Metashape generated 3d tiles

### ISSUE THREAD

**Issue by sau0409** [NASA-AMMOS/3DTilesRendererJS#520]
Hi,

I am trying to load 3d tiles generated through Agisoft Metashape. Tiles are loading properly. But the model position is  {
    "x": -4187813.326841842,
    "y": -828961.7326518039,
    "z": -4723778.720413422
}

Is there a way I can translate or transform model to 0,0,0. 

![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/64318068/eb9a7b77-1569-4865-bada-2c8cfff6957f)

**Comment by gkjohnson** [comment]
See https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/395 and https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/506.

The example code shows how center a tileset [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/1ce1070f38dfa3dc0e87f7d93343bf66924dbeab/example/index.js#L540-L551) but as mentioned in https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/395 I'd be open to adding a function to simplify the process of centering a tileset if you'd like to make a suggestion and make a PR.
