### ISSUE TITLE
Is it possible to render NRRD format in the 3d tile structure?

### ISSUE THREAD

**Issue by tomhsiao1260** [NASA-AMMOS/3DTilesRendererJS#521]
Hi, Garrett Johnson

I've made a box which is rendered via NRRD format. Something looks like this one:
https://threejs.org/examples/webgl_loader_nrrd.html

I have multiple boxes like this which is in a BVH structure (e.g. a series of boundingData, splitAxis, offset, count, ... etc). Is it possible to render all of them with the help of this repo? If not, any recommend way to achieve this? (In the worse case, it's fine for me to write all of them from the bottom up if necessary)

Thanks!

**Comment by gkjohnson** [comment]
Unfortunately it's not possible to just render anything with hierarchical bounds with the project. The renderer requires a tile set in the [3d tiles format](https://github.com/CesiumGS/3d-tiles). It would likely be possible to convert such a structure to 3d tiles (either offline or on load) but the format really requires having varying levels of detail at each level of the hierarchy. Perhaps there are tools out there for converting large point cloud sets to 3d tiles but I don't have any I can recommend.

But either way - the scope of this project is rendering 3d tiles files specifically and there's no straight forward or supported way to rig it to render other structures even if they're similar.
