### ISSUE TITLE
Is version 1.1 not supported by anything?

### ISSUE THREAD

**Issue by bbhxwl** [NASA-AMMOS/3DTilesRendererJS#542]
I have a LOD, version 1.1 3D tiles file that cannot be loaded, there are no errors, only warnings.

 
tiles versions at 1.1 or higher have limited support. Some new extensions and features may not be supported.

**Comment by pgzmnk** [comment]
What's the status on 1.1? @bbhxwl

**Comment by gkjohnson** [comment]
The list of unsupported 1.1 features is in #235 - though "implicit tiles" is mostly supported, now.
