### ISSUE TITLE
The issue with testing by Jest

### ISSUE THREAD

**Issue by volodymyrprotskiy** [NASA-AMMOS/3DTilesRendererJS#560]
The issue occurs when running jest test, is there someway to fix this issue.

 Details:

    /node_modules/3d-tiles-renderer/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './three/DebugTilesRenderer.js';

    SyntaxError: Unexpected token 'export'

**Comment by gkjohnson** [comment]
This is an issue with Jest - you'll have to look into how to configure Jest to run with es6 modules.
