### ISSUE TITLE
GoogleTilesRenderer get all needed tiles loaded status

### ISSUE THREAD

**Issue by volodymyrprotskiy** [NASA-AMMOS/3DTilesRendererJS#563]
I use GoogleTilesRenderer class to render specific locations. 

Is there any way to detect when all needed tiles are loaded?

**Comment by gkjohnson** [comment]
This isn't possible yet but I'd be happy to see it added - see #389, #522. PR #440 implements this but has not been able to be merged, yet. If you'd like to make a PR I'm happy to help guide how this can be added.

I'll close this as a duplicate of #389 for now, though.
