### ISSUE TITLE
Cannot assign to "i" because it is a constant

### ISSUE THREAD

**Issue by bbhxwl** [NASA-AMMOS/3DTilesRendererJS#578]
<img width="1062" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/26525599/417242a2-af3e-45b6-8a2a-2676d5ce513a">
<img width="1051" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/26525599/3afaff4e-41be-4605-9903-d3e44dfaca36">
<img width="1179" alt="image" src="https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/26525599/0995512d-b3a2-481b-bcb3-39843d2c0c4a">

**Comment by gkjohnson** [comment]
Fixed in #576
