### ISSUE TITLE
Only JSON file loaded, no 3D model file loaded，Please help me take a look

### ISSUE THREAD

**Issue by zhu-gang** [NASA-AMMOS/3DTilesRendererJS#593]
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/36910489/974954db-393a-44fa-b0e7-5e9248e0f0e4)

here is my code:
function load3Dtitle() {
	// let url = '/model/3dtitle-20240626-1/tileset.json'
	// let url = '/model/fbx/tileset.json'
	// let url = '/model/data/tileset.json'
	let url = '/model/fbx-title/tileset.json'
	const tilesRenderer = new TilesRenderer(url);
	tilesRenderer.setCamera(camera);
	tilesRenderer.setResolutionFromRenderer(camera, renderer);
	tilesRenderer.addEventListener( 'load-tile-set', () => {
		// optionally center the tile set in case it's far off center
		const sphere = new THREE.Sphere();
		tilesRenderer.getBoundingSphere( sphere );
		tilesRenderer.position.copy( sphere.center ).multiplyScalar( - 1 );
	} );
	tilesRenderer.onLoadModel = function ( scene ) {
		// create a custom material for the tile
		// console.log(scene)
		// scene.traverse( c => {
		// 	if ( c.material ) {
		// 		c.originalMaterial = c.material;
		// 		c.material = new MeshBasicMaterial();
		// 	}
		// } );
	};
	tilesRenderer.onDisposeModel = function ( scene ) {
		// dispose of any manually created materials
		scene.traverse( c => {
			if ( c.material ) {
				c.material.dispose();
			}
		} );
	};
	scene.add(tilesRenderer.group);
	renderLoop()
	function renderLoop() {
		requestAnimationFrame(renderLoop);
		// The camera matrix is expected to be up to date
		// before calling tilesRenderer.update
		camera.updateMatrixWorld();
		tilesRenderer.update();
		renderer.render(scene, camera);
	}
}
[fbx-title.zip](https://github.com/user-attachments/files/16015787/fbx-title.zip)

Below is the error message：
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/36910489/4889100c-409f-48e3-8041-23642977bb19)
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/36910489/b94c1962-c58e-4920-9658-056fa1bf0f16)

**Comment by gkjohnson** [comment]
There is no `tilesRenderer.position` property - I see there is a mistake in the documentation. This line should be

```js
tilesRenderer.group.position.copy( sphere.center ).multiplyScalar( - 1 );
```

I've updated the docs in 2e0c4e0. Thanks for the report!
