### ISSUE TITLE
[Batch table] implement a method to get data for a batch `ID`

### ISSUE THREAD

**Issue by mgermerie** [NASA-AMMOS/3DTilesRendererJS#595]
**Is your feature request related to a problem? Please describe.**

Hi, thanks for this awesome library ! I'm currently working on using it to render 3d tiles data in [iTowns](https://github.com/iTowns/itowns) which is a geographic data visualization framework. I am more specifically working on batch tables at the moment.

In our previous implementation, we had a method that read all data in a batch table for a given batch `ID`, whether those data are stored directly in the batch table or using [`3DTILES_batch_table_hierarchy`](https://github.com/CesiumGS/3d-tiles/blob/main/extensions/3DTILES_batch_table_hierarchy/README.md) extension.

If you would be willing, I wish to implement such a method in your library.

**Describe alternatives you've considered**

The [`BatchTable`](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/70ae645ebb1b76b6dd1153818af20f8199d7810f/src/utilities/FeatureTable.js#L153) you already implemented provides properties and methods which allow users to implement such a method on their side. However, I considered two elements on that idea. 

- The first is that such a method could perhaps be useful to other users than us, though I admit I didn't investigate on this matter.
- Moreover, reading all entries in a binary batch table for a given batch `ID` with your [`BatchTable.getData`](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/70ae645ebb1b76b6dd1153818af20f8199d7810f/src/utilities/FeatureTable.js#L162) method requires parsing the whole binary batch table when we could just parse the buffer part corresponding to the batch `ID`. I think this is an optimization issue, especially when dealing with a large number of batches.

**Describe the solution you'd like**

I propose to implement a `getDataForBatchId` method in [`BatchTable`](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/70ae645ebb1b76b6dd1153818af20f8199d7810f/src/utilities/FeatureTable.js#L153) (the name is just a suggestion) which, for a given `batchID` parameter, would return an object as such : 

```js
{
    batchTableProperty1: value1,
    batchTableProperty2: value2,
    // ...All other properties in the batch table
    extensions: {
        3DTILES_batch_table_hierarchy: {
            className1: { ...valuesForClass1Properties },
            className2: { ...valuesForClass2Properties },
            // ...All other classes in the extension of the batch table
        },
    },
}
```

Would the idea of implementing such a method suit you ?

**Comment by gkjohnson** [comment]
Hello! I think adding such a function is a good addition. I'm imagining the API looking like so:

```js
batchTable.getDataForId( id, target = {} );
```

The `target` object is the object to set all values on so garbage creation can be avoided.

 > ```js
> extensions: {
>        3DTILES_batch_table_hierarchy: {
>            className1: { ...valuesForClass1Properties },
>            className2: { ...valuesForClass2Properties },
>            // ...All other classes in the extension of the batch table
>        },
>    },
> ```

Can you explain this? I'm not understanding why we would return the list of extensions on every result. These extensions should be retrieved from the batch table directly if needed, I think.

> Moreover, reading all entries in a binary batch table for a given batch ID with your [BatchTable.getData](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/70ae645ebb1b76b6dd1153818af20f8199d7810f/src/utilities/FeatureTable.js#L162) method requires parsing the whole binary batch table when we could just parse the buffer part corresponding to the batch ID

Just a note that the [getData function](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/70ae645ebb1b76b6dd1153818af20f8199d7810f/src/utilities/FeatureTable.js#L32-L142) is not doing anything complicated per call. The overhead should be very low beyond creating a new array buffer typed array wrapper instance. These could be cached if needed, though.

**Comment by mgermerie** [comment]
Hi ! Thanks for your response and sorry for the late answer.

> The target object is the object to set all values on so garbage creation can be avoided.

Noted, I'll implement it with that in mind.

> Can you explain this? I'm not understanding why we would return the list of extensions on every result. These extensions should be retrieved from the batch table directly if needed, I think.

I simply suggested a structure that followed batch table support in iTowns, without questioning it ^^. As you say, it would indeed be simpler to have an object for the extension directly returned from the batch table.

> Just a note that the [getData function](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/70ae645ebb1b76b6dd1153818af20f8199d7810f/src/utilities/FeatureTable.js#L32-L142) is not doing anything complicated per call. The overhead should be very low beyond creating a new array buffer typed array wrapper instance. These could be cached if needed, though.

Okay, if that's good for you I agree to simply use the result of `getData` for now and propose another PR to cache its results later if performance drops with large batch tables (I'll try to benchmark it).

**Comment by gkjohnson** [comment]
All sounds good to me. If you'd like to make a PR to add `getDataForId( id, target )` so you can more easily get the full set of data associated with an id I'm open to that. It would align the class more closely to the new metadata extension APIs that return all data from a class schema based on an [id](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/PLUGINS.md#getpropertyattributedata) (or [barycoord / triangle](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/PLUGINS.md#getpropertytexturedata)):
