### ISSUE TITLE
DebugTilesPlugin: Add option for enabling / disabling plugin to toggle performance

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#647]
The traversal and updates of the fields and objects in debug plugin can cause some hiccups and slowness. It would be nice to be able to disable the function of the plugin so it doesn't impact performance. Things like tile updates can be deferred until their needed in the update function which can be paused for performance.

**Comment by sguimmara** [comment]
I'm interested in working on this if nobody else is currently doing so
