### ISSUE TITLE
Add example to demonstrate batch table use

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#68]
For all model loader types

**Comment by liberostelios** [comment]
If it's useful, we could provide an example dataset of `b3dm` files with on batch attribute.

**Comment by gkjohnson** [comment]
I have a small example that uses some data from the 3d tiles example repo [here](https://nasa-ammos.github.io/3DTilesRendererJS/example/bundle/b3dmExample.html). It demos an example shader showing how to highlight individual pieces of a model based on batchid when you hover over the model:

https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/243cfb192461d0ce7c57b06420261af3e8969f8b/example/b3dmExample.js#L163-L173

I think the only thing left for this issue is to log one of the fields of the batch table on hover in the same function to show to read the batch id and associated date.

New data is always fun, though -- what kind of data can you share?

**Comment by liberostelios** [comment]
We have an export of our 3D generated buildings from the Hague (Netherlands) which has also one attribute (basically, its id with respect to the Dutch cadastre registry). It's not anything sophisticated, but if you think it would be useful for an example we are happy to share.

**Comment by gkjohnson** [comment]
If you want attach it as a zip in this issue and I'll take a look at it -- it's always good to have more data to test against!

**Comment by liberostelios** [comment]
You can find the zip [here](https://godzilla.bk.tudelft.nl/3dtiles/denhaag.zip) (sorry, too big to upload it in here).

There are two tilesets:
- `tileset.json` is the one with a flat hierarchy, and
- `tileset1.json` is the one that has an extra "layer" of empty tiles on-top of them.
