### ISSUE TITLE
src/base/TilesRendererBase.d.ts is missing type declaration for registerPlugin function

### ISSUE THREAD

**Issue by jesse-small** [NASA-AMMOS/3DTilesRendererJS#711]
**Describe the bug**

The new method to registerPlugin is not provided in the type definition for TilesRendererBase so it won't work when using TypeScript. I am not sure if there are other missing types or not from the type definition files with the recent changes.

**Comment by gkjohnson** [comment]
Thanks! Can you make a PR with the addition?

**Comment by jesse-small** [comment]
I have created the PR here https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/718
