### ISSUE TITLE
ImplicitTiling looping request

### ISSUE THREAD

**Issue by AnthonyGlt** [NASA-AMMOS/3DTilesRendererJS#728]
When I load this link https://storage.googleapis.com/ahp-research/projects/sogelink/hackathon/bdnb/sampleset/tileset.json which has implicitTiling
The data is loading as expected but once everything is loaded, the `0_0_0.subtree` is fetched again and provoking errors
Maybe it's caused by one of [the implementations left todo](https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/608#issuecomment-2283364305) but I don't see which one it could be

**To Reproduce**

- I've used the file `example/index.js` to load the link
- I've replaced 
 `geospatialRotationParent.scale.set( 1, 1, 1 );` by `geospatialRotationParent.scale.set( 0.01, 0.01, 0.01 );` because the dataset is big
- I've set `errorTarget` & `errorThreshold` at `0` + checked `displayRegionBounds`
 ![Screenshot from 2024-08-29 09-59-06](https://github.com/user-attachments/assets/68a78fc5-c793-4db2-9219-8d45a861c547)
- Zoom out  

**Screenshots**
![Screenshot from 2024-08-29 09-58-51](https://github.com/user-attachments/assets/aee1e6fe-bedb-48d0-af1a-f4f1bd49c97e)

![Screenshot from 2024-08-29 10-00-03](https://github.com/user-attachments/assets/b257b594-d9c7-48b8-a5d8-944915fd6a0e)

**Comment by gkjohnson** [comment]
The positioning of the tile set in the index example is a bit odd 😅 Maybe the automatic positioning logic could be improved. But I was able to get it in frame once and wasn't seeing any errors so this may need a more succinct repro.

**Comment by gkjohnson** [comment]
I see it now - I think this is related to #726 which I noticed last week. The LRUCache unload behavior isn't working correctly so I need to spend some time this next week figuring out what's going on. Setting the error target to 0 causes the buggy lru cache behavior to kick in.

Also I see that this tile set has two extremely far clusters of tiles making it difficult to see the extent / find the geometry:

<img width="565" alt="image" src="https://github.com/user-attachments/assets/bab2c2fa-f784-4658-a45b-e0da355d6874">

Adding a new debug settings to display parent tile bounds (Both empty and not empty) would make tile sets like this easier to understand.

**Comment by gkjohnson** [comment]
@AnthonyGlt do you mind retrying your test? The issue should have been fixed in #726, #727.

**Comment by AnthonyGlt** [comment]
Yes it got fixed, well done ! :D
