### ISSUE TITLE
DebugTilesPlugin: Add support for displaying parent bounds

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#730]
Can be added efficiently without significant performance impact by traversing the ancestors when making the tile visible, adding all parent bounds, and then incrementing a reference counter per parent tile. When a tile is hidden the reference counter for each ancestor can be decremented and if it reaches 0 then the parent bounds can be removed.

**Comment by gkjohnson** [comment]
cc @sguimmara I'm not sure if this debug feature is interesting for you since you're working in that plugin.

**Comment by sguimmara** [comment]
@gkjohnson  I could look into it but I don't really understand what the issue is wanting to do...

**Comment by gkjohnson** [comment]
Sorry it's unclear - right now only "leaf tile" bounds are displayed when toggling them:

<img width="450" alt="image" src="https://github.com/user-attachments/assets/c2e24523-adfe-4a2c-bb51-1de75c549fe3" />

Of course the parent tiles also have bounds that encapsulate all the child bounds that must be in the frustum before the leaves are displayed. So this issue is about adding an option to display the parent bounds of all the visible leaf tiles in addition to the leaf bounds. Hopefully that's more clear.

**Comment by sguimmara** [comment]
> Sorry it's unclear - right now only "leaf tile" bounds are displayed when toggling them:
> 
> <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/734200/397961295-c2e24523-adfe-4a2c-bb51-1de75c549fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTc4NzAsIm5iZiI6MTczNDg1NzU3MCwicGF0aCI6Ii83MzQyMDAvMzk3OTYxMjk1LWMyZTI0NTIzLWFkZmUtNGEyYy1iYjUxLTFkZTc1YzU0OWZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwODUyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTQwY2M3OGM1YWVlOTQ4OWY0NjM5MjY0OGNlNzU2MDkyYjU0NzA5MjU0NzE2ODcwZWM0YmJiMTY0NzFlMTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uh_Hnv1sgTdnDYdZGXxs0wpNozuPmNnwCtkGQMck6Ic">
> Of course the parent tiles also have bounds that encapsulate all the child bounds that must be in the frustum before the leaves are displayed. So this issue is about adding an option to display the parent bounds of all the visible leaf tiles in addition to the leaf bounds. Hopefully that's more clear.

Yes much clearer thanks :) I guess that the non-leaf bounds should be displayed in a way that make them clearly identifiable as such, maybe with dotted lines or a different color/line thickness. I'll have a try
