### ISSUE TITLE
Quality difference between Google 3D Photorealistic Tiles and Google Maps

### ISSUE THREAD

**Issue by RodrigoHamuy** [NASA-AMMOS/3DTilesRendererJS#747]
This may just be a limitation of what Google offers, but just wanted to make sure!

Is Google not including the best quality 3D models in their API and keeping it only in their Google Maps web/app product?

Or is it just a setting that we are missing? Seems like 3D models may be the same, but the textures are crispier.

Example: Trafalgar Square (`tiles.setLatLonToYUp(51.507500 * MathUtils.DEG2RAD, -0.128100 * MathUtils.DEG2RAD);`)

Using `3DTilesRendererJS` (without `TileCompressionPlugin`):

![image](https://github.com/user-attachments/assets/14290837-a53a-4992-8c35-2910cd397336)

Using Google Maps website:

![image](https://github.com/user-attachments/assets/8d829c32-f5ff-4932-ba33-b85e579cb265)

**Comment by lilleyse** [comment]
> Is Google not including the best quality 3D models in their API and keeping it only in their Google Maps web/app product?

Correct, one level of detail isn’t included in Photorealistic 3D Tiles.

CC https://community.cesium.com/t/google-tiles-in-cesium-less-detailed-than-google-earth/26721

**Comment by RodrigoHamuy** [comment]
Thanks @gkjohnson , @lilleyse . Added a ticket in Google Support page as suggested in Cesium forum, hope they include the extra level of detail at some point!

https://issuetracker.google.com/issues/367297521
