### ISSUE TITLE
Consolidate "credits" handling

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#775]
Related to #771 

Ion assets provide credits via the initial request while Google tiles (and others?) may include credits in the tile geometry itself.

**Comment by jo-chemla** [comment]
It seems that for google, the tile geometry embeds a reference to a provider, and that provider has metadata listed by the original dbRoot request, stored in a property `dbRoot.providerInfo[idx].copyrightString.value` as shown here in cesium: [CesiumGS/cesium/.../GoogleEarthEnterpriseMetadata.js](https://github.com/CesiumGS/cesium/blob/baaabaa49058067c855ad050be73a9cdfe9b6ac7/packages/engine/Source/Core/GoogleEarthEnterpriseMetadata.js#L579-L587)

Using this [google cesium](https://sandcastle.cesium.com/#c=dVNNb9swDP0rRLCDC6SKHdtxvKXFirTYDh0arMVOPlSx2ESoLAWSkiwr8t9Hf6RNvy6CRfI9Pj2TpdHOw0biFi2cgcYtTNHJdcX+NLGg6JXNfWq051KjLXp9eCo0gJcVKop8hQeuHPbrGNey4l4afRx0JWr8ZQTOZPmI9jg15w6v+Q7t+9RgAHdLhIUycwRh0IE2ngSiAG+gjkm3UoQVh3IndYngCTRbGm8sciWdlyXEl3AnFTFQgVoLqkFr6TE1ruF/6bs/+VZQnNiuNJ8rBItaoJV60RC7x12hW7dY8yxGkQtfGbdaoqXb0mzJRm/XeOC5EOIzPYX2dteaWTb/wddR9MTAt1z6w68oCerxhzELha+p4su7FhLUuuFA0OiYWhTSuxt9S3jUL7IAXr1gZWUlvdygY1yIoKOo+fZQcl8uISC7jD15UWoUMmUWwf1VnQBluKgd+sz2g6oa/uWpIdvfNw06j2ZGat8YXPIKLQfe3tonrxT+feN6W8aItB7ToBEmkLrqbvqOBnnKracvruOgLgM4HY7yOMszlqZROAqTLOt3iWSYZ1GcsjTKwjzJhmmXiMdpkoUhy+hMoiQeJU3ipDmNlUi78a7vT2xcmUmy8LdRquuesFGahtQ4H6ZRlOfPTU5DNhyP4nGe0BnF43E86jIRi9NRlJHUYZplcZTFeJo9K6CRhV6/N3F+p/C8RQB8l9XKWA9rqwLGBh4rWhbyYTBf06Z5VjrXjgzAZHAMnQi5ASnOPlh8KBV3jjIPa6Vu5T8seueTAdW/g3YTcbNBSytaly2j8+s2yBibDOj6MdIbo+bcvmH+Dw) sandcastle with `tileset.showCreditsOnScreen = true;`, it seems that credits are correctly attributed, for vexcel over sydney, airbus over paris (in addition to NASA, ESA, CNES, USGS & co).

**Comment by jo-chemla** [comment]
I think I've mixed up credits attribution parsing for the google terrain/imagery providers vs for the google photorealistic 3d-tiles 3dtiles tileset. I've already encountered this dbRoot.v5 when trying to add support for historical imagery in cesium GoogleEarthEnterpriseImageryProvider, shown in [this issue](https://github.com/CesiumGS/cesium/issues/12089), which calls http://kh.google.com/dbRoot.v5 but is not openly documented. 

Again, probably a great esign idea to have these credits populated by the auth or provider plugin.

**Comment by gkjohnson** [comment]
Oh I didn't realize this was a thing. If you'd like to open up a new issue here with a description of what this is for and to add support I might be open to a contribution for it.

**Comment by jo-chemla** [comment]
This dbRoot Google Earth Entreprise thing is really completely different from OGC 3D-Tiles, pretty closed format reverse-engineered + api-documented by Cesium team, so this is probably out-of-scope. 

But I sincerely hope that at some point, one can fetch historical satellite imagery the same way Google earth software (+ soon on the [GE web](https://blog.google/products/earth/3-imagery-updates-to-google-earth-and-maps/) version) does, outside of the google ecosystem, be it via a pure-js lib solution or other wrappers.
