### ISSUE TITLE
Deprecate and remove the GooglePhotorealisticTilesRenderer

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#778]
Open questions:
- Where should the other default settings be assigned? In the plugin?
- Should the plugin also handle the tiles URL assignment?

Related to #770

**Comment by jo-chemla** [comment]
Just saw that thread. I was cleaning an example based on the r3f components, and did notice the CesiumIonAuthPlugin assigns endpointUrl on init based on assetId, while GoogleAuthPlugin does not. I edited it to include a fallback google endpoint url on init as well 'https://tile.googleapis.com/v1/3dtiles/root.json'. Will do a PR with these and a few other minor fixes asap.
