### ISSUE TITLE
Adjust the texture processing threshold for Google Globe Tiles

### ISSUE THREAD

**Issue by wzq9** [NASA-AMMOS/3DTilesRendererJS#794]
* 3d-tiles-renderer version: 0.3.38
* three.js version: 0.168
 I am using Google Globe Tiles. When the camera is close to the model, the texture is clear, but when the camera is far away, the texture becomes blurry. How can I modify this processing threshold? I hope to keep the texture clear.

**Comment by gkjohnson** [comment]
Do you have an example of the issue? This is what things look like for me when zoomed out - I don't see particularly blurry textures:

<img width="692" alt="image" src="https://github.com/user-attachments/assets/6bc5e0fd-bb74-40fe-82ef-c49ec33ef854">

**Comment by wzq9** [comment]
Sure, I need to fine-tune the problem statement in order to more accurately showcase the model's performance. However, this needs to be done in a very similar context.
![image](https://github.com/user-attachments/assets/d35ae8db-13e9-4024-888d-0ecc9b0967b1)
The distant view effect of the camera model needs to be maintained or improved, rather than being as it is now by adjusting the LOD trigger distance.
![image](https://github.com/user-attachments/assets/cac50083-8cd0-4f42-ac63-2125aebf5deb)

**Comment by gkjohnson** [comment]
This is the nature of hierarchical levels of detail. Have you adjusted the error target? Lowering the error target will increase the detail but, of course, mean loading more data.

**Comment by wzq9** [comment]
Sure, this is exactly the effect I was hoping for.
