### ISSUE TITLE
r3f-dev branch: switching on and off TilesFadePlugin yields `TypeError: this.onBeforeCompile is null`

### ISSUE THREAD

**Issue by jo-chemla** [NASA-AMMOS/3DTilesRendererJS#796]
**Describe the bug**

With the current r3f-dev PR here https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/793 the leva controls let the user switch on and off some plugins like 
 - the `DebugTilesPlugin`, which does work
 - and `TilesFadePlugin`, which yields an error `TypeError: this.onBeforeCompile is null`

On top of this, the rendering is pretty odd when that fade-plugin has been switched back on, like if the fade effect is applied multiple times.

**Comment by gkjohnson** [comment]
Fixed in [6ff24c7](https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/805/commits/6ff24c764f6389270929e4e0f5b8be78f107809f)

**Comment by jo-chemla** [comment]
I can confirm this is fixed in latest r3f-dev, thanks!
