### ISSUE TITLE
Issue with "Test suite failed to run"

### ISSUE THREAD

**Issue by volodymyrprotskiy** [NASA-AMMOS/3DTilesRendererJS#797]
Hi, all!

I have run my Jest test after updating the 3d-tiles-renderer  from v0.3.31 to v0.3.38, and an error occurred. Could someone help here?

The error message: "Test suite failed to run. ReferenceError: TextDecoder is not defined."

<img width="769" alt="Screenshot 2024-10-09 at 17 59 00" src="https://github.com/user-attachments/assets/81edf715-c517-4d8e-88ef-8e3e230884ed">

**Comment by gkjohnson** [comment]
If TextDecoder isn't available then you're likely using an outdated version of node.js.

**Comment by volodymyrprotskiy** [comment]
I use "jsdom" as test environment

**Comment by gkjohnson** [comment]
If you've made modifications to the project you're not stating here then I can't help. The tests run with the versions of node used in the [ci](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/.github/workflows/node.js.yml#L19).

**Comment by gkjohnson** [comment]
Sorry - I see you're running tests in you're own project. If you're following the set up that jest and jsdom suggest then you'll need to report an issue at those repositories. TextDecoder is a valid JS class in the browser and node.js.

**Comment by volodymyrprotskiy** [comment]
The issue is related only to 0.3.38 version of the 3d-tiles-renderer lib, so I assume you can help me here

**Comment by volodymyrprotskiy** [comment]
The tests is running well with 3d-tiles-renderer v0.3.31, and only after updating the lib to v0.3.38 the issue with TextDecoder occured.
