### ISSUE TITLE
Instanced 3D Tiles - Getting attributes

### ISSUE THREAD

**Issue by AnthonyGlt** [NASA-AMMOS/3DTilesRendererJS#810]
Original issue : 
https://github.com/iTowns/itowns/issues/2434

> 
> Hi, I want to show attributes of Instanced 3D Tiles (I3dm), like it works with Batched 3D Tiles (b3dm)
> 
> Sample (does not work): Click on cube in https://www.itowns-project.org/itowns/examples/3dtiles_loader.html?tileset=https://bertt.github.io/cesium_3dtiles_samples/samples/instanced/traffic_lights/tileset.json
> 
> Cesium Sample shows attributes Id, Bevestiging on click on cube : https://bertt.github.io/cesium_3dtiles_samples/samples/instanced/traffic_lights/
> 
> ![image](https://github.com/user-attachments/assets/199c89aa-fac1-4894-9fa3-0f20eff248d9)
> 

I've tried to get the attributes from an i3dm dataset. By looking at the b3dm example, I've also tried to access the `batchid` from the selected geometry but it's missing.

Should I use an other attribute for this purpose ? Or should we add ourselves an id in the `i3dmLoader` for each instance ?

 

**To Reproduce**
I've used b3dm example
Replacing new B3DMLoader() by the I3DMLoader 
I've tried by using a subpart of the tileset from the original issue:
https://bertt.github.io/cesium_3dtiles_samples/samples/instanced/traffic_lights/tiles/0_1_9_0.i3dm

Thank you

**Comment by gkjohnson** [comment]
Instances can't have per-vertex ids the way B3DM files do. For instances you can compute the instance id based on the instance number or by reading the `BATCH_ID` field from the BatchTable at the same index. From the [BatchTable docs](https://github.com/CesiumGS/3d-tiles/blob/main/specification/TileFormats/BatchTable/README.adoc#json-header):

> The length of each array is equal to batchLength, which is specified in each tile format. This is the number of features in the tile. For example, batchLength may be the number of models in a b3dm tile, ***the number of instances in a i3dm tile***, or the number of points (or number of objects) in a pnts tile.

And from the [i3dm spec section on batch table semantics](https://github.com/CesiumGS/3d-tiles/blob/main/specification/TileFormats/Instanced3DModel/README.adoc#semantics): `BATCH_ID` can be present but is not required. So you have to resolve that id differently for instances.

If you have ideas on how to make this more ergonomic I'm open to suggestions.

**Comment by AnthonyGlt** [comment]
It seems that 
raycaster.intersectObject
also return the [instanceId](https://threejs.org/docs/#api/en/core/Raycaster.intersectObject)
And looks like it is the correct value.

Thank you
