### ISSUE TITLE
Help wanted: how do I change the location programatically by coordinates?

### ISSUE THREAD

**Issue by dnnsthnnr** [NASA-AMMOS/3DTilesRendererJS#816]
* 3d-tiles-renderer version: 0.3.39
* three.js version: 0.196.0

Hi there,

I need support figuring out how I can programmatically change the location from where I want the tiles to be rendered. I am first displaying a default location and after some input I want to display the location of the input.

I am using the 3D Tiles from Google Maps and I followed the following example: https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/googleMapsAerial.js

My approach current approach can be boiled down to: 
```
    // setting initial rendering location
    t.setLatLonToYUp( 52.520645 * MathUtils.DEG2RAD, 13.409779 * MathUtils.DEG2RAD); 

    // updating rendering location
    setInterval(() => {
      t.setLatLonToYUp(48.1363 * MathUtils.DEG2RAD, 11.5944*MathUtils.DEG2RAD)
    }, 5000)
```

The result I am facing is that the location change does render tiles what looks like from the below looking up:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/543e8618-8eeb-445b-a6e4-274908221df7">

In contrast to the rendering after the initial location setting:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/872b8373-19fc-4a9e-a1c5-94f371c39f88">

Can you please point me in the right direction on how I can dynamically change the coordinates of tiles rendered? Very much appreciated!

**Comment by gkjohnson** [comment]
The `setLatLonToYUp` positions the tiles based on the surface of the WGS84 ellipsoid at the given lat lon - however the geometry of the tiles are often not situated at the ellipsoid surface resulting in the geometry being higher than you want it to be. You can see that your issue has nothing to do with calling the function twice - just setting the orientation / position to the second lat lon results in the same view under the terrain.

You can address this by shifting the tile set down along y (ie set position.y to a negative value). If you'd like to automatically shift the tile set you'll have to do something like raycast the surface every frame and shift the terrain accordingly as tiles load in.

**Comment by dnnsthnnr** [comment]
Hi @gkjohnson thanks for the help!
Can I ask you to point me to an Raycast example if there is on?

**Comment by gkjohnson** [comment]
I don't have an example prepared but if you run into problems and can share a small example of what's not working for you I can point you in the right direction.
