### ISSUE TITLE
Full R3F example with npm imports

### ISSUE THREAD

**Issue by grahambates-code** [NASA-AMMOS/3DTilesRendererJS#817]
I dont know if I am experiencing a user error here, but I am struggling to get the R3F examples working in my own project, I am hitting issues with GLTF extentions not being found, would it be possible to show the r3f examples with npm imports instead of local/dev imports ?

**Comment by gkjohnson** [comment]
Without any information on what errors you're seeing or tile set you're using it's difficult to help. But I assume this is related to the DRACOLoader or KTXLoader when loading GLTF files?

The `GLTFExtensionsPlugin` is used [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/r3f/globe.jsx#L88) but it's not published with the project at the moment. Perhaps it will be moved to the core in the future. For now you'll have to copy the associated [file from the examples directory](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/src/plugins/GLTFExtensionsPlugin.js) to your own project to use it.

**Comment by gkjohnson** [comment]
I've updated the examples to use the npm package name as an import in [8b4a97a](https://github.com/NASA-AMMOS/3DTilesRendererJS/commit/8b4a97a8edcb2e94d33be982eb18147484b3c70c).
