### ISSUE TITLE
r3f: get basic sample working?

### ISSUE THREAD

**Issue by bertt** [NASA-AMMOS/3DTilesRendererJS#826]
Hi,

I'm trying to get the basic r3f sample working:

```
npx create-react-app my-app
cd my-app
npm install three @react-three/fiber 3d-tiles-renderer
npm run start
```

A basic three.js sample (https://r3f.docs.pmnd.rs/getting-started/your-first-scene) is working.

but with in app.js:

```
import { Canvas } from "@react-three/fiber";
import { TilesRenderer } from '3d-tiles-renderer/r3f';

const TILESET_URL ="https://bertt.github.io/cesium_3dtiles_samples/samples/b3dm/tileset.json";
export default function App() {
  return (
    <Canvas>
      <TilesRenderer url={ TILESET_URL } />
    </Canvas>
  );
}
```

I'm getting a webpack compile error, any idea?

<details>
<summary>Failed to compile -  Unexpected token (124:8)</summary>
Failed to compile.

Module parse failed: Unexpected token (124:8)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export function EnvironmentControls( props ) {
|
>       return <ControlsBaseComponent { ...props } controlsConstructor={ EnvironmentControlsImpl } />;
|
| }
ERROR in ./node_modules/3d-tiles-renderer/src/r3f/components/CameraControls.jsx 124:8
Module parse failed: Unexpected token (124:8)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export function EnvironmentControls( props ) {
| 
>       return <ControlsBaseComponent { ...props } controlsConstructor={ EnvironmentControlsImpl } />;
| 
| }

ERROR in ./node_modules/3d-tiles-renderer/src/r3f/components/CanvasDOMOverlay.jsx 47:2
Module parse failed: Unexpected token (47:2)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|       // render the children into the container
|       root.render(
>               <StrictMode>
|                       <div { ...rest }>
|                               { children }

ERROR in ./node_modules/3d-tiles-renderer/src/r3f/components/TilesAttributionOverlay.jsx 56:13
Module parse failed: Unexpected token (56:13)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|               if ( att.type === 'string' ) {
| 
>                       element = <div key={ i }>{ att.value }</div>;
| 
|               } else if ( att.type === 'html' ) {

ERROR in ./node_modules/3d-tiles-renderer/src/r3f/components/TilesRenderer.jsx 27:8
Module parse failed: Unexpected token (27:8)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|       }, [ tiles ] );
| 
>       return <group ref={ ref } matrixWorldAutoUpdate={ false } matrixAutoUpdate={ false }>{ children }</group>;
| 
| }

webpack compiled with 4 errors
</details>

**Comment by gkjohnson** [comment]
I don't know much about Webpack or create-react-app and why this wouldn't be working, but as far as I know create-react-app is defunct and should no longer be used. Is that not right? cc @drcmda

**Comment by bertt** [comment]
ok, so what's the recommended way to get the basic sample working?

**Comment by gkjohnson** [comment]
I'm not an expert in these build processes but this project uses Vite and is what I typically see recommended elsewhere. You can see other recommendations in the official react docs:

https://react.dev/learn/start-a-new-react-project

**Comment by bertt** [comment]
Got a step further, I see tileset.json is requested but no b3dm request (and empty screen). Maybe need to go to initial extent or so?

```
import { Canvas } from "@react-three/fiber";
import { TilesRenderer } from '3d-tiles-renderer/r3f';

const TILESET_URL = "https://bertt.github.io/3dtiles_cube/demo/dam/1.0/tileset.json";
export default function App() {
  return (
    <Canvas>
      <TilesRenderer url={ TILESET_URL } />
    </Canvas>
  );
}
```

**Comment by gkjohnson** [comment]
It looks like the camera needs to be positioned so the tile set is in view. You can do so with the "camera" property on the Canvas element. See the [Canvas component docs](https://r3f.docs.pmnd.rs/api/canvas) for react-three-fiber.

```jsx
<Canvas camera={ { position: [ x, y, z ] } }>
```
