### ISSUE TITLE
How to properly compute roof tilt from tile intersections in Google 3D Tiles?

### ISSUE THREAD

**Issue by LarisaYeskova** [NASA-AMMOS/3DTilesRendererJS#828]
* 3d-tiles-renderer version: "^0.3.39"
* three.js version: "^0.167.0"
* Link to your project: ---

Hello, 
First of all, thank you for the work you do.
I'm currently working with Google 3D Tiles in a Three.js environment and facing difficulties when trying to compute the correct tilt of a roof surface based on raycast intersections.

I'm using the following setup:

TilesRenderer for Google 3D Tiles
Raycasting to get intersection points on tiles

The issue I’m encountering is that when placing objects on roofs (like solar panels), the tilt of the object doesn't always align correctly with the roof surface. Additionally,  the panels seem to sink into the surface, and the orientation seems inaccurate.

Here’s what I’ve tried:

Raycasting to get the intersection point and surface normal.
Using Quaternion.setFromUnitVectors with the normal and world up vector.

However, I still get inconsistent panel placements, especially when working with roofs at different angles.

Is there a recommended way to calculate the correct orientation (tilt) based on the intersection point on 3D tiles? Any help or examples would be much appreciated!

**Comment by Dmitrijlagutkin** [comment]
I faced the same problem. I need to recognize the angles of the roof. In 3js the only available method is reycaster. But my quaternion is constantly getting strange values ​​and my objects are not being placed parallel to the base surface. Is there any way to interact with objects that are in a tile?

**Comment by gkjohnson** [comment]
Without images or any kind of example I can only guess at what the issue is.

But this may be a data source issue. The "Google Photorealistic Tiles" data is not precise - you can take a look at the wireframe or a lit version of the model to see that much of the geometry is fairly "wobbly". I would be surprised if you can get a accurate roof angle from the data set. Even if you average points.
