### ISSUE TITLE
Add example which implement the WebXR functionality on index example

### ISSUE THREAD

**Issue by psyntium** [NASA-AMMOS/3DTilesRendererJS#843]
Hi,

I'm still new with WebXR and 3D Tiles Renderer and I'm learning based on existing examples as starting from scratch would be too steep for learning.

I tried to copy & paste the codes from [vr.js](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/vr.js) to the [index.js](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/index.js) but it seems too complicated to implement the WebXR.

Please help to create the sample which makes use of the WebXR but have the capability to rotate, zoom-in/out as the on used in [index](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/index.js) example.

**Comment by gkjohnson** [comment]
Zooming in and out or rotating the camera is a achieved through head movement in VR, which the VR example shows. If you're interested in a different kind of object interaction in VR, though, I recommend asking at the [three.js discourse](https://discourse.threejs.org/) or discord channels which will apply to the 3d tiles interactions. General VR help and examples are outside the scope of this project, unfortunately.
